package task

type bbegin struct {
	count int
	name  string
	en    []string
	tj    []string
	ru    []string
}

func NewBeginTask() Task {
	b := &bbegin{
		count: 41,
		name:  "Begin",
	}
	b.makeEn()
	b.makeTj()
	b.makeRu()
	return b
}

func (b *bbegin) Count() int   { return b.count }
func (b *bbegin) Name() string { return b.name }
func (b *bbegin) En() []string { return b.en }
func (b *bbegin) Tj() []string { return b.tj }
func (b *bbegin) Ru() []string { return b.ru }

func (b *bbegin) makeEn() {
	b.en = make([]string, b.count)
	b.en[1] = `Given the side&nbsp;<i>a</i> of a square, find the perimeter&nbsp;<i>P</i> of the square: <i>P</i>&nbsp;=&nbsp;4&#183;<i>a</i>.`
	b.en[2] = `Given the side&nbsp;<i>a</i> of a square, find the area&nbsp;<i>S</i> of the square: <i>S</i>&nbsp;=&nbsp;<i>a</i><sup>2</sup>.`
	b.en[3] = `The sides&nbsp;<i>a</i> and&nbsp;<i>b</i> of a rectangle are given. Find the area&nbsp;<i>S</i>&nbsp;=&nbsp;<i>a</i>&#183;<i>b</i> and the perimeter&nbsp;<i>P</i>&nbsp;=&nbsp;2&#183;(<i>a</i>&nbsp;+&nbsp;<i>b</i>) of the rectangle.`
	b.en[4] = `Given the diameter&nbsp;<i>d</i> of a circle, find the length&nbsp;<i>L</i> of the circle: <i>L</i>&nbsp;=&nbsp;&#960;&#183;<i>d</i>. Use 3.14 for a value of &#960;.`
	b.en[5] = `Given the edge&nbsp;<i>a</i> of a cube, find the volume&nbsp;<i>V</i>&nbsp;=&nbsp;<i>a</i><sup>3</sup> and the surface area&nbsp;<i>S</i>&nbsp;=&nbsp;6&#183;<i>a</i><sup>2</sup> of the cube.`
	b.en[6] = `The edges&nbsp;<i>a</i>, <i>b</i>,&nbsp;<i>c</i> of a right parallelepiped are given. Find the volume&nbsp;<i>V</i>&nbsp;=&nbsp;<i>a&#183;b&#183;c</i> and the surface area&nbsp;<i>S</i>&nbsp;=&nbsp;2&#183;(<i>a&#183;b</i>&nbsp;+&nbsp;<i>b&#183;c</i>&nbsp;+&nbsp;<i>a&#183;c</i>) of the right parallelepiped.`
	b.en[7] = `Given the radius&nbsp;<i>R</i> of a circle, find the length&nbsp;<i>L</i> of the circumference and the area&nbsp;<i>S</i> of the circle: <i>L</i>&nbsp;=&nbsp;2&#183;&#960;&#183;<i>R</i>, &nbsp; &nbsp; &nbsp; &nbsp;<i>S</i>&nbsp;=&nbsp;&#960;&#183;<i>R</i><sup>2</sup>.Use 3.14 for a value of&nbsp;&#960;.`
	b.en[8] = `Given two numbers&nbsp;<i>a</i> and&nbsp;<i>b</i>, find their <i>average</i>: (<i>a</i>&nbsp;+&nbsp;<i>b</i>)/2.`
	b.en[9] = `Given two nonnegative numbers&nbsp;<i>a</i> and&nbsp;<i>b</i>, find their <i>geometrical mean</i> (a square root of their product): (<i>a</i>&#183;<i>b</i>)<sup>1/2</sup>.`
	b.en[10] = `Two nonzero numbers are given. Find the sum, the difference, the product, and the quotient of their squares.`
	b.en[11] = `Two nonzero numbers are given. Find the sum, the difference, the product, and the quotient of their absolute values.`
	b.en[12] = `The legs&nbsp;<i>a</i> and&nbsp;<i>b</i> of a right triangle are given. Find the hypotenuse&nbsp;<i>c</i> and the perimeter&nbsp;<i>P</i> of the triangle: <i>c</i>&nbsp;=&nbsp;(<i>a</i><sup>2</sup>&nbsp;+&nbsp;<i>b</i><sup>2</sup>)<sup>1/2</sup>, &nbsp; &nbsp; &nbsp; &nbsp;<i>P</i>&nbsp;=&nbsp;<i>a</i>&nbsp;+&nbsp;<i>b</i>&nbsp;+&nbsp;<i>c</i>`
	b.en[13] = `Given the radiuses&nbsp;<i>R</i><sub>1</sub> and&nbsp;<i>R</i><sub>2</sub> of two concentric circles (<i>R</i><sub>1</sub>&nbsp;&gt;&nbsp;<i>R</i><sub>2</sub>), find the areas&nbsp;<i>S</i><sub>1</sub> and&nbsp;<i>S</i><sub>2</sub> of the circles and the area&nbsp;<i>S</i><sub>3</sub> of the ring bounded by the circles: <i>S</i><sub>1</sub>&nbsp;=&nbsp;&#960;&#183;(<i>R</i><sub>1</sub>)<sup>2</sup>, &nbsp; &nbsp; &nbsp; &nbsp;<i>S</i><sub>2</sub>&nbsp;=&nbsp;&#960;&#183;(<i>R</i><sub>2</sub>)<sup>2</sup>, &nbsp; &nbsp; &nbsp; &nbsp;<i>S</i><sub>3</sub>&nbsp;=&nbsp;<i>S</i><sub>1</sub>&nbsp;&#8722;&nbsp;<i>S</i><sub>2</sub>.Use 3.14 for a value of&nbsp;&#960;.`
	b.en[14] = `Given the length&nbsp;<i>L</i> of a circumference, find the radius&nbsp;<i>R</i> and the area&nbsp;<i>S</i> of the circle. Take into account that <i>L</i>&nbsp;=&nbsp;2&#183;&#960;&#183;<i>R</i>, &nbsp; &nbsp;<i>S</i>&nbsp;=&nbsp;&#960;&#183;<i>R</i><sup>2</sup>. Use 3.14 for a value of&nbsp;&#960;.`
	b.en[15] = `Given the area&nbsp;<i>S</i> of a circle, find the diameter&nbsp;<i>D</i> and the length&nbsp;<i>L</i> of the circumference. Take into account that <i>L</i>&nbsp;=&nbsp;&#960;&#183;<i>D</i>, &nbsp; &nbsp;<i>S</i>&nbsp;=&nbsp;&#960;&#183;<i>D</i><sup>2</sup>/4. Use 3.14 for a value of&nbsp;&#960;.`
	b.en[16] = `Two points with the coordinates&nbsp;<i>x</i><sub>1</sub> and&nbsp;<i>x</i><sub>2</sub> are given on the real axis. Find the distance between these points: |<i>x</i><sub>2</sub>&nbsp;&#8722;&nbsp;<i>x</i><sub>1</sub>|.`
	b.en[17] = `Three points&nbsp;<i>A</i>, <i>B</i>,&nbsp;<i>C</i> are given on the real axis. Find the length of&nbsp;<i>AC</i>, the length of&nbsp;<i>BC</i>, and the sum of these lengths.`
	b.en[18] = `Three points&nbsp;<i>A</i>, <i>B</i>,&nbsp;<i>C</i> are given on the real axis, the point&nbsp;<i>C</i> is located between the points&nbsp;<i>A</i> and&nbsp;<i>B</i>. Find the product of the length of&nbsp;<i>AC</i> and the length of&nbsp;<i>BC</i>.`
	b.en[19] = `The coordinates (<i>x</i><sub>1</sub>,&nbsp;<i>y</i><sub>1</sub>) and (<i>x</i><sub>2</sub>,&nbsp;<i>y</i><sub>2</sub>) of two opposite vertices of a rectangle are given. Sides of the rectangle are parallel to coordinate axes. Find the perimeter and the area of the rectangle.`
	b.en[20] = `The coordinates (<i>x</i><sub>1</sub>,&nbsp;<i>y</i><sub>1</sub>) and (<i>x</i><sub>2</sub>,&nbsp;<i>y</i><sub>2</sub>) of two points are given. Find the distance between the points:  ((<i>x</i><sub>2</sub>&nbsp;&#8722;&nbsp;<i>x</i><sub>1</sub>)<sup>2</sup>&nbsp;+&nbsp;(<i>y</i><sub>2</sub>&nbsp;&#8722;&nbsp;<i>y</i><sub>1</sub>)<sup>2</sup>)<sup>1/2</sup>`
	b.en[21] = `The coordinates (<i>x</i><sub>1</sub>,&nbsp;<i>y</i><sub>1</sub>), (<i>x</i><sub>2</sub>,&nbsp;<i>y</i><sub>2</sub>), (<i>x</i><sub>3</sub>,&nbsp;<i>y</i><sub>3</sub>) of the triangle vertices are given. Find the perimeter and the area of the triangle using the formula for distance between two points in the plane (see Begin20). The area of a triangle with sides&nbsp;<i>a</i>, <i>b</i>,&nbsp;<i>c</i> can be found by <i>Heron formula</i>: <i>S</i>&nbsp;=&nbsp;(<i>p</i>&#183;(<i>p</i>&nbsp;&#8722;&nbsp;<i>a</i>)&#183;(<i>p</i>&nbsp;&#8722;&nbsp;<i>b</i>)&#183;(<i>p</i>&nbsp;&#8722;&nbsp;<i>c</i>))<sup>1/2</sup>,where <i>p</i>&nbsp;=&nbsp;(<i>a</i>&nbsp;+&nbsp;<i>b</i>&nbsp;+&nbsp;<i>c</i>)/2 is the <i>half-perimeter</i>.`
	b.en[22] = `Exchange the values of two given variables&nbsp;<i>A</i> and&nbsp;<i>B</i>. Output the new values of&nbsp;<i>A</i> and&nbsp;<i>B</i>.`
	b.en[23] = `Variables&nbsp;<i>A</i>, <i>B</i>,&nbsp;<i>C</i> are given. Change values of the variables by moving the given value of&nbsp;<i>A</i> into the variable&nbsp;<i>B</i>, the given value of&nbsp;<i>B</i> into the variable&nbsp;<i>C</i>, and the given value of&nbsp;<i>C</i> into the variable&nbsp;<i>A</i>. Output the new values of&nbsp;<i>A</i>, <i>B</i>,&nbsp;<i>C</i>.`
	b.en[24] = `Variables&nbsp;<i>A</i>, <i>B</i>,&nbsp;<i>C</i> are given. Change values of the variables by moving the given value of&nbsp;<i>A</i> into the variable&nbsp;<i>C</i>, the given value of&nbsp;<i>C</i> into the variable&nbsp;<i>B</i>, and the given value of&nbsp;<i>B</i> into the variable&nbsp;<i>A</i>. Output the new values of&nbsp;<i>A</i>, <i>B</i>,&nbsp;<i>C</i>.`
	b.en[25] = `Given an independent variable&nbsp;<i>x</i>, find the value of a function <i>y</i>&nbsp;=&nbsp;3<i>x</i><sup>6</sup>&nbsp;&#8722;&nbsp;6<i>x</i><sup>2</sup>&nbsp;&#8722;&nbsp;7.`
	b.en[26] = `Given an independent variable&nbsp;<i>x</i>, find the value of a function <i>y</i>&nbsp;=&nbsp;4(<i>x</i>&#8722;3)<sup>6</sup>&nbsp;&#8722;&nbsp;7(<i>x</i>&#8722;3)<sup>3</sup>&nbsp;+&nbsp;2.`
	b.en[27] = `Given a number&nbsp;<i>A</i>, compute a power&nbsp;<i>A</i><sup>8</sup> using three multiplying operators for computing <i>A</i><sup>2</sup>, <i>A</i><sup>4</sup>, <i>A</i><sup>8</sup> sequentially. Output all obtained powers of the number&nbsp;<i>A</i>.`
	b.en[28] = `Given a number&nbsp;<i>A</i>, compute a power <i>A</i><sup>15</sup> using five multiplying operators for computing <i>A</i><sup>2</sup>, <i>A</i><sup>3</sup>, <i>A</i><sup>5</sup>, <i>A</i><sup>10</sup>, <i>A</i><sup>15</sup> sequentially. Output all obtained powers of the number&nbsp;<i>A</i>.`
	b.en[29] = `The angle value&nbsp;&#945; in degrees (0&nbsp;&#8804;&nbsp;&#945;&nbsp;&lt;&nbsp;360) is given. Convert this value into radians. Take into account that 180&#176; = &#960; radians. Use 3.14 for a value of&nbsp;&#960;.`
	b.en[30] = `The angle value&nbsp;&#945; in radians (0&nbsp;&#8804;&nbsp;&#945;&nbsp;&lt;&nbsp;2&#183;&#960;) is given. Convert this value into degrees. Take into account that 180&#176; = &#960; radians. Use 3.14 for a value of&nbsp;&#960;.`
	b.en[31] = `A Fahrenheit temperature&nbsp;<i>T</i> is given. Convert it into a centigrade temperature. The centigrade temperature&nbsp;<i>T</i><sub><i>C</i></sub> and the Fahrenheit temperature&nbsp;<i>T</i><sub><i>F</i></sub> are connected as:<i>T</i><sub><i>C</i></sub> = (<i>T</i><sub><i>F</i></sub> &#8722; 32)&#183;5/9`
	b.en[32] = `A centigrade temperature&nbsp;<i>T</i> is given. Convert it into a Fahrenheit temperature. The centigrade temperature&nbsp;<i>T</i><sub><i>C</i></sub> and the Fahrenheit temperature&nbsp;<i>T</i><sub><i>F</i></sub> are connected as:<i>T</i><sub><i>C</i></sub> = (<i>T</i><sub><i>F</i></sub> &#8722; 32)&#183;5/9`
	b.en[33] = `<i>X</i> kg of sweet cost <i>A</i>&nbsp;euro. Find the cost of 1&nbsp;kg and <i>Y</i>&nbsp;kg of the sweets (positive numbers&nbsp;<i>X</i>, <i>A</i>,&nbsp;<i>Y</i> are given).`
	b.en[34] = `<i>X</i>&nbsp;kg of chocolates cost <i>A</i>&nbsp;euro and <i>Y</i>&nbsp;kg of sugar candies cost <i>B</i>&nbsp;euro (positive numbers&nbsp;<i>X</i>, <i>A</i>, <i>Y</i>,&nbsp;<i>B</i> are given). Find the cost of 1&nbsp;kg of the chocolates and the cost of 1&nbsp;kg of the sugar candies. Also determine how many times the chocolates are more expensive than the sugar candies.`
	b.en[35] = `A boat velocity in still water is <i>V</i>&nbsp;km/h, river flow velocity is <i>U</i>&nbsp;km/h (<i>U</i>&nbsp;&lt;&nbsp;<i>V</i>). The boat goes along the lake during <i>T</i><sub>1</sub>&nbsp;h and then goes against stream of the river during <i>T</i><sub>2</sub>&nbsp;h. Positive numbers&nbsp;<i>V</i>, <i>U</i>, <i>T</i><sub>1</sub>,&nbsp;<i>T</i><sub>2</sub> are given. Find the distance&nbsp;<i>S</i> covered by the boat (distance = time &#183; velocity).`
	b.en[36] = `The velocity of the first car is <i>V</i><sub>1</sub>&nbsp;km/h, the velocity of the second car is <i>V</i><sub>2</sub>&nbsp;km/h, the initial distance between the cars is <i>S</i>&nbsp;km. Find the distance between the cars after <i>T</i>&nbsp;hours provided that the distance is increasing. The required distance is equal to a sum of the initial distance and the total distance covered by the both cars (total distance = time &#183; total velocity).`
	b.en[37] = `The velocity of the first car is <i>V</i><sub>1</sub>&nbsp;km/h, the velocity of the second car is <i>V</i><sub>2</sub>&nbsp;km/h, the initial distance between the cars is <i>S</i>&nbsp;km. Find the distance between the cars after <i>T</i>&nbsp;hours provided that at the start time the distance is decreasing. This distance is equal to an absolute value of a difference between the initial distance and the total distance covered by the both cars.`
	b.en[38] = `Solve a linear equation <i>A</i>&#183;<i>x</i>&nbsp;+&nbsp;<i>B</i>&nbsp;=&nbsp;0 with given coefficients&nbsp;<i>A</i> and&nbsp;<i>B</i> (<i>A</i> is not equal to 0).`
	b.en[39] = `Solve a <i>quadratic equation</i> <i>A</i>&#183;<i>x</i><sup>2</sup>&nbsp;+&nbsp;<i>B</i>&#183;<i>x</i>&nbsp;+&nbsp;<i>C</i>&nbsp;=&nbsp;0 with given coefficients <i>A</i>, <i>B</i>,&nbsp;<i>C</i> (<i>A</i> and the discriminant of the equation are positive). Output the smaller equation root and then the larger one. Roots of the quadratic equation may be found by formula <i>x</i><sub>1,&nbsp;2</sub> = (&#8722;<i>B</i>&nbsp;&#177;&nbsp;(<i>D</i>)<sup>1/2</sup>)/(2&#183;<i>A</i>),where <i>D</i>&nbsp;=&nbsp;<i>B</i><sup>2</sup>&nbsp;&#8722;&nbsp;4&#183;<i>A</i>&#183;<i>C</i> is a <i>discriminant</i>.`
	b.en[40] = `Solve a <i>system of linear equations</i> <i>A</i><sub>1</sub>&#183;<i>x</i>&nbsp;+&nbsp;<i>B</i><sub>1</sub>&#183;<i>y</i> = <i>C</i><sub>1</sub>,<br><i>A</i><sub>2</sub>&#183;<i>x</i>&nbsp;+&nbsp;<i>B</i><sub>2</sub>&#183;<i>y</i> = <i>C</i><sub>2</sub>with given coefficients <i>A</i><sub>1</sub>, <i>B</i><sub>1</sub>, <i>C</i><sub>1</sub>, <i>A</i><sub>2</sub>, <i>B</i><sub>2</sub>, <i>C</i><sub>2</sub> provided that the system has the only solution. Use the following formulas: <i>x</i> = (<i>C</i><sub>1</sub>&#183;<i>B</i><sub>2</sub>&nbsp;&#8722;&nbsp;<i>C</i><sub>2</sub>&#183;<i>B</i><sub>1</sub>)/<i>D</i>, &nbsp; &nbsp; &nbsp; &nbsp;<i>y</i> = (<i>A</i><sub>1</sub>&#183;<i>C</i><sub>2</sub>&nbsp;&#8722;&nbsp;<i>A</i><sub>2</sub>&#183;<i>C</i><sub>1</sub>)/<i>D</i>,<br>where <i>D</i> = <i>A</i><sub>1</sub>&#183;<i>B</i><sub>2</sub>&nbsp;&#8722;&nbsp;<i>A</i><sub>2</sub>&#183;<i>B</i><sub>1</sub>`
}

func (b *bbegin) makeTj() {
	b.tj = make([]string, b.count)
	b.tj[1] = `Тарафи квадрат а дода шудааст. Периметри он Р = 4*a ёфта шавад.`
	b.tj[2] = `Тарафи квадрат a дода шудааст. Масоҳати он S = a<sup>2</sup> ёфта шавад.`
	b.tj[3] = `Тарафҳои росткунҷа a ва b дода шудаанд. Масоҳати он S=a*b ва периметри он P=2*(a+b) ёфта шаванд.`
	b.tj[4] = `Диаметри давра d дода шудааст. Дарозии он L=PI*d ёфта шавад. Ба сифати қимати PI 3.14 истифода бурда шавад.`
	b.tj[5] = `Дарозии рӯяи куб a дода шудааст. Ҳаҷми куб V=a<sup>3</sup> ва масоҳати сатҳи болоии он S=6*a<sup>2</sup> ёфта шаванд.`
	b.tj[6] = `Дарозиҳои рӯяҳои параллелопипеди росткунҷа a, b, c дода шудаанд. Ҳаҷми он V=a*b*c ва масоҳати сатҳи болоии он S=2*(a*b+b*c+a*c) ёфта шаванд.`
	b.tj[7] = `Дарозии давра L ва масоҳати доира S ёфта шаванд, агар радиус R дода шуда бошад: L=2*PI*R, S=PI*R<sup>2</sup>. Ба сифати қимати PI 3.14 истифода бурда шавад.`
	b.tj[8] = `Ду ададҳо a ва b дода шудаанд. Қимати миёнаи арифметикии онҳо: (a+b)/2 ёфта шавад.`
	b.tj[9] = `Ду ададҳои ғайриманфӣ a ва b дода шудаанд. Қимати миёнаи геометрии онҳо ёфта шавад, яъне решаи квадратӣ аз ҳосилизарби онҳо sqrt(a*b).`
	b.tj[10] = `Ду ададҳои ғайринулӣ дода шудаанд. Сумма, фарқ, ҳосилизарб ва ҳосилитақсими квадратҳои онҳо ёфта шаванд.`
	b.tj[11] = `Ду ададҳои ғайринулӣ дода шудаанд. Сумма, фарқ, ҳосилизарб ва ҳосилитақсими қиматҳои мутлақи онҳо ёфта шаванд.`
	b.tj[12] = `Катетҳои секунҷаи росткунҷа a ва b дода шудаанд. Гипотенуза c ва периметри он P ёфта шаванд: c=sqrt(a<sup>2</sup>+b<sup>2</sup>), P=a+b+c.`
	b.tj[13] = `Ду доираҳо бо маркази умумӣ ва радиусҳои R<sub>1</sub> ва R<sub>2</sub> (R<sub>1</sub>>R<sub>2</sub>) дода шудаанд. Масоҳатҳои ин доираҳо S<sub>1</sub> ва S<sub>2</sub>, ҳамчунин масоҳати ҳалқае S<sub>3</sub>, ки радиуси беруниаш баробари R<sub>1</sub> ва радиуси дохилиаш баробари R<sub>2</sub> ҳастанд, ёфта шаванд: S<sub>1</sub>=PI*R<sub>1</sub><sup>2</sup>, S<sub>2</sub>=PI*R<sub>2</sub><sup>2</sup>, S<sub>3</sub>=S<sub>1</sub>-S<sub>2</sub>.`
	b.tj[14] = `Дарозии давра L дода шудааст. Радиуси он R ва масоҳати доирае S ки, бо ин давра маҳдуд аст, бо назардошти он, ки L=2*PI*R, S=PI*R<sup>2</sup> аст, ёфта шаванд. Ба сифати қимати PI 3.14 истифода бурда шавад.`
	b.tj[15] = `Масоҳати доира S дода шудааст. Диаметри он D ва дарозии даврае L, ки ин доираро маҳдуд мекунад, бо дарназардошти он, ки L=PI*D, S=PI*D<sup>2</sup>/4 аст, ёфта шаванд. Ба сифати қимати PI 3.14 истифода бурда шавад.`
	b.tj[16] = `Масофаи байни ду нуқта бо координатаҳои додашудаи x<sub>1</sub> ва x<sub>2</sub> дар тири ададӣ ёфта шавад: |x<sub>2</sub> - x<sub>1</sub>|.`
	b.tj[17] = `Се нуқтаҳо A, B, C дар тири ададӣ дода шудаанд. Дарозиҳои порчаҳои AC ва BC ва суммаи онҳо ёфта шаванд.`
	b.tj[18] = `Се нуқтаҳо A, B, C дар тири ададӣ дода шудаанд. Нуқтаи C дар байни нуқтаҳои A ва B ҷойгир аст. Ҳосилизарби дарозиҳои порчаҳои AC ва BC ёфта шавад.`
	b.tj[19] = `Координатаҳои ду қуллаҳои муқобили росткунҷа дода шудаанд:(x<sub>1</sub>,y<sub>1</sub>), (x<sub>2</sub>,y<sub>2</sub>). Тарафҳои росткунҷа ба тирҳои координатӣ параллел мебошанд. Периметр ва масоҳати росткунҷаи додашуда ёфта шаванд.`
	b.tj[20] = `Масофаи байни ду нуқтаҳо бо координатаҳои додашудаи (x<sub>1</sub>,y<sub>1</sub>) ва (x<sub>2</sub>,y<sub>2</sub>) дар ҳамворӣ ёфта шавад. Масофа аз рӯи формулаи зерин ҳисоб карда мешавад: sqrt((x<sub>2</sub>-x<sub>1</sub>)<sup>2</sup>+(y<sub>2</sub>-y<sub>1</sub>)<sup>2</sup>).`
	b.tj[21] = `Координатаҳои се қуллаҳои секунҷа:(x<sub>1</sub>,y<sub>1</sub>), (x<sub>2</sub>,y<sub>2</sub>), (x<sub>3</sub>,y<sub>3</sub>) дода шудаанд. Периметр ва масоҳати он бо истифодабарии формулаи масофаи байни ду нуқта дар ҳамворӣ (ниг. ба масъалаи Begin20) ёфта шаванд. Барои ёфтани масоҳати секунҷа бо тарафҳои a, b, c формулаи Ҳерон истифода бурда шавад: S=sqrt(p*(p-a)*(p-b)*(p-c)), дар ин ҷо p=(a+b+c)/2 - нимпериметр.`
	b.tj[22] = `Ҷойҳои қиматҳои тағйирёбандаҳои A ва B иваз карда шаванд ва қиматҳои нави A ва B хориҷ карда шаванд.`
	b.tj[23] = `Тағйирёбандаҳои A, B, C дода шудаанд. Қиматҳои онҳо бо ҷойивазкунии қимати A ба B, B ба C, C ба A иваз карда шаванд ва қиматҳои нави тағйирёбандаҳои A, B, C хориҷ карда шаванд.`
	b.tj[24] = `Тағйирёбандаҳои A, B, C дода шудаанд. Қиматҳои онҳо бо ҷойивазкунии қимати A ба C, C ба B, B ба A иваз карда шаванд ва қиматҳои нави тағйирёбандаҳои A, B, C хориҷ карда шаванд.`
	b.tj[25] = `Қимати функсияи y=3*x<sup>6</sup>-6*x<sup>2</sup>-7 ҳангоми дода шудани қимати x ёфта шавад.`
	b.tj[26] = `Қимати функсияи y=4*(x-3)<sup>6</sup>-7*(x-3)<sup>3</sup>+2 ҳангоми дода шудани қимати x ёфта шавад.`
	b.tj[27] = `Адади A дода шудааст. Бо истифодабарии тағйирёбандаи ёридиҳанда ва се амалиёти зарбкунӣ A<sup>8</sup>-ро ҳисоб кунед. Барои ин пай дар пай A<sup>2</sup>, A<sup>4</sup>, A<sup>8</sup>-ро ёфтан лозим меояд. Ҳамаи дараҷаҳои ёфташудаи адади A хориҷ карда шаванд.`
	b.tj[28] = `Адади A дода шудааст. Бо истифодабарии ду тағйирёбандҳои ёридиҳанда ва панҷ амалиёти зарбкунӣ A<sup>15</sup>-ро ҳисоб кунед. Барои ин пай дар пай A<sup>2</sup>, A<sup>3</sup>, A<sup>5</sup>, A<sup>10</sup>, A<sup>15</sup>-ро ёфтан лозим меояд. Ҳамаи дараҷаҳои ёфташудаи адади A хориҷ карда шаванд.`
	b.tj[29] = `Қимати кунҷ бо градус дода шудааст (0&lt;a&lt;360). Қимати ҳамин кунҷро бо радиан ёбед, бо дарназардошти он, ки 180<sup>o</sup> = PI радиан аст. Ба сифати қимати PI 3.14 истифода бурда шавад.`
	b.tj[30] = `Қимати кунҷ бо радиан дода шудааст (0&lt;a&lt;2*PI). Қимати ҳамин кунҷро бо градус ёбед, бо дарназардошти он, ки 180<sup>o</sup> = PI радиан аст. Ба сифати қимати PI 3.14 истифода бурда шавад.`
	b.tj[31] = `Қимати ҳарорат T бо градуси Фаренгейт дода шудааст. Қимати ҳамин ҳароратро бо градуси Селсий ёбед. Ҳарорати Селсий T<sub>C</sub> ва ҳарорати Фаренгейт T<sub>F</sub> аз рӯи муносибати зерин алоқаманданд: T<sub>C</sub>=(T<sub>F</sub>-32)*5/9.`
	b.tj[32] = `Қимати ҳарорат T бо градуси Селсий дода шудааст. Қимати ҳамин ҳароратро бо градуси Фаренгейт ёбед. Ҳарорати Селсий T<sub>C</sub> ва ҳарорати Фаренгейт T<sub>F</sub> аз рӯи муносибати зерин алоқаманданд: T<sub>C</sub>=(T<sub>F</sub>-32)*5/9.`
	b.tj[33] = `Маълум аст, ки X кг қанд A сомонӣ арзиш дорад. Муайян кунед, ки 1 кг ва Y кг -и ҳамин қанд чӣ қадар арзиш дорад.`
	b.tj[34] = `Маълум аст, ки X кг шоколад A сомонӣ арзиш дорад ва Y кг ирис B сомонӣ арзиш дорад. Муайян кунед, ки 1 кг шоколад ва 1 кг ирис чӣ қадар арзиш доранд, ҳамчунин чанд маротиба шоколад аз ирис қиматтар аст.`
	b.tj[35] = `Суръати киштӣ дар оби ором V км/ст аст, суръати ҷараёни дарё бошад, U км/ст (U&lt;V) аст. Вақти ҳаракати киштӣ дар кӯл T<sub>1</sub> соат буда, дар дарё (бар зидди ҷараён) - T<sub>2</sub> соат аст. Роҳи тайкардаи киштӣ S ёфта шавад (роҳ=вақт*суръат). Бояд ба назар гирифт, ки ҳангоми ҳаракат ба муқобили ҷараён суръати киштӣ ба бузургии суръати ҷараён кам мешавад.`
	b.tj[36] = `Суръати мошини якӯм V<sub>1</sub> км/ст, дуюм - V<sub>2</sub> км/ст буда, масофаи байни онҳо S км аст. Масофаи байни онҳоро пас аз T соат ҳисоб кунед, агар мошинҳо аз якдигарашон дур шаванд. Масофаи мазкур ба суммаи масофаи аввала ва роҳи умумии тайкардаи мошинҳо баробар аст; роҳи_умумӣ=вақт*суръати_умумӣ.`
	b.tj[37] = `Суръати мошини якӯм V<sub>1</sub> км/ст, дуюм - V<sub>2</sub> км/ст буда, масофаи байни онҳо S км аст. Масофаи байни онҳоро пас аз T соат муайян кунед, агар мошинҳо мисли пешина ба муқобили якдигар ҳаракат кунанд. Масофаи мазкур ба қимати мутлақи фарқи масофаи аввала ва роҳи умумии тайкардаи мошинҳо баробар аст; роҳи_умумӣ=вақт*суръати_умумӣ.`
	b.tj[38] = `Муодилаи хаттии A*x+B=0 бо коэффитсиентҳои додашудаи A ва B (коэффитсиенти A НОбаробари 0 аст) ҳал карда шавад.`
	b.tj[39] = `Решаҳои муодилаи квадратии A*x<sup>2</sup>+B*x+C=0 бо коффитсиентҳои додашудаи A, B, C (коэффитсиенти A НОбаробари 0 аст) ёфта шаванд, агар маълум бошад, ки дискриминанти муодила мусбат аст. Дар аввал решаи хурд ва сонӣ решаи калони ёфташуда хориҷ карда шаванд. Решаҳои муодилаи квадратӣ аз рӯи формулаи x<sub>1,2</sub>=(-B+-sqrt(D))/(2*a) ёфта мешаванд, ки дар ин ҷо D-дискриминант аст, D=B<sup>2</sup>-4*A*C.`
	b.tj[40] = `Ҳалли системаи муодилаҳои хаттии намуди A<sub>1</sub>*x+B<sub>1</sub>*y=C<sub>1</sub>, A<sub>2</sub>*x+B<sub>2</sub>*y=C</sub>2</sub> бо коэффитсиентҳои додашудаи A<sub>1</sub>, B<sub>1</sub>, C<sub>1</sub>, A<sub>2</sub>, B<sub>2</sub>, C<sub>2</sub> ёфта шавад, агар маълум бошад, ки системаи мазкур ҳалли ягона дорад. Аз формулаҳои x=(C<sub>1</sub>*B<sub>2</sub>-C<sub>2</sub>*B<sub>1</sub>)/D, y=(A<sub>1</sub>*C<sub>2</sub>-A<sub>2</sub>*C<sub>1</sub>)/D истифода баред, ки дар ин ҷо D=A<sub>1</sub>*B<sub>2</sub>-A<sub>2</sub>*B<sub>1</sub> аст.`
}

func (b *bbegin) makeRu() {
	b.ru = make([]string, b.count)
	b.ru[1] = `Дана сторона квадрата&nbsp;<i>a</i>. Найти его периметр&nbsp;<i>P</i>&nbsp;=&nbsp;4&#183;<i>a</i>.`
	b.ru[2] = `Дана сторона квадрата&nbsp;<i>a</i>. Найти его площадь&nbsp;<i>S</i>&nbsp;=&nbsp;<i>a</i><sup>2</sup>.`
	b.ru[3] = `Даны стороны прямоугольника&nbsp;<i>a</i> и&nbsp;<i>b</i>.  Найти его площадь&nbsp;<i>S</i>&nbsp;=&nbsp;<i>a</i>&#183;<i>b</i> и периметр&nbsp;<i>P</i>&nbsp;=&nbsp;2&#183;(<i>a</i>&nbsp;+&nbsp;<i>b</i>).`
	b.ru[4] = `Дан диаметр окружности&nbsp;<i>d</i>. Найти ее длину&nbsp;<i>L</i>&nbsp;=&nbsp;&#960;&#183;<i>d</i>. В качестве значения&nbsp;&#960; использовать&nbsp;3.14.`
	b.ru[5] = `Дана длина ребра куба&nbsp;<i>a</i>. Найти объем куба&nbsp;<i>V</i>&nbsp;=&nbsp;<i>a</i><sup>3</sup> и площадь его поверхности&nbsp;<i>S</i>&nbsp;=&nbsp;6&#183;<i>a</i><sup>2</sup>.`
	b.ru[6] = `Даны длины ребер&nbsp;<i>a</i>, <i>b</i>, <i>c</i> прямоугольного параллелепипеда. Найти его объем&nbsp;<i>V</i>&nbsp;=&nbsp;<i>a&#183;b&#183;c</i> и площадь поверхности&nbsp;<i>S</i>&nbsp;=&nbsp;2&#183;(<i>a&#183;b</i>&nbsp;+&nbsp;<i>b&#183;c</i>&nbsp;+&nbsp;<i>a&#183;c</i>).`
	b.ru[7] = `Найти длину окружности&nbsp;<i>L</i> и площадь круга&nbsp;<i>S</i> заданного радиуса&nbsp;<i>R</i>: <i>L</i>&nbsp;=&nbsp;2&#183;&#960;&#183;<i>R</i>, &nbsp; &nbsp; &nbsp; &nbsp;<i>S</i>&nbsp;=&nbsp;&#960;&#183;<i>R</i><sup>2</sup>.В качестве значения&nbsp;&#960; использовать&nbsp;3.14.`
	b.ru[8] = `Даны два числа&nbsp;<i>a</i> и&nbsp;<i>b</i>. Найти их <i>среднее арифметическое</i>: (<i>a</i>&nbsp;+&nbsp;<i>b</i>)/2.`
	b.ru[9] = `Даны два неотрицательных числа&nbsp;<i>a</i> и&nbsp;<i>b</i>. Найти их <i>среднее геометрическое</i>, т.&nbsp;е. квадратный корень из их произведения: (<i>a</i>&#183;<i>b</i>)<sup>1/2</sup>.`
	b.ru[10] = `Даны два ненулевых числа. Найти сумму, разность, произведение и частное их квадратов.`
	b.ru[11] = `Даны два ненулевых числа. Найти сумму, разность, произведение и частное их модулей.`
	b.ru[12] = `Даны катеты прямоугольного треугольника&nbsp;<i>a</i> и&nbsp;<i>b</i>. Найти его гипотенузу&nbsp;<i>c</i> и периметр&nbsp;<i>P</i>: <i>c</i>&nbsp;=&nbsp;(<i>a</i><sup>2</sup>&nbsp;+&nbsp;<i>b</i><sup>2</sup>)<sup>1/2</sup>, &nbsp; &nbsp; &nbsp; &nbsp;<i>P</i>&nbsp;=&nbsp;<i>a</i>&nbsp;+&nbsp;<i>b</i>&nbsp;+&nbsp;<i>c</i>`
	b.ru[13] = `Даны два круга с общим центром и радиусами&nbsp;<i>R</i><sub>1</sub> и&nbsp;<i>R</i><sub>2</sub> (<i>R</i><sub>1</sub>&nbsp;&gt;&nbsp;<i>R</i><sub>2</sub>). Найти площади этих кругов&nbsp;<i>S</i><sub>1</sub> и&nbsp;<i>S</i><sub>2</sub>, а также площадь&nbsp;<i>S</i><sub>3</sub> кольца, внешний радиус которого равен&nbsp;<i>R</i><sub>1</sub>, а внутренний радиус равен&nbsp;<i>R</i><sub>2</sub>: <i>S</i><sub>1</sub>&nbsp;=&nbsp;&#960;&#183;(<i>R</i><sub>1</sub>)<sup>2</sup>, &nbsp; &nbsp; &nbsp; &nbsp;<i>S</i><sub>2</sub>&nbsp;=&nbsp;&#960;&#183;(<i>R</i><sub>2</sub>)<sup>2</sup>, &nbsp; &nbsp; &nbsp; &nbsp;<i>S</i><sub>3</sub>&nbsp;=&nbsp;<i>S</i><sub>1</sub>&nbsp;&#8722;&nbsp;<i>S</i><sub>2</sub>.В качестве значения&nbsp;&#960; использовать&nbsp;3.14.`
	b.ru[14] = `Дана длина&nbsp;<i>L</i> окружности. Найти ее радиус&nbsp;<i>R</i> и площадь&nbsp;<i>S</i> круга, ограниченного этой окружностью, учитывая, что <i>L</i>&nbsp;=&nbsp;2&#183;&#960;&#183;<i>R</i>, &nbsp; &nbsp;<i>S</i>&nbsp;=&nbsp;&#960;&#183;<i>R</i><sup>2</sup>. В качестве значения&nbsp;&#960; использовать&nbsp;3.14.`
	b.ru[15] = `Дана площадь&nbsp;<i>S</i> круга. Найти его диаметр&nbsp;<i>D</i> и длину&nbsp;<i>L</i> окружности, ограничивающей этот круг, учитывая, что <i>L</i>&nbsp;=&nbsp;&#960;&#183;<i>D</i>, &nbsp; &nbsp;<i>S</i>&nbsp;=&nbsp;&#960;&#183;<i>D</i><sup>2</sup>/4. В качестве значения&nbsp;&#960; использовать&nbsp;3.14.`
	b.ru[16] = `Найти расстояние между двумя точками с заданными координатами&nbsp;<i>x</i><sub>1</sub> и&nbsp;<i>x</i><sub>2</sub> на числовой оси: |<i>x</i><sub>2</sub>&nbsp;&#8722;&nbsp;<i>x</i><sub>1</sub>|.`
	b.ru[17] = `Даны три точки&nbsp;<i>A</i>, <i>B</i>,&nbsp;<i>C</i> на числовой оси. Найти длины отрезков&nbsp;<i>AC</i> и&nbsp;<i>BC</i> и их сумму.`
	b.ru[18] = `Даны три точки&nbsp;<i>A</i>, <i>B</i>,&nbsp;<i>C</i> на числовой оси. Точка&nbsp;<i>C</i> расположена между точками&nbsp;<i>A</i> и&nbsp;<i>B</i>. Найти произведение длин отрезков&nbsp;<i>AC</i> и&nbsp;<i>BC</i>.`
	b.ru[19] = `Даны координаты двух противоположных вершин прямоугольника: (<i>x</i><sub>1</sub>,&nbsp;<i>y</i><sub>1</sub>), (<i>x</i><sub>2</sub>,&nbsp;<i>y</i><sub>2</sub>). Стороны прямоугольника параллельны осям координат. Найти периметр и площадь данного прямоугольника.`
	b.ru[20] = `Найти расстояние между двумя точками с заданными координатами (<i>x</i><sub>1</sub>,&nbsp;<i>y</i><sub>1</sub>) и&nbsp;(<i>x</i><sub>2</sub>,&nbsp;<i>y</i><sub>2</sub>) на плоскости. Расстояние вычисляется по формуле ((<i>x</i><sub>2</sub>&nbsp;&#8722;&nbsp;<i>x</i><sub>1</sub>)<sup>2</sup>&nbsp;+&nbsp;(<i>y</i><sub>2</sub>&nbsp;&#8722;&nbsp;<i>y</i><sub>1</sub>)<sup>2</sup>)<sup>1/2</sup>`
	b.ru[21] = `Даны координаты трех вершин треугольника: (<i>x</i><sub>1</sub>,&nbsp;<i>y</i><sub>1</sub>), (<i>x</i><sub>2</sub>,&nbsp;<i>y</i><sub>2</sub>), (<i>x</i><sub>3</sub>,&nbsp;<i>y</i><sub>3</sub>). Найти его периметр и площадь, используя формулу для расстояния между двумя точками на плоскости (см. задание Begin20). Для нахождения площади треугольника со сторонами&nbsp;<i>a</i>, <i>b</i>, <i>c</i> использовать <i>формулу Герона</i>: <i>S</i>&nbsp;=&nbsp;(<i>p</i>&#183;(<i>p</i>&nbsp;&#8722;&nbsp;<i>a</i>)&#183;(<i>p</i>&nbsp;&#8722;&nbsp;<i>b</i>)&#183;(<i>p</i>&nbsp;&#8722;&nbsp;<i>c</i>))<sup>1/2</sup>,где <i>p</i>&nbsp;=&nbsp;(<i>a</i>&nbsp;+&nbsp;<i>b</i>&nbsp;+&nbsp;<i>c</i>)/2 &#8212; <i>полупериметр</i>.`
	b.ru[22] = `Поменять местами содержимое переменных&nbsp;<i>A</i> и&nbsp;<i>B</i> и вывести новые значения&nbsp;<i>A</i> и&nbsp;<i>B</i>.`
	b.ru[23] = `Даны переменные&nbsp;<i>A</i>, <i>B</i>,&nbsp;<i>C</i>. Изменить их значения, переместив содержимое&nbsp;<i>A</i> в&nbsp;<i>B</i>, <i>B</i> &#8212; в&nbsp;<i>C</i>, <i>C</i> &#8212; в&nbsp;<i>A</i>, и вывести новые значения переменных&nbsp;<i>A</i>, <i>B</i>,&nbsp;<i>C</i>.`
	b.ru[24] = `Даны переменные&nbsp;<i>A</i>, <i>B</i>,&nbsp;<i>C</i>. Изменить их значения, переместив содержимое&nbsp;<i>A</i> в&nbsp;<i>C</i>, <i>C</i> &#8212; в&nbsp;<i>B</i>, <i>B</i> &#8212; в&nbsp;<i>A</i>, и вывести новые значения переменных&nbsp;<i>A</i>, <i>B</i>,&nbsp;<i>C</i>.`
	b.ru[25] = `Найти значение функции <i>y</i>&nbsp;=&nbsp;3<i>x</i><sup>6</sup>&nbsp;&#8722;&nbsp;6<i>x</i><sup>2</sup>&nbsp;&#8722;&nbsp;7 при данном значении&nbsp;<i>x</i>.`
	b.ru[26] = `Найти значение функции <i>y</i>&nbsp;=&nbsp;4(<i>x</i>&#8722;3)<sup>6</sup>&nbsp;&#8722;&nbsp;7(<i>x</i>&#8722;3)<sup>3</sup>&nbsp;+&nbsp;2 при данном значении&nbsp;<i>x</i>.`
	b.ru[27] = `Дано число&nbsp;<i>A</i>. Вычислить&nbsp;<i>A</i><sup>8</sup>, используя вспомогательную переменную и три операции умножения. Для этого последовательно находить <i>A</i><sup>2</sup>, <i>A</i><sup>4</sup>, <i>A</i><sup>8</sup>. Вывести все найденные степени числа&nbsp;<i>A</i>.`
	b.ru[28] = `Дано число&nbsp;<i>A</i>. Вычислить <i>A</i><sup>15</sup>, используя две вспомогательные переменные и пять операций умножения. Для этого последовательно находить <i>A</i><sup>2</sup>, <i>A</i><sup>3</sup>, <i>A</i><sup>5</sup>, <i>A</i><sup>10</sup>, <i>A</i><sup>15</sup>. Вывести все найденные степени числа&nbsp;<i>A</i>.`
	b.ru[29] = `Дано значение угла&nbsp;&#945; в градусах (0&nbsp;&#8804;&nbsp;&#945;&nbsp;&lt;&nbsp;360). Определить значение этого же угла в радианах, учитывая, что 180&#176; = &#960; радианов. В качестве значения&nbsp;&#960; использовать&nbsp;3.14.`
	b.ru[30] = `Дано значение угла&nbsp;&#945; в радианах (0&nbsp;&#8804;&nbsp;&#945;&nbsp;&lt;&nbsp;2&#183;&#960;). Определить значение этого же угла в градусах, учитывая, что 180&#176; = &#960; радианов. В качестве значения&nbsp;&#960; использовать&nbsp;3.14.`
	b.ru[31] = `Дано значение температуры&nbsp;<i>T</i> в градусах Фаренгейта. Определить значение этой же температуры в градусах Цельсия. Температура по Цельсию&nbsp;<i>T</i><sub><i>C</i></sub> и температура по Фаренгейту&nbsp;<i>T</i><sub><i>F</i></sub> связаны следующим соотношением:<i>T</i><sub><i>C</i></sub> = (<i>T</i><sub><i>F</i></sub> &#8722; 32)&#183;5/9`
	b.ru[32] = `Дано значение температуры <i>T</i> в градусах Цельсия. Определить значение этой же температуры в градусах Фаренгейта. Температура по Цельсию&nbsp;<i>T</i><sub><i>C</i></sub> и температура по Фаренгейту&nbsp;<i>T</i><sub><i>F</i></sub> связаны следующим соотношением:<i>T</i><sub><i>C</i></sub> = (<i>T</i><sub><i>F</i></sub> &#8722; 32)&#183;5/9`
	b.ru[33] = `Известно, что <i>X</i>&nbsp;кг конфет стоит <i>A</i>&nbsp;рублей. Определить, сколько стоит 1&nbsp;кг и <i>Y</i>&nbsp;кг этих же конфет.`
	b.ru[34] = `Известно, что <i>X</i>&nbsp;кг шоколадных конфет стоит <i>A</i>&nbsp;рублей, а <i>Y</i>&nbsp;кг ирисок стоит <i>B</i>&nbsp;рублей.  Определить, сколько стоит 1&nbsp;кг шоколадных конфет, 1&nbsp;кг ирисок, а также во сколько раз шоколадные конфеты дороже ирисок.`
	b.ru[35] = `Скорость лодки в стоячей воде <i>V</i>&nbsp;км/ч, скорость течения реки <i>U</i>&nbsp;км/ч (<i>U</i>&nbsp;&lt;&nbsp;<i>V</i>). Время движения лодки по озеру <i>T</i><sub>1</sub>&nbsp;ч, а по реке (против течения) &#8212; <i>T</i><sub>2</sub>&nbsp;ч. Определить путь <i>S</i>, пройденный лодкой (путь = время &#183; скорость). Учесть, что при движении против течения скорость лодки уменьшается на величину скорости течения.`
	b.ru[36] = `Скорость первого автомобиля <i>V</i><sub>1</sub>&nbsp;км/ч, второго &#8212; <i>V</i><sub>2</sub>&nbsp;км/ч, расстояние между ними <i>S</i>&nbsp;км. Определить расстояние между ними через <i>T</i>&nbsp;часов, если автомобили удаляются друг от друга, двигаясь в противоположных направлениях. Данное расстояние равно сумме начального расстояния и общего пути, проделанного автомобилями; общий путь = время &#183; суммарная скорость.`
	b.ru[37] = `Скорость первого автомобиля <i>V</i><sub>1</sub>&nbsp;км/ч, второго &#8212; <i>V</i><sub>2</sub>&nbsp;км/ч, расстояние между ними <i>S</i>&nbsp;км. Определить расстояние между ними через <i>T</i>&nbsp;часов, если автомобили первоначально движутся навстречу друг другу. Данное расстояние равно модулю разности начального расстояния и общего пути, проделанного автомобилями; общий путь = время &#183; суммарная скорость.`
	b.ru[38] = `Решить линейное уравнение <i>A</i>&#183;<i>x</i>&nbsp;+&nbsp;<i>B</i>&nbsp;=&nbsp;0, заданное своими коэффициентами&nbsp;<i>A</i> и&nbsp;<i>B</i> (коэффициент&nbsp;<i>A</i> не&nbsp;равен&nbsp;0).`
	b.ru[39] = `Найти корни <i>квадратного уравнения</i> <i>A</i>&#183;<i>x</i><sup>2</sup>&nbsp;+&nbsp;<i>B</i>&#183;<i>x</i>&nbsp;+&nbsp;<i>C</i>&nbsp;=&nbsp;0, заданного своими коэффициентами <i>A</i>, <i>B</i>, <i>C</i> (<i>A</i>&nbsp;&gt;&nbsp;0), если известно, что дискриминант уравнения положителен. Вывести вначале меньший, а затем больший из найденных корней. Корни квадратного уравнения находятся по формуле <i>x</i><sub>1,&nbsp;2</sub> = (&#8722;<i>B</i>&nbsp;&#177;&nbsp;(<i>D</i>)<sup>1/2</sup>)/(2&#183;<i>A</i>),где <i>D</i> &#8212; <i>дискриминант</i>, равный <i>B</i><sup>2</sup>&nbsp;&#8722;&nbsp;4&#183;<i>A</i>&#183;<i>C</i>.`
	b.ru[40] = `Найти решение <i>системы линейных уравнений</i> вида <i>A</i><sub>1</sub>&#183;<i>x</i>&nbsp;+&nbsp;<i>B</i><sub>1</sub>&#183;<i>y</i> = <i>C</i><sub>1</sub>,<br><i>A</i><sub>2</sub>&#183;<i>x</i>&nbsp;+&nbsp;<i>B</i><sub>2</sub>&#183;<i>y</i> = <i>C</i><sub>2</sub>,заданной своими коэффициентами <i>A</i><sub>1</sub>, <i>B</i><sub>1</sub>, <i>C</i><sub>1</sub>, <i>A</i><sub>2</sub>, <i>B</i><sub>2</sub>, <i>C</i><sub>2</sub>, если известно, что данная система имеет единственное решение. Воспользоваться формулами <i>x</i> = (<i>C</i><sub>1</sub>&#183;<i>B</i><sub>2</sub>&nbsp;&#8722;&nbsp;<i>C</i><sub>2</sub>&#183;<i>B</i><sub>1</sub>)/<i>D</i>, &nbsp; &nbsp; &nbsp; &nbsp;<i>y</i> = (<i>A</i><sub>1</sub>&#183;<i>C</i><sub>2</sub>&nbsp;&#8722;&nbsp;<i>A</i><sub>2</sub>&#183;<i>C</i><sub>1</sub>)/<i>D</i>,<br>где <i>D</i> = <i>A</i><sub>1</sub>&#183;<i>B</i><sub>2</sub>&nbsp;&#8722;&nbsp;<i>A</i><sub>2</sub>&#183;<i>B</i><sub>1</sub>`
}
