package task

type ffor struct {
	count int
	name  string
	en    []string
	tj    []string
	ru    []string
}

func NewForTask() Task {
	f := &ffor{
		count: 41,
		name:  "For",
	}
	f.makeEn()
	f.makeTj()
	f.makeRu()
	return f
}

func (f *ffor) Count() int   { return f.count }
func (f *ffor) Name() string { return f.name }
func (f *ffor) En() []string { return f.en }
func (f *ffor) Tj() []string { return f.tj }
func (f *ffor) Ru() []string { return f.ru }

func (f *ffor) makeEn() {
	f.en = make([]string, f.count)
	f.en[1] = `Given integers&nbsp;<i>K</i> and&nbsp;<i>N</i> (<i>N</i>&nbsp;&gt;&nbsp;0), output the number&nbsp;<i>K</i> <i>N</i>&nbsp;times.`
	f.en[2] = `Given two integers&nbsp;<i>A</i> and&nbsp;<i>B</i> (<i>A</i>&nbsp;&lt;&nbsp;<i>B</i>), output in ascending order all integers in the range&nbsp;<i>A</i> to&nbsp;<i>B</i> (including&nbsp;<i>A</i> and&nbsp;<i>B</i>). Also output the amount&nbsp;<i>N</i> of these integers.`
	f.en[3] = `Given two integers&nbsp;<i>A</i> and&nbsp;<i>B</i> (<i>A</i>&nbsp;&lt;&nbsp;<i>B</i>), output in descending order all integers in the range&nbsp;<i>A</i> to&nbsp;<i>B</i> (excluding&nbsp;<i>A</i> and&nbsp;<i>B</i>). Also output the amount&nbsp;<i>N</i> of these integers.`
	f.en[4] = `Given the price of 1&nbsp;kg of sweets (as a real number), output the cost of 1, 2,&nbsp;&#8230;, 10&nbsp;kg of these sweets.`
	f.en[5] = `Given the price of 1&nbsp;kg of sweets (as a real number), output the cost of 0.1, 0.2,&nbsp;&#8230;, 1&nbsp;kg of these sweets.`
	f.en[6] = `Given the price of 1&nbsp;kg of sweets (as a real number), output the cost of 1.2, 1.4,&nbsp;&#8230;, 2&nbsp;kg of these sweets.`
	f.en[7] = `Given two integers&nbsp;<i>A</i> and&nbsp;<i>B</i> (<i>A</i>&nbsp;&lt;&nbsp;<i>B</i>), find the sum of all integers in the range&nbsp;<i>A</i> to&nbsp;<i>B</i> inclusive.`
	f.en[8] = `Given two integers&nbsp;<i>A</i> and&nbsp;<i>B</i> (<i>A</i>&nbsp;&lt;&nbsp;<i>B</i>), find the product of all integers in the range&nbsp;<i>A</i> to&nbsp;<i>B</i> inclusive.`
	f.en[9] = `Given two integers&nbsp;<i>A</i> and&nbsp;<i>B</i> (<i>A</i>&nbsp;&lt;&nbsp;<i>B</i>), find the sum of squares of all integers in the range&nbsp;<i>A</i> to&nbsp;<i>B</i> inclusive.`
	f.en[10] = `Given an integer&nbsp;<i>N</i> (&gt;&nbsp;0), find the value of a following sum (as a real number): 1&nbsp;+&nbsp;1/2&nbsp;+&nbsp;1/3&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;1/<i>N</i>`
	f.en[11] = `Given an integer&nbsp;<i>N</i> (&gt;&nbsp;0), find the value of a following sum (as an integer): <i>N</i><sup>2</sup>&nbsp;+&nbsp;(<i>N</i>&nbsp;+&nbsp;1)<sup>2</sup>&nbsp;+&nbsp;(<i>N</i>&nbsp;+&nbsp;2)<sup>2</sup>&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;(2&#183;<i>N</i>)<sup>2</sup>`
	f.en[12] = `Given an integer&nbsp;<i>N</i> (&gt;&nbsp;0), find the value of a following product of <i>N</i>&nbsp;factors: 1.1&nbsp;&#183;&nbsp;1.2&nbsp;&#183;&nbsp;1.3&nbsp;&#183;&nbsp;&#8230;&nbsp;`
	f.en[13] = `Given an integer&nbsp;<i>N</i> (&gt;&nbsp;0), find the value of the following expression of <i>N</i>&nbsp;terms with alternating signs: 1.1&nbsp;&#8722;&nbsp;1.2&nbsp;+&nbsp;1.3&nbsp;&#8722;&nbsp;&#8230;&nbsp;Do not use conditional statements.`
	f.en[14] = `Given an integer&nbsp;<i>N</i> (&gt;&nbsp;0), compute&nbsp;<i>N</i><sup>2</sup> by means of the formula <i>N</i><sup>2</sup>&nbsp;=&nbsp;1&nbsp;+&nbsp;3&nbsp;+&nbsp;5&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;(2&#183;<i>N</i>&nbsp;&#8722;&nbsp;1)Output the value of the sum after addition of each term. As a result, squares of all integers in the range&nbsp;1 to&nbsp;<i>N</i> will be output.`
	f.en[15] = `Given a real number&nbsp;<i>A</i> and an integer&nbsp;<i>N</i> (&gt;&nbsp;0), find&nbsp;<i>A</i> raised to the power&nbsp;<i>N</i> (i.&nbsp;e., the product of&nbsp;<i>N</i> values of&nbsp;<i>A</i>): <i>A</i><sup><i>N</i></sup> = <i>A</i>&#183;<i>A</i>&#183;&nbsp;&#8230;&nbsp;&#183;<i>A</i>`
	f.en[16] = `A real number&nbsp;<i>A</i> and an integer&nbsp;<i>N</i> (&gt;&nbsp;0) are given. Using one loop-statement compute and output powers&nbsp;<i>A</i><sup><i>K</i></sup> for all integer exponents&nbsp;<i>K</i> in the range&nbsp;1 to&nbsp;<i>N</i>.`
	f.en[17] = `A real number&nbsp;<i>A</i> and an integer&nbsp;<i>N</i> (&gt;&nbsp;0) are given. Using one loop-statement compute the sum   1&nbsp;+&nbsp;<i>A</i>&nbsp;+&nbsp;<i>A</i><sup>2</sup>&nbsp;+&nbsp;<i>A</i><sup>3</sup>&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;<i>A</i><sup><i>N</i></sup>`
	f.en[18] = `A real number&nbsp;<i>A</i> and an integer&nbsp;<i>N</i> (&gt;&nbsp;0) are given. Using one loop-statement compute the expression 1&nbsp;&#8722;&nbsp;<i>A</i>&nbsp;+&nbsp;<i>A</i><sup>2</sup>&nbsp;&#8722;&nbsp;<i>A</i><sup>3</sup>&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;(&#8722;1)<sup><i>N</i></sup>&#183;<i>A</i><sup><i>N</i></sup>Do not use conditional statements.`
	f.en[19] = `Given an integer&nbsp;<i>N</i> (&gt;&nbsp;0), find the value of a following product:<i>N</i>!&nbsp;=&nbsp;1&#183;2&#183;&#8230;&#183;<i>N</i>(<i><i>N</i>&#8211;factorial</i>). To avoid the integer overflow, compute the product using a real variable and output the result as a real number.`
	f.en[20] = `An integer&nbsp;<i>N</i> (&gt;&nbsp;0) is given. Using one loop-statement compute the sum 1!&nbsp;+&nbsp;2!&nbsp;+&nbsp;3!&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;<i>N</i>!, where <i>N</i>! (<i><i>N</i>&#8211;factorial</i>) is the product  of all integers in the range&nbsp;1 to&nbsp;<i>N</i>: &nbsp; &nbsp;<i>N</i>!&nbsp;=&nbsp;1&#183;2&#183;&#8230;&#183;<i>N</i>. To avoid the integer overflow, compute the sum using real variables and output the result as a real number.`
	f.en[21] = `An integer&nbsp;<i>N</i> (&gt;&nbsp;0) is given. Using one loop-statement compute the sum 1&nbsp;+&nbsp;1/(1!)&nbsp;+&nbsp;1/(2!)&nbsp;+&nbsp;1/(3!)&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;1/(<i>N</i>!),where <i>N</i>! (<i><i>N</i>&#8211;factorial</i>) is the product of all integers in the range&nbsp;1 to&nbsp;<i>N</i>: &nbsp; &nbsp;<i>N</i>!&nbsp;=&nbsp;1&#183;2&#183;&#8230;&#183;<i>N</i>. The result is an approximate value of the constant <i>e</i>&nbsp;=&nbsp;exp(1).`
	f.en[22] = `A real number&nbsp;<i>X</i> and an integer&nbsp;<i>N</i> (&gt;&nbsp;0) are given. Compute the expression 1&nbsp;+&nbsp;<i>X</i>&nbsp;+&nbsp;<i>X</i><sup>2</sup>/(2!)&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;<i>X</i><sup><i>N</i></sup>/(<i>N</i>!)(<i>N</i>!&nbsp;=&nbsp;1&#183;2&#183;&#8230;&#183;<i>N</i>). The result is an approximate value of exp(<i>X</i>).`
	f.en[23] = `A real number&nbsp;<i>X</i> and an integer&nbsp;<i>N</i> (&gt;&nbsp;0) are given. Compute the expression <i>X</i>&nbsp;&#8722;&nbsp;<i>X</i><sup>3</sup>/(3!)&nbsp;+&nbsp;<i>X</i><sup>5</sup>/(5!)&nbsp;&#8722;&nbsp;&#8230;&nbsp;+&nbsp;(&#8722;1)<sup><i>N</i></sup>&#183;<i>X</i><sup>2&#183;<i>N</i>+1</sup>/((2&#183;<i>N</i>+1)!)(<i>N</i>!&nbsp;=&nbsp;1&#183;2&#183;&#8230;&#183;<i>N</i>). The result is an approximate value of sin(<i>X</i>).`
	f.en[24] = `A real number&nbsp;<i>X</i> and an integer&nbsp;<i>N</i> (&gt;&nbsp;0) are given. Compute the expression 1&nbsp;&#8722;&nbsp;<i>X</i><sup>2</sup>/(2!)&nbsp;+&nbsp;<i>X</i><sup>4</sup>/(4!)&nbsp;&#8722;&nbsp;&#8230;&nbsp;+&nbsp;(&#8722;1)<sup><i>N</i></sup>&#183;<i>X</i><sup>2&#183;<i>N</i></sup>/((2&#183;<i>N</i>)!)(<i>N</i>!&nbsp;=&nbsp;1&#183;2&#183;&#8230;&#183;<i>N</i>). The result is an approximate value of cos(<i>X</i>).`
	f.en[25] = `A real number&nbsp;<i>X</i> (|<i>X</i>|&nbsp;&lt;&nbsp;1) and an integer&nbsp;<i>N</i> (&gt;&nbsp;0) are given. Compute the expression <i>X</i>&nbsp;&#8722;&nbsp;<i>X</i><sup>2</sup>/2&nbsp;+&nbsp;<i>X</i><sup>3</sup>/3&nbsp;&#8722;&nbsp;&#8230;&nbsp;+&nbsp;(&#8722;1)<sup><i>N</i>&#8722;1</sup>&#183;<i>X</i><sup><i>N</i></sup>/<i>N</i>The result is an approximate value of ln(1&nbsp;+&nbsp;<i>X</i>).`
	f.en[26] = `A real number&nbsp;<i>X</i> (|<i>X</i>|&nbsp;&lt;&nbsp;1) and an integer&nbsp;<i>N</i> (&gt;&nbsp;0) are given. Compute the expression <i>X</i>&nbsp;&#8722;&nbsp;<i>X</i><sup>3</sup>/3&nbsp;+&nbsp;<i>X</i><sup>5</sup>/5&nbsp;&#8722;&nbsp;&#8230;&nbsp;+&nbsp;(&#8722;1)<sup><i>N</i></sup>&#183;<i>X</i><sup>2&#183;<i>N</i>+1</sup>/(2&#183;<i>N</i>+1)The result is an approximate value of atan(<i>X</i>).`
	f.en[27] = `A real number&nbsp;<i>X</i> (|<i>X</i>|&nbsp;&lt;&nbsp;1) and an integer&nbsp;<i>N</i> (&gt;&nbsp;0) are given. Compute the expression <i>X</i>&nbsp;+&nbsp;1&#183;<i>X</i><sup>3</sup>/(2&#183;3)&nbsp;+&nbsp;1&#183;3&#183;<i>X</i><sup>5</sup>/(2&#183;4&#183;5)&nbsp;+&nbsp;&#8230;&nbsp;+<br>+&nbsp;1&#183;3&#183;&#8230;&#183;(2&#183;<i>N</i>&#8722;1)&#183;<i>X</i><sup>2&#183;<i>N</i>+1</sup>/(2&#183;4&#183;&#8230;&#183;(2&#183;<i>N</i>)&#183;(2&#183;<i>N</i>+1))The result is an approximate value of asin(<i>X</i>).`
	f.en[28] = `A real number&nbsp;<i>X</i> (|<i>X</i>|&nbsp;&lt;&nbsp;1) and an integer&nbsp;<i>N</i> (&gt;&nbsp;0) are given. Compute the expression 1&nbsp;+&nbsp;<i>X</i>/2&nbsp;&#8722;&nbsp;1&#183;<i>X</i><sup>2</sup>/(2&#183;4)&nbsp;+&nbsp;1&#183;3&#183;<i>X</i><sup>3</sup>/(2&#183;4&#183;6)&nbsp;&#8722;&nbsp;&#8230;&nbsp;+<br>+&nbsp;(&#8722;1)<sup><i>N</i>&#8722;1</sup>&#183;1&#183;3&#183;&#8230;&#183;(2&#183;<i>N</i>&#8722;3)&#183;<i>X</i><sup><i>N</i></sup>/(2&#183;4&#183;&#8230;&#183;(2&#183;<i>N</i>))The result is an approximate value of the square root of&nbsp;1&nbsp;+&nbsp;<i>X</i>.`
	f.en[29] = `An integer&nbsp;<i>N</i> (&gt;&nbsp;1) and two points <i>A</i>,&nbsp;<i>B</i> (<i>A</i>&nbsp;&lt;&nbsp;<i>B</i>) on the real axis are given. The segment [<i>A</i>,&nbsp;<i>B</i>] is divided into&nbsp;<i>N</i> sub-segments of equal length. Output the length&nbsp;<i>H</i> of each sub-segment and then output the sequence of points <i>A</i>, &nbsp; &nbsp;<i>A</i>&nbsp;+&nbsp;<i>H</i>, &nbsp; &nbsp;<i>A</i>&nbsp;+&nbsp;2&#183;<i>H</i>, &nbsp; &nbsp;<i>A</i>&nbsp;+&nbsp;3&#183;<i>H</i>, &nbsp; &nbsp;&#8230;, &nbsp; &nbsp;<i>B</i>,which forms a partition of the segment [<i>A</i>,&nbsp;<i>B</i>].`
	f.en[30] = `An integer&nbsp;<i>N</i> (&gt;&nbsp;1) and two points <i>A</i>,&nbsp;<i>B</i> (<i>A</i>&nbsp;&lt;&nbsp;<i>B</i>) on the real axis are given. The segment [<i>A</i>,&nbsp;<i>B</i>] is divided into&nbsp;<i>N</i> sub-segments of equal length. Output the length&nbsp;<i>H</i> of each sub-segment and then output the values of a function <i>F</i>(<i>X</i>)&nbsp;=&nbsp;1&nbsp;&#8722;&nbsp;sin(<i>X</i>) at points dividing the segment [<i>A</i>,&nbsp;<i>B</i>]: <i>F</i>(<i>A</i>), &nbsp; &nbsp;<i>F</i>(<i>A</i>&nbsp;+&nbsp;<i>H</i>), &nbsp; &nbsp;<i>F</i>(<i>A</i>&nbsp;+&nbsp;2&#183;<i>H</i>), &nbsp; &nbsp;&#8230;, &nbsp; &nbsp;<i>F</i>(<i>B</i>)`
	f.en[31] = `An integer&nbsp;<i>N</i> (&gt;&nbsp;0) is given. A sequence of real numbers&nbsp;<i>A</i><sub><i>K</i></sub> is defined as: <i>A</i><sub>0</sub>&nbsp;=&nbsp;2, &nbsp; &nbsp; &nbsp; &nbsp;<i>A</i><sub><i>K</i></sub>&nbsp;=&nbsp;2&nbsp;+&nbsp;1/<i>A</i><sub><i>K</i>&#8722;1</sub>, &nbsp; &nbsp;<i>K</i>&nbsp;=&nbsp;1,&nbsp;2,&nbsp;&#8230;&nbsp;Output terms <i>A</i><sub>1</sub>, <i>A</i><sub>2</sub>,&nbsp;&#8230;,&nbsp;<i>A</i><sub><i>N</i></sub> of the sequence.`
	f.en[32] = `An integer&nbsp;<i>N</i> (&gt;&nbsp;0) is given. A sequence of real numbers&nbsp;<i>A</i><sub><i>K</i></sub> is defined as: <i>A</i><sub>0</sub>&nbsp;=&nbsp;1, &nbsp; &nbsp; &nbsp; &nbsp;<i>A</i><sub><i>K</i></sub>&nbsp;=&nbsp;(<i>A</i><sub><i>K</i>&#8722;1</sub>&nbsp;+&nbsp;1)/<i>K</i>, &nbsp; &nbsp;<i>K</i>&nbsp;=&nbsp;1,&nbsp;2,&nbsp;&#8230;&nbsp;Output terms <i>A</i><sub>1</sub>, <i>A</i><sub>2</sub>,&nbsp;&#8230;,&nbsp;<i>A</i><sub><i>N</i></sub> of the sequence.`
	f.en[33] = `An integer&nbsp;<i>N</i> (&gt;&nbsp;0) is given. An integer-valued sequence of the <i>Fibonacci numbers</i>&nbsp;<i>F</i><sub><i>K</i></sub> is defined as: <i>F</i><sub>1</sub>&nbsp;=&nbsp;1, &nbsp; &nbsp; &nbsp; &nbsp;<i>F</i><sub>2</sub>&nbsp;=&nbsp;1, &nbsp; &nbsp; &nbsp; &nbsp;<i>F</i><sub><i>K</i></sub>&nbsp;=&nbsp;<i>F</i><sub><i>K</i>&#8722;2</sub>&nbsp;+&nbsp;<i>F</i><sub><i>K</i>&#8722;1</sub>, &nbsp; &nbsp;<i>K</i>&nbsp;=&nbsp;3,&nbsp;4,&nbsp;&#8230;&nbsp;Output terms <i>F</i><sub>1</sub>, <i>F</i><sub>2</sub>,&nbsp;&#8230;,&nbsp;<i>F</i><sub><i>N</i></sub> of the sequence.`
	f.en[34] = `An integer&nbsp;<i>N</i> (&gt;&nbsp;1) is given. A sequence of real numbers&nbsp;<i>A</i><sub><i>K</i></sub> is defined as: <i>A</i><sub>1</sub>&nbsp;=&nbsp;1, &nbsp; &nbsp; &nbsp; &nbsp;<i>A</i><sub>2</sub>&nbsp;=&nbsp;2, &nbsp; &nbsp; &nbsp; &nbsp;<i>A</i><sub><i>K</i></sub>&nbsp;=&nbsp;(<i>A</i><sub><i>K</i>&#8722;2</sub>&nbsp;+&nbsp;2&#183;<i>A</i><sub><i>K</i>&#8722;1</sub>)/3, &nbsp; &nbsp;<i>K</i>&nbsp;=&nbsp;3,&nbsp;4,&nbsp;&#8230;&nbsp;Output terms <i>A</i><sub>1</sub>, <i>A</i><sub>2</sub>,&nbsp;&#8230;,&nbsp;<i>A</i><sub><i>N</i></sub> of the sequence.`
	f.en[35] = `An integer&nbsp;<i>N</i> (&gt;&nbsp;2) is given. A sequence of integers&nbsp;<i>A</i><sub><i>K</i></sub> is defined as: <i>A</i><sub>1</sub>&nbsp;=&nbsp;1, &nbsp; &nbsp; &nbsp; &nbsp;<i>A</i><sub>2</sub>&nbsp;=&nbsp;2, &nbsp; &nbsp; &nbsp; &nbsp;<i>A</i><sub>3</sub>&nbsp;=&nbsp;3,  &nbsp; &nbsp; &nbsp; &nbsp;<i>A</i><sub><i>K</i></sub>&nbsp;=&nbsp;<i>A</i><sub><i>K</i>&#8722;1</sub>&nbsp;+&nbsp;<i>A</i><sub><i>K</i>&#8722;2</sub>&nbsp;&#8722;&nbsp;2&#183;<i>A</i><sub><i>K</i>&#8722;3</sub>, &nbsp; &nbsp;<i>K</i>&nbsp;=&nbsp;4,&nbsp;5,&nbsp;&#8230;&nbsp;Output terms <i>A</i><sub>1</sub>, <i>A</i><sub>2</sub>,&nbsp;&#8230;,&nbsp;<i>A</i><sub><i>N</i></sub> of the sequence.`
	f.en[36] = `Given positive integers&nbsp;<i>N</i> and&nbsp;<i>K</i>, find the sum1<sup><i>K</i></sup>&nbsp;+&nbsp;2<sup><i>K</i></sup>&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;<i>N</i><sup><i>K</i></sup>To avoid the integer overflow, compute the sum using real variables and output the result as a real number.`
	f.en[37] = `Given an integer&nbsp;<i>N</i> (&gt;&nbsp;0), find the sum1<sup>1</sup>&nbsp;+&nbsp;2<sup>2</sup>&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;<i>N</i><sup><i>N</i></sup>To avoid the integer overflow, compute the sum using real variables and output the result as a real number.`
	f.en[38] = `Given an integer&nbsp;<i>N</i> (&gt;&nbsp;0), find the sum1<sup><i>N</i></sup>&nbsp;+&nbsp;2<sup><i>N</i>&#8722;1</sup>&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;<i>N</i><sup>1</sup>To avoid the integer overflow, compute the sum using real variables and output the result as a real number.`
	f.en[39] = `Positive integers&nbsp;<i>A</i> and&nbsp;<i>B</i> (<i>A</i>&nbsp;&lt;&nbsp;<i>B</i>) are given. Output all integers in the range&nbsp;<i>A</i> to&nbsp;<i>B</i>, with an integer of a value&nbsp;<i>K</i> being output <i>K</i>&nbsp;times (for example, the number&nbsp;3 must be output 3&nbsp;times).`
	f.en[40] = `Integers&nbsp;<i>A</i> and&nbsp;<i>B</i> (<i>A</i>&nbsp;&lt;&nbsp;<i>B</i>) are given. Output all integers in the range&nbsp;<i>A</i> to&nbsp;<i>B</i>, with the number&nbsp;<i>A</i> being output once, the number&nbsp;<i>A</i>&nbsp;+&nbsp;1 being output twice, and so on.`
}

func (f *ffor) makeTj() {
	f.tj = make([]string, f.count)
	f.tj[1] = `Ду ададҳои бутуни K ва N (N>0) дода шудаанд. Адади K-ро N маротиба хориҷ кунед.`
	f.tj[2] = `Ду ададҳои бутуни A ва B (A&lt;B) дода шудаанд. Ҳамаи ададҳои бутуни дар байни ададҳои A ва B ҷойгирбударо бо тартиби афзуншавӣ (дар якҷоягӣ бо худи ададҳои A ва B), ҳамчунин миқдори ин ададҳоро N хориҷ кунед.`
	f.tj[3] = `Ду ададҳои бутуни A ва B (A&lt;B) дода шудаанд. Ҳамаи ададҳои бутуни дар байни ададҳои A ва B ҷойгирбударо бо тартиби камшавӣ (ба истиснои ададҳои A ва B), ҳамчунин миқдори ин ададҳоро N хориҷ кунед.`
	f.tj[4] = `Адади ҳақиқӣ — нархи 1 кг қанд дода шудааст. Нархи 1,2,…,10 кг қандро хориҷ кунед.`
	f.tj[5] = `Адади ҳақиқӣ — нархи 1 кг қанд дода шудааст. Нархи 0.1, 0.2, …, 1 кг қандро хориҷ кунед.`
	f.tj[6] = `Адади ҳақиқӣ - нархи 1 кг қанд дода шудааст. Нархи 1.2, 1.4, .. , 2 кг қандро хориҷ кунед.`
	f.tj[7] = `Ду ададҳои бутуни A ва B (A&lt;B) дода шудаанд. Суммаи ҳамаи ададҳои бутунро аз A то B дар якҷоягӣ ёбед.`
	f.tj[8] = `Ду ададҳои бутуни A ва B (A&lt;B) дода шудаанд. Ҳосилизарби ҳамаи ададҳои бутунро аз A то B дар якҷоягӣ ёбед.`
	f.tj[9] = `Ду ададҳои бутуни A ва B (A&lt;B) дода шудаанд. Суммаи квадратҳои ҳамаи ададҳои бутунро аз A то B дар якҷоягӣ ёбед.`
	f.tj[10] = `Адади бутуни N(>0) дода шудааст. Суммаи 1+1/2+1/3+…+1/N (адади ҳақиқӣ)-ро ёбед.`
	f.tj[11] = `Адади бутуни N(>0) дода шудааст. Суммаи N<sup>2</sup>+(N+1)<sup>2</sup>+(N+2)<sup>2</sup>+…+(2·N)<sup>2</sup>(адади бутун)-ро ёбед.`
	f.tj[12] = `Адади бутуни N(>0) дода шудааст. ҲосилиЗарби 1.1 · 1.2 · 1.3 · ... (N зарбкунанда)-ро ёбед.`
	f.tj[13] = `Адади бутуни N (>0) дода шудааст. Қимати ифодаи 1.1 - 1.2 + 1.3 - ... (N ҷамъшавандаҳо, аломатҳои иваз шуда меистанд)-ро ёбед. Оператори шартиро истифода набаред.`
	f.tj[14] = `Адади бутуни N (>0) дода шудааст. Квадрати адади мазкурро ёбед, барои ҳисобкунии он формулаи зеринро истифода баред: N<sup>2</sup>=1+3+5+...+(2·N-1). Пас аз ҳамроҳкунии ҳар як ҷамъшаванда ба сумма қимати ҷории суммаро хориҷ кунед (дар натиҷа квадратҳои ҳамаи ададҳои бутун аз 1 то N хориҷ карда мешаванд).`
	f.tj[15] = `Адади ҳақиқии A ва адади бутуни N(>0) дода шудаанд. A дар дараҷаи N-ро ёбед: A<sup>N</sup>=A*A* ...*A (ададҳои A - N маротиба бо ҳам зарб мешаванд).`
	f.tj[16] = `Адади ҳақиқии A ва адади бутуни N(>0) дода шудаанд. Бо истифодабарии як давр ҳамаи дараҷаҳои бутуни адади A-ро аз 1 то N хориҷ кунед.`
	f.tj[17] = `Адади ҳақиқии A ва адади бутуни N(>0) дода шудаанд. Бо истифодабарии як давр суммаи 1+A+A<sup>2</sup>+A<sup>3</sup>+...+A<sup>N</sup>-ро ёбед.`
	f.tj[18] = `Адади ҳақиқии A ва адади бутуни N(>0) дода шудаанд. Бо истифодабарии як давр қимати ифодаи 1–A+A<sup>2</sup>–A<sup>3</sup>+ ... + (–1)<sup>N</sup>*A<sup>N</sup>-ро ёбед. Оператори шартиро истифода набаред.`
	f.tj[19] = `Адади бутуни N(>0) дода шудааст. ҲосилиЗарби N!=1*2*...*N (N–факториал)-ро ёбед. Барои роҳ надодан ба пуршавии қатори ададҳои бутун ин зарбкуниро ба воситаи тағйирёбандаи ҳақиқӣ ҳисоб кунед ва онро чун адади ҳақиқӣ хориҷ кунед.`
	f.tj[20] = `Адади бутуни N(>0) дода шудааст. Бо истифодабарии як давр суммаи 1!+2!+3!+ ... +N!(ифодаи N! — N–факториал — ҳосилизарби ҳамаи ададҳои бутунро аз 1 то N ифода мекунад: N!=1*2* ... *N)-ро ёбед. Барои роҳ надодан ба пуршавии қатори ададҳои бутун ҳисобкуниро бо ёрии тағйирёбандаҳои ҳақиқӣ гузаронед ва натиҷаро чун адади ҳақиқӣ хориҷ кунед.`
	f.tj[21] = `Адади бутуни N(>0) дода шудааст. Бо истифодабарии як давр суммаи 1+1/(1!)+1/(2!)+1/(3!)+ ... +1/(N!)(ифодаи N! - N-факториал - ҳосилизарби ҳамаи ададҳои бутунро аз 1 то N ифода мекунад: N!=1*2*...*N)-ро ёбед. Адади ҳосилшуда қимати тақрибии доимии e=exp(1) ба ҳисоб меравад.`
	f.tj[22] = `Адади ҳақиқии X ва адади бутуни N(>0) дода шудаанд. Қимати ифодаи 1+X+X<sup>2</sup>/(2!)+...+X<sup>N</sup>/(N!) (N!=1*2*...*N)-ро ёбед. Адади ҳосилшуда қимати тақрибии функсияи exp дар нуқтаи X ба ҳисоб меравад.`
	f.tj[23] = `Адади ҳақиқии X ва адади бутуни N(>0) дода шудаанд. Қимати ифодаи X-X<sup>3</sup>/(3!)+X<sup>5</sup>/(5!)-...+(-1)<sup>N</sup>*X<sup>2*N+1</sup>/((2·N+1)!) (N!=1*2*...*N)-ро ёбед. Адади ҳосилшуда қимати тақрибии функсияи sin дар нуқтаи X ба ҳисоб меравад.`
	f.tj[24] = `Адади ҳақиқии X ва адади бутуни N(>0) дода шудаанд. Қимати ифодаи 1-X<sup>2</sup>/(2!)+X<sup>4</sup>/(4!)-...+(-1)<sup>N</sup>*X<sup>2*N</sup>/((2*N)!) (N!=1*2*...*N)-ро ёбед. Адади ҳосилшуда қимати тақрибии функсияи cos дар нуқтаи X ба ҳисоб меравад.`
	f.tj[25] = `Адади ҳақиқии X (|X|<1) ва адади бутуни N(>0) дода шудаанд. Қимати ифодаи X-X<sup>2</sup>/2+X<sup>3</sup>/3-...+(-1)<sup>N-1</sup>*X<sup>N</sup>/N-ро ёбед. Адади ҳосилшуда қимати тақрибии функсияи ln дар нуқтаи 1+X ба ҳисоб меравад.`
	f.tj[26] = `Адади ҳақиқии X (|X|<1) ва адади бутуни N(>0) дода шудаанд. Қимати ифодаи X-X<sup>3</sup>/3+X<sup>5</sup>/5-...+(-1)<sup>N</sup>*X<sup>2*N+1</sup>/(2*N+1)-ро ёбед. Адади ҳосилшуда қимати тақрибии функсияи arctg дар нуқтаи X ба ҳисоб меравад.`
	f.tj[27] = `Адади ҳақиқии X (|X|<1) ва адади бутуни N(>0) дода шудаанд. Қимати ифодаи X+1*X<sup>3</sup>/(2*3)+1*3*X<sup>5</sup>/(2*4*5)+...+1*3*...*(2*N-1)*X<sup>2*N+1</sup>/(2*4*...*(2*N)*(2*N+1))-ро ёбед. Адади ҳосилшуда қимати тақрибии функсии arcsin дар нуқтаи X ба ҳисоб меравад.`
	f.tj[28] = `Адади ҳақиқии X (|X|<1) ва адади бутуни N(>0) дода шудаанд. Қимати ифодаи 1+X/2-1*X<sup>2</sup>/(2*4)+1*3*X<sup>3</sup>/(2*4*6)-...+(-1)<sup>N-1</sup>*1*3*...*(2*N-3)*X<sup>N</sup>/(2*4*...*(2*N))-ро ёбед. Адади ҳосилшуда қимати тақрибии функсии sqrt(1+x) ба ҳисоб меравад.`
	f.tj[29] = `Адади бутуни N(>1) ва ду нуқтаҳои ҳақиқӣ дар тири ададӣ дода шудаанд: A, B (A&lt;B). Порчаи [A, B] ба N порчаҳои баробар тақсим шудааст. Дарозии ҳар як порча H-ро, ҳамчунин маҷмӯи нуқтаҳои A, A+H, A+2*H, A+3*H, ..., B-ро, ки тақсимшавии порчаи [A, B]-ро ба вуҷуд меоваранд, хориҷ кунед.`
	f.tj[30] = `Адади бутуни N(>1) ва ду нуқтаҳои ҳақиқӣ дар тири ададӣ дода шудаанд: A, B (A&lt;B). Порчаи [A, B] ба N порчаҳои баробар тақсим шудааст. Дарозии ҳар як порча H-ро, ҳамчунин қимати функсияи F(X)=1-sin(X)-ро дар нуқтаҳое, ки порчаи [A, B]-ро тақсим мекунанд, ёбед: F(A), F(A+H), F(A+2*H), ..., F(B).`
	f.tj[31] = `Адади бутуни N(>0) дода шудааст. Пайдарпайии ададҳои ҳақиқӣ A<sub>K</sub> ба тариқи зайл муайян карда мешавад: A<sub>0</sub>=2, A<sub>K</sub>=2+1/A<sub>K-1</sub>, K=1, 2, ... . Элементҳои A<sub>1</sub>, A<sub>2</sub>, ..., A<sub>N</sub>-ро хориҷ кунед.`
	f.tj[32] = `Адади бутуни N(>0) дода шудааст. Пайдарпайии ададҳои ҳақиқӣ A<sub>K</sub> ба тариқи зайл муайян карда мешавад: A<sub>0</sub>=1, A<sub>K</sub>=(A<sub>K-1</sub>+1)/K, K=1, 2, ... . Элементҳои A<sub>1</sub>, A<sub>2</sub>, ..., A<sub>N</sub>-ро хориҷ кунед.`
	f.tj[33] = `Адади бутуни N(>1) дода шудааст. Пайдарпайии ададҳои Фибоначчи F<sub>K</sub> (ададҳои типи бутун) ба тариқи зайл муайян карда мешавад: F<sub>1</sub>=1, F<sub>2</sub>=1, F<sub>K</sub>=F<sub>K-2</sub>+F<sub>K-1</sub>, K=3, 4, ... . Элементҳои F<sub>1</sub>, F<sub>2</sub>, ..., F<sub>N</sub>-ро хориҷ кунед.`
	f.tj[34] = `Адади бутуни N(>1) дода шудааст. Пайдарпайии ададҳои ҳақиқии A<sub>K</sub> ба тариқи зайл муайян карда мешавад: A<sub>1</sub>=1, A<sub>2</sub>=2, A<sub>K</sub>=(A<sub>K-2</sub>+2*A<sub>K-1</sub>)/3, K=3, 4, ... . Элементҳои A<sub>1</sub>, A<sub>2</sub>, ..., A<sub>N</sub>-ро хориҷ кунед.`
	f.tj[35] = `Адади бутуни N(>2) дода шудааст. Пайдарпайии ададҳои бутуни A<sub>K</sub> ба тариқи зайл муайян карда мешавад: A<sub>1</sub>=1, A<sub>2</sub>=2, A<sub>3</sub>=3, A<sub>K</sub>=A<sub>K-1</sub>+A<sub>K-2</sub>-2*A<sub>K-3</sub>, K=4, 5, ... . Элементҳои A<sub>1</sub>, A<sub>2</sub>, ..., A<sub>N</sub>-ро хориҷ кунед.`
	f.tj[36] = `Ададҳои бутуни мусбии N ва K дода шудаанд. Суммаи 1<sup>K</sup>+2<sup>K</sup>+ ... +N<sup>K</sup>-ро ёбед. Барои роҳ надодан ба пуршавии қатори ададҳои бутун ҷамъшавандаҳои ин суммаро бо ёрии тағйирёбандаи ҳақиқӣ ҳисоб кунед ва натиҷаро чун адади ҳақиқӣ хориҷ кунед.`
	f.tj[37] = `Адади бутуни N(>0) дода шудааст. Суммаи 1<sup>1</sup>+2<sup>2</sup>+ ... +N<sup>N</sup>-ро ёбед. Барои роҳ надодан ба пуршавии қатори ададҳои бутун ҷамъшавандаҳои ин суммаро бо ёрии тағйирёбандаи ҳақиқӣ ҳисоб кунед ва натиҷаро чун адади ҳақиқӣ хориҷ кунед.`
	f.tj[38] = `Адади бутуни N(>0) дода шудааст. Суммаи 1<sup>N</sup>+2<sup>N-1</sup>+...+N<sup>1</sup>-ро ёбед. Барои роҳ надодан ба пуршавии қатори ададҳои бутун ҷамъшавандаҳои ин суммаро бо ёрии тағйирёбандаи ҳақиқӣ ҳисоб кунед ва натиҷаро чун адади ҳақиқӣ хориҷ кунед.`
	f.tj[39] = `Ададҳои бутуни мусбии A ва B (A&lt;B) дода шудаанд. Ҳамаи ададҳои бутунро аз A то B дар якҷоягӣ хориҷ кунед; дар ин ҳангом ҳар як адад бояд ҳамон қадар хориҷ карда шавад, ки дар қиматаш нишон дода шудааст (масалан, адади 3 - 3 маротиба хориҷ карда мешавад).`
	f.tj[40] = `Ададҳои бутуни A ва B (A&lt;B) дода шудаанд. Ҳамаи ададҳои бутунро аз A то B дар якҷоягӣ хориҷ кунед; дар ин ҳангом адади A бояд 1 маротиба хориҷ карда шавад, адади A+1 бояд 2 маротиба хориҷ карда шавад ва ғ.`
}

func (f *ffor) makeRu() {
	f.ru = make([]string, f.count)
	f.ru[1] = `Даны целые числа&nbsp;<i>K</i> и&nbsp;<i>N</i> (<i>N</i>&nbsp;&gt;&nbsp;0). Вывести <i>N</i>&nbsp;раз число&nbsp;<i>K</i>.`
	f.ru[2] = `Даны два целых числа&nbsp;<i>A</i> и&nbsp;<i>B</i> (<i>A</i>&nbsp;&lt;&nbsp;<i>B</i>). Вывести в порядке возрастания все целые числа, расположенные между&nbsp;<i>A</i> и&nbsp;<i>B</i> (включая сами числа&nbsp;<i>A</i> и&nbsp;<i>B</i>), а также количество&nbsp;<i>N</i> этих чисел.`
	f.ru[3] = `Даны два целых числа&nbsp;<i>A</i> и&nbsp;<i>B</i> (<i>A</i>&nbsp;&lt;&nbsp;<i>B</i>). Вывести в порядке убывания все целые числа, расположенные между&nbsp;<i>A</i> и&nbsp;<i>B</i> (не включая числа&nbsp;<i>A</i> и&nbsp;<i>B</i>), а также количество&nbsp;<i>N</i> этих чисел.`
	f.ru[4] = `Дано вещественное число &#8212; цена 1&nbsp;кг конфет. Вывести стоимость 1, 2,&nbsp;&#8230;, 10&nbsp;кг конфет.`
	f.ru[5] = `Дано вещественное число &#8212; цена 1&nbsp;кг конфет. Вывести стоимость 0.1, 0.2,&nbsp;&#8230;, 1&nbsp;кг конфет.`
	f.ru[6] = `Дано вещественное число &#8212; цена 1&nbsp;кг конфет. Вывести стоимость 1.2, 1.4,&nbsp;&#8230;, 2&nbsp;кг конфет.`
	f.ru[7] = `Даны два целых числа&nbsp;<i>A</i> и&nbsp;<i>B</i> (<i>A</i>&nbsp;&lt;&nbsp;<i>B</i>). Найти сумму всех целых чисел от&nbsp;<i>A</i> до&nbsp;<i>B</i> включительно.`
	f.ru[8] = `Даны два целых числа&nbsp;<i>A</i> и&nbsp;<i>B</i> (<i>A</i>&nbsp;&lt;&nbsp;<i>B</i>). Найти произведение всех целых чисел от&nbsp;<i>A</i> до&nbsp;<i>B</i> включительно.`
	f.ru[9] = `Даны два целых числа&nbsp;<i>A</i> и&nbsp;<i>B</i> (<i>A</i>&nbsp;&lt;&nbsp;<i>B</i>). Найти сумму квадратов всех целых чисел от&nbsp;<i>A</i> до&nbsp;<i>B</i> включительно.`
	f.ru[10] = `Дано целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Найти сумму1&nbsp;+&nbsp;1/2&nbsp;+&nbsp;1/3&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;1/<i>N</i>(вещественное число).`
	f.ru[11] = `Дано целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Найти сумму<i>N</i><sup>2</sup>&nbsp;+&nbsp;(<i>N</i>&nbsp;+&nbsp;1)<sup>2</sup>&nbsp;+&nbsp;(<i>N</i>&nbsp;+&nbsp;2)<sup>2</sup>&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;(2&#183;<i>N</i>)<sup>2</sup>(целое число).`
	f.ru[12] = `Дано целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Найти произведение1.1&nbsp;&#183;&nbsp;1.2&nbsp;&#183;&nbsp;1.3&nbsp;&#183;&nbsp;&#8230;(<i>N</i>&nbsp;сомножителей).`
	f.ru[13] = `Дано целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Найти значение выражения1.1&nbsp;&#8722;&nbsp;1.2&nbsp;+&nbsp;1.3&nbsp;&#8722;&nbsp;&#8230;(<i>N</i>&nbsp;слагаемых, знаки чередуются). Условный оператор не использовать.`
	f.ru[14] = `Дано целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Найти квадрат данного числа, используя для его вычисления следующую формулу: <i>N</i><sup>2</sup>&nbsp;=&nbsp;1&nbsp;+&nbsp;3&nbsp;+&nbsp;5&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;(2&#183;<i>N</i>&nbsp;&#8722;&nbsp;1).После добавления к сумме каждого слагаемого выводить текущее значение суммы (в результате будут выведены квадраты всех целых чисел от&nbsp;1 до&nbsp;<i>N</i>).`
	f.ru[15] = `Дано вещественное число&nbsp;<i>A</i> и целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Найти&nbsp;<i>A</i> в степени&nbsp;<i>N</i>: <i>A</i><sup><i>N</i></sup> = <i>A</i>&#183;<i>A</i>&#183;&nbsp;&#8230;&nbsp;&#183;<i>A</i>(числа&nbsp;<i>A</i> перемножаются&nbsp;<i>N</i> раз).`
	f.ru[16] = `Дано вещественное число&nbsp;<i>A</i> и целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Используя один цикл, вывести все целые степени числа&nbsp;<i>A</i> от&nbsp;1 до&nbsp;<i>N</i>.`
	f.ru[17] = `Дано вещественное число&nbsp;<i>A</i> и целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Используя один цикл, найти сумму   1&nbsp;+&nbsp;<i>A</i>&nbsp;+&nbsp;<i>A</i><sup>2</sup>&nbsp;+&nbsp;<i>A</i><sup>3</sup>&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;<i>A</i><sup><i>N</i></sup>`
	f.ru[18] = `Дано вещественное число&nbsp;<i>A</i> и целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Используя один цикл, найти значение выражения 1&nbsp;&#8722;&nbsp;<i>A</i>&nbsp;+&nbsp;<i>A</i><sup>2</sup>&nbsp;&#8722;&nbsp;<i>A</i><sup>3</sup>&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;(&#8722;1)<sup><i>N</i></sup>&#183;<i>A</i><sup><i>N</i></sup>.Условный оператор не использовать.`
	f.ru[19] = `Дано целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Найти произведение<i>N</i>!&nbsp;=&nbsp;1&#183;2&#183;&#8230;&#183;<i>N</i>(<i><i>N</i>&#8211;факториал</i>). Чтобы избежать целочисленного переполнения, вычислять это произведение с помощью вещественной переменной и вывести его как вещественное число.`
	f.ru[20] = `Дано целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Используя один цикл, найти сумму 1!&nbsp;+&nbsp;2!&nbsp;+&nbsp;3!&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;<i>N</i>!    (выражение <i>N</i>! &#8212; <i><i>N</i>&#8211;факториал</i> &#8212; обозначает произведение всех целых чисел от&nbsp;1 до&nbsp;<i>N</i>: &nbsp; &nbsp;<i>N</i>!&nbsp;=&nbsp;1&#183;2&#183;&#8230;&#183;<i>N</i>). Чтобы избежать целочисленного переполнения, проводить вычисления с помощью вещественных переменных и вывести результат как вещественное число.`
	f.ru[21] = `Дано целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Используя один цикл, найти сумму 1&nbsp;+&nbsp;1/(1!)&nbsp;+&nbsp;1/(2!)&nbsp;+&nbsp;1/(3!)&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;1/(<i>N</i>!)(выражение <i>N</i>! &#8212; <i><i>N</i>&#8211;факториал</i> &#8212; обозначает произведение всех целых чисел от&nbsp;1 до&nbsp;<i>N</i>: &nbsp; &nbsp;<i>N</i>!&nbsp;=&nbsp;1&#183;2&#183;&#8230;&#183;<i>N</i>). Полученное число является приближенным значением константы <i>e</i>&nbsp;=&nbsp;exp(1).`
	f.ru[22] = `Дано вещественное число&nbsp;<i>X</i> и целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Найти значение выражения 1&nbsp;+&nbsp;<i>X</i>&nbsp;+&nbsp;<i>X</i><sup>2</sup>/(2!)&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;<i>X</i><sup><i>N</i></sup>/(<i>N</i>!)(<i>N</i>!&nbsp;=&nbsp;1&#183;2&#183;&#8230;&#183;<i>N</i>). Полученное число является приближенным значением функции exp в точке&nbsp;<i>X</i>.`
	f.ru[23] = `Дано вещественное число&nbsp;<i>X</i> и целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Найти значение выражения <i>X</i>&nbsp;&#8722;&nbsp;<i>X</i><sup>3</sup>/(3!)&nbsp;+&nbsp;<i>X</i><sup>5</sup>/(5!)&nbsp;&#8722;&nbsp;&#8230;&nbsp;+&nbsp;(&#8722;1)<sup><i>N</i></sup>&#183;<i>X</i><sup>2&#183;<i>N</i>+1</sup>/((2&#183;<i>N</i>+1)!)(<i>N</i>!&nbsp;=&nbsp;1&#183;2&#183;&#8230;&#183;<i>N</i>). Полученное число является приближенным значением функции sin в точке&nbsp;<i>X</i>.`
	f.ru[24] = `Дано вещественное число&nbsp;<i>X</i> и целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Найти значение выражения 1&nbsp;&#8722;&nbsp;<i>X</i><sup>2</sup>/(2!)&nbsp;+&nbsp;<i>X</i><sup>4</sup>/(4!)&nbsp;&#8722;&nbsp;&#8230;&nbsp;+&nbsp;(&#8722;1)<sup><i>N</i></sup>&#183;<i>X</i><sup>2&#183;<i>N</i></sup>/((2&#183;<i>N</i>)!)(<i>N</i>!&nbsp;=&nbsp;1&#183;2&#183;&#8230;&#183;<i>N</i>). Полученное число является приближенным значением функции cos в точке&nbsp;<i>X</i>.`
	f.ru[25] = `Дано вещественное число&nbsp;<i>X</i> (|<i>X</i>|&nbsp;&lt;&nbsp;1) и целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Найти значение выражения <i>X</i>&nbsp;&#8722;&nbsp;<i>X</i><sup>2</sup>/2&nbsp;+&nbsp;<i>X</i><sup>3</sup>/3&nbsp;&#8722;&nbsp;&#8230;&nbsp;+&nbsp;(&#8722;1)<sup><i>N</i>&#8722;1</sup>&#183;<i>X</i><sup><i>N</i></sup>/<i>N</i>.Полученное число является приближенным значением функции ln в точке&nbsp;1&nbsp;+&nbsp;<i>X</i>.`
	f.ru[26] = `Дано вещественное число&nbsp;<i>X</i> (|<i>X</i>|&nbsp;&lt;&nbsp;1) и целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Найти значение выражения <i>X</i>&nbsp;&#8722;&nbsp;<i>X</i><sup>3</sup>/3&nbsp;+&nbsp;<i>X</i><sup>5</sup>/5&nbsp;&#8722;&nbsp;&#8230;&nbsp;+&nbsp;(&#8722;1)<sup><i>N</i></sup>&#183;<i>X</i><sup>2&#183;<i>N</i>+1</sup>/(2&#183;<i>N</i>+1).Полученное число является приближенным значением функции arctg в точке&nbsp;<i>X</i>.`
	f.ru[27] = `Дано вещественное число&nbsp;<i>X</i> (|<i>X</i>|&nbsp;&lt;&nbsp;1) и целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Найти значение выражения <i>X</i>&nbsp;+&nbsp;1&#183;<i>X</i><sup>3</sup>/(2&#183;3)&nbsp;+&nbsp;1&#183;3&#183;<i>X</i><sup>5</sup>/(2&#183;4&#183;5)&nbsp;+&nbsp;&#8230;&nbsp;+<br>+&nbsp;1&#183;3&#183;&#8230;&#183;(2&#183;<i>N</i>&#8722;1)&#183;<i>X</i><sup>2&#183;<i>N</i>+1</sup>/(2&#183;4&#183;&#8230;&#183;(2&#183;<i>N</i>)&#183;(2&#183;<i>N</i>+1)).Полученное число является приближенным значением функции arcsin в точке&nbsp;<i>X</i>.`
	f.ru[28] = `Дано вещественное число&nbsp;<i>X</i> (|<i>X</i>|&nbsp;&lt;&nbsp;1) и целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Найти значение выражения 1&nbsp;+&nbsp;<i>X</i>/2&nbsp;&#8722;&nbsp;1&#183;<i>X</i><sup>2</sup>/(2&#183;4)&nbsp;+&nbsp;1&#183;3&#183;<i>X</i><sup>3</sup>/(2&#183;4&#183;6)&nbsp;&#8722;&nbsp;&#8230;&nbsp;+<br>+&nbsp;(&#8722;1)<sup><i>N</i>&#8722;1</sup>&#183;1&#183;3&#183;&#8230;&#183;(2&#183;<i>N</i>&#8722;3)&#183;<i>X</i><sup><i>N</i></sup>/(2&#183;4&#183;&#8230;&#183;(2&#183;<i>N</i>)).Полученное число является приближенным значением функции (1+<i>X</i>)<sup>1/2</sup>.`
	f.ru[29] = `Дано целое число&nbsp;<i>N</i> (&gt;&nbsp;1) и две вещественные точки на числовой оси: <i>A</i>,&nbsp;<i>B</i> (<i>A</i>&nbsp;&lt;&nbsp;<i>B</i>). Отрезок [<i>A</i>,&nbsp;<i>B</i>] разбит на&nbsp;<i>N</i> равных отрезков. Вывести&nbsp;<i>H</i> &#8212; длину каждого отрезка, а также набор точек<i>A</i>, &nbsp; &nbsp;<i>A</i>&nbsp;+&nbsp;<i>H</i>, &nbsp; &nbsp;<i>A</i>&nbsp;+&nbsp;2&#183;<i>H</i>, &nbsp; &nbsp;<i>A</i>&nbsp;+&nbsp;3&#183;<i>H</i>, &nbsp; &nbsp;&#8230;, &nbsp; &nbsp;<i>B</i>,образующий разбиение отрезка [<i>A</i>,&nbsp;<i>B</i>].`
	f.ru[30] = `Дано целое число&nbsp;<i>N</i> (&gt;&nbsp;1) и две вещественные точки на числовой оси: <i>A</i>,&nbsp;<i>B</i> (<i>A</i>&nbsp;&lt;&nbsp;<i>B</i>). Отрезок [<i>A</i>,&nbsp;<i>B</i>] разбит на&nbsp;<i>N</i> равных отрезков. Вывести&nbsp;<i>H</i> &#8212; длину каждого отрезка, а также значения функции <i>F</i>(<i>X</i>)&nbsp;=&nbsp;1&nbsp;&#8722;&nbsp;sin(<i>X</i>) в точках, разбивающих отрезок [<i>A</i>,&nbsp;<i>B</i>]:<i>F</i>(<i>A</i>), &nbsp; &nbsp;<i>F</i>(<i>A</i>&nbsp;+&nbsp;<i>H</i>), &nbsp; &nbsp;<i>F</i>(<i>A</i>&nbsp;+&nbsp;2&#183;<i>H</i>), &nbsp; &nbsp;&#8230;, &nbsp; &nbsp;<i>F</i>(<i>B</i>)`
	f.ru[31] = `Дано целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Последовательность вещественных чисел&nbsp;<i>A</i><sub><i>K</i></sub> определяется следующим образом: <i>A</i><sub>0</sub>&nbsp;=&nbsp;2, &nbsp; &nbsp; &nbsp; &nbsp;<i>A</i><sub><i>K</i></sub>&nbsp;=&nbsp;2&nbsp;+&nbsp;1/<i>A</i><sub><i>K</i>&#8722;1</sub>, &nbsp; &nbsp;<i>K</i>&nbsp;=&nbsp;1,&nbsp;2,&nbsp;&#8230;&nbsp;.Вывести элементы <i>A</i><sub>1</sub>, <i>A</i><sub>2</sub>,&nbsp;&#8230;,&nbsp;<i>A</i><sub><i>N</i></sub>.`
	f.ru[32] = `Дано целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Последовательность вещественных чисел&nbsp;<i>A</i><sub><i>K</i></sub> определяется следующим образом: <i>A</i><sub>0</sub>&nbsp;=&nbsp;1, &nbsp; &nbsp; &nbsp; &nbsp;<i>A</i><sub><i>K</i></sub>&nbsp;=&nbsp;(<i>A</i><sub><i>K</i>&#8722;1</sub>&nbsp;+&nbsp;1)/<i>K</i>, &nbsp; &nbsp;<i>K</i>&nbsp;=&nbsp;1,&nbsp;2,&nbsp;&#8230;&nbsp;.Вывести элементы <i>A</i><sub>1</sub>, <i>A</i><sub>2</sub>,&nbsp;&#8230;,&nbsp;<i>A</i><sub><i>N</i></sub>.`
	f.ru[33] = `Дано целое число&nbsp;<i>N</i> (&gt;&nbsp;1). Последовательность <i>чисел Фибоначчи</i>&nbsp;<i>F</i><sub><i>K</i></sub> (целого типа) определяется следующим образом: <i>F</i><sub>1</sub>&nbsp;=&nbsp;1, &nbsp; &nbsp; &nbsp; &nbsp;<i>F</i><sub>2</sub>&nbsp;=&nbsp;1, &nbsp; &nbsp; &nbsp; &nbsp;<i>F</i><sub><i>K</i></sub>&nbsp;=&nbsp;<i>F</i><sub><i>K</i>&#8722;2</sub>&nbsp;+&nbsp;<i>F</i><sub><i>K</i>&#8722;1</sub>, &nbsp; &nbsp;<i>K</i>&nbsp;=&nbsp;3,&nbsp;4,&nbsp;&#8230;&nbsp;.Вывести элементы <i>F</i><sub>1</sub>, <i>F</i><sub>2</sub>,&nbsp;&#8230;,&nbsp;<i>F</i><sub><i>N</i></sub>.`
	f.ru[34] = `Дано целое число&nbsp;<i>N</i> (&gt;&nbsp;1). Последовательность вещественных чисел&nbsp;<i>A</i><sub><i>K</i></sub> определяется следующим образом: <i>A</i><sub>1</sub>&nbsp;=&nbsp;1, &nbsp; &nbsp; &nbsp; &nbsp;<i>A</i><sub>2</sub>&nbsp;=&nbsp;2, &nbsp; &nbsp; &nbsp; &nbsp;<i>A</i><sub><i>K</i></sub>&nbsp;=&nbsp;(<i>A</i><sub><i>K</i>&#8722;2</sub>&nbsp;+&nbsp;2&#183;<i>A</i><sub><i>K</i>&#8722;1</sub>)/3, &nbsp; &nbsp;<i>K</i>&nbsp;=&nbsp;3,&nbsp;4,&nbsp;&#8230;&nbsp;.Вывести элементы <i>A</i><sub>1</sub>, <i>A</i><sub>2</sub>,&nbsp;&#8230;,&nbsp;<i>A</i><sub><i>N</i></sub>.`
	f.ru[35] = `Дано целое число&nbsp;<i>N</i> (&gt;&nbsp;2). Последовательность целых чисел&nbsp;<i>A</i><sub><i>K</i></sub> определяется следующим образом: <i>A</i><sub>1</sub>&nbsp;=&nbsp;1, &nbsp; &nbsp; &nbsp; &nbsp;<i>A</i><sub>2</sub>&nbsp;=&nbsp;2, &nbsp; &nbsp; &nbsp; &nbsp;<i>A</i><sub>3</sub>&nbsp;=&nbsp;3,  &nbsp; &nbsp; &nbsp; &nbsp;<i>A</i><sub><i>K</i></sub>&nbsp;=&nbsp;<i>A</i><sub><i>K</i>&#8722;1</sub>&nbsp;+&nbsp;<i>A</i><sub><i>K</i>&#8722;2</sub>&nbsp;&#8722;&nbsp;2&#183;<i>A</i><sub><i>K</i>&#8722;3</sub>, &nbsp; &nbsp;<i>K</i>&nbsp;=&nbsp;4,&nbsp;5,&nbsp;&#8230;&nbsp;.Вывести элементы <i>A</i><sub>1</sub>, <i>A</i><sub>2</sub>,&nbsp;&#8230;,&nbsp;<i>A</i><sub><i>N</i></sub>.`
	f.ru[36] = `Даны целые положительные числа&nbsp;<i>N</i> и&nbsp;<i>K</i>. Найти сумму1<sup><i>K</i></sup>&nbsp;+&nbsp;2<sup><i>K</i></sup>&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;<i>N</i><sup><i>K</i></sup>.Чтобы избежать целочисленного переполнения, вычислять слагаемые этой суммы с помощью вещественной переменной и выводить результат как вещественное число.`
	f.ru[37] = `Дано целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Найти сумму1<sup>1</sup>&nbsp;+&nbsp;2<sup>2</sup>&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;<i>N</i><sup><i>N</i></sup>.Чтобы избежать целочисленного переполнения, вычислять слагаемые этой суммы с помощью вещественной переменной и выводить результат как вещественное число.`
	f.ru[38] = `Дано целое число&nbsp;<i>N</i> (&gt;&nbsp;0). Найти сумму1<sup><i>N</i></sup>&nbsp;+&nbsp;2<sup><i>N</i>&#8722;1</sup>&nbsp;+&nbsp;&#8230;&nbsp;+&nbsp;<i>N</i><sup>1</sup>.Чтобы избежать целочисленного переполнения, вычислять слагаемые этой суммы с помощью вещественной переменной и выводить результат как вещественное число.`
	f.ru[39] = `Даны целые положительные числа&nbsp;<i>A</i> и&nbsp;<i>B</i> (<i>A</i>&nbsp;&lt;&nbsp;<i>B</i>). Вывести все целые числа от&nbsp;<i>A</i> до&nbsp;<i>B</i> включительно; при этом каждое число должно выводиться столько раз, каково его значение (например, число&nbsp;3 выводится 3&nbsp;раза).`
	f.ru[40] = `Даны целые числа&nbsp;<i>A</i> и&nbsp;<i>B</i> (<i>A</i>&nbsp;&lt;&nbsp;<i>B</i>). Вывести все целые числа от&nbsp;<i>A</i> до&nbsp;<i>B</i> включительно; при этом число&nbsp;<i>A</i> должно выводиться&nbsp;1 раз, число <i>A</i>&nbsp;+&nbsp;1 должно выводиться 2&nbsp;раза и&nbsp;т.&nbsp;д.`
}
