package task

type mmatrix struct {
	count int
	name  string
	en    []string
	tj    []string
	ru    []string
}

func NewMatrixTask() Task {
	m := &mmatrix{
		count: 101,
		name:  "Matrix",
	}
	m.makeEn()
	m.makeTj()
	m.makeRu()
	return m
}

func (m *mmatrix) Count() int   { return m.count }
func (m *mmatrix) Name() string { return m.name }
func (m *mmatrix) En() []string { return m.en }
func (m *mmatrix) Tj() []string { return m.tj }
func (m *mmatrix) Ru() []string { return m.ru }

func (m *mmatrix) makeEn() {
	m.en = make([]string, m.count)
	m.en[1] = `Given two positive integers&nbsp;<i>M</i> and&nbsp;<i>N</i>, create and output an <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of integers such that all its elements of the <i>I</i>-th&nbsp;row are equal to&nbsp;10&#183;<i>I</i> (<i>I</i>&nbsp;=&nbsp;1,&nbsp;&#8230;,&nbsp;<i>M</i>).`
	m.en[2] = `Given two positive integers&nbsp;<i>M</i> and&nbsp;<i>N</i>, create and output an <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of integers such that all its elements of the <i>J</i>-th&nbsp;column are equal to&nbsp;5&#183;<i>J</i> (<i>J</i>&nbsp;=&nbsp;1,&nbsp;&#8230;,&nbsp;<i>N</i>).`
	m.en[3] = `Two positive integers&nbsp;<i>M</i>, <i>N</i> and a sequence of <i>M</i>&nbsp;real numbers are given. Create and output an <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers such that each of its columns contains all numbers from the given sequence (in the same order).`
	m.en[4] = `Two positive integers&nbsp;<i>M</i>, <i>N</i> and a sequence of <i>M</i>&nbsp;real numbers are given. Create and output an <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers such that each of its rows contains all numbers from the given sequence (in the same order).`
	m.en[5] = `Two positive integers&nbsp;<i>M</i> and <i>N</i>, a real number&nbsp;<i>D</i>, and a sequence of <i>M</i>&nbsp;real numbers are given. Create and output an <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers such that its first column contains all numbers from the given sequence (in the same order), and elements of each next column are equal to the sum of the corresponding element of the previous column and the number&nbsp;<i>D</i> (so each row of the matrix will be an <i>arithmetic sequence</i> with the common difference&nbsp;<i>D</i>).`
	m.en[6] = `Two positive integers&nbsp;<i>M</i> and <i>N</i>, a real number&nbsp;<i>D</i>, and a sequence of <i>M</i>&nbsp;real numbers are given. Create and output an <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers such that its first row contains all numbers from the given sequence (in the same order), and elements of each next row are equal to the sum of the corresponding element of the previous row and the number&nbsp;<i>R</i> (so each column of the matrix will be a <i>geometric sequence</i> with the common ratio&nbsp;<i>R</i>).`
	m.en[7] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers and an integer&nbsp;<i>K</i> are given (1&nbsp;&#8804;&nbsp;<i>K</i>&nbsp;&#8804;&nbsp;<i>M</i>). Output elements of the matrix row with the order number&nbsp;<i>K</i>.`
	m.en[8] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers and an integer&nbsp;<i>K</i> are given (1&nbsp;&#8804;&nbsp;<i>K</i>&nbsp;&#8804;&nbsp;<i>M</i>). Output elements of the matrix column with the order number&nbsp;<i>K</i>.`
	m.en[9] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Output elements of its rows with even order numbers (2, 4,&nbsp;&#8230;). An output of matrix elements must be performed in the order of rows. Do not use conditional statements.`
	m.en[10] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Output elements of its columns with odd order numbers (1, 3,&nbsp;&#8230;). An output of matrix elements must be performed in the order of columns. Do not use conditional statements.`
	m.en[11] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Output elements of the matrix in the following order: the first row from left to right, the second row from right to left, the third row from left to right, the fourth row from right to left, and so on.`
	m.en[12] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Output elements of the matrix in the following order: the first column from up to down, the second column from down to up, the third column from up to down, the fourth column from down to up, and so on.`
	m.en[13] = `A real-valued square matrix&nbsp;<i>A</i> of order&nbsp;<i>M</i> is given. Starting with the element <i>A</i><sub>1,1</sub>, output its elements as follows: all elements of the first row, all elements of the <i>M</i>-th column except the element <i>A</i><sub>1,<i>M</i></sub> (which is already output), all remaining elements of the second row, all remaining elements of the (<i>M</i>&#8722;1)-th column, and so on; the element <i>A</i><sub><i>M</i>,1</sub> must be output in the end. All rows must be output from left to right, all columns must be output from up to down.`
	m.en[14] = `A real-valued square matrix&nbsp;<i>A</i> of order&nbsp;<i>M</i> is given. Starting with the element <i>A</i><sub>1,1</sub>, output its elements as follows: all elements of the first column, all elements of the <i>M</i>-th row except the element <i>A</i><sub><i>M</i>,1</sub> (which is already output), all remaining elements of the second column, all remaining elements of the (<i>M</i>&#8722;1)-th row, and so on; the element <i>A</i><sub>1,<i>M</i></sub> must be output in the end. All rows must be output from left to right, all columns must be output from up to down.`
	m.en[15] = `A real-valued square matrix&nbsp;<i>A</i> of order&nbsp;<i>M</i> is given (<i>M</i>&nbsp;is an odd number). Starting with the element <i>A</i><sub>1,1</sub> and moving clockwise, output all matrix elements <i>in the spiral order</i>: the first row from left to right, the last column from up to down, the last row from right to left, the first column from down to up, all remaining elements of the second row (from left to right), and so on; the central element of the matrix must be output in the end.`
	m.en[16] = `A real-valued square matrix&nbsp;<i>A</i> of order&nbsp;<i>M</i> is given (<i>M</i>&nbsp;is an odd number). Starting with the element <i>A</i><sub>1,1</sub> and moving counter-clockwise, output all matrix elements <i>in the spiral order</i>: the first column from up to down, the last row from left to right, the last column from down to up, the first row from right to left, all remaining elements of the second column (from up to down), and so on; the central element of the matrix must be output in the end.`
	m.en[17] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers and an integer&nbsp;<i>K</i> are given (1&nbsp;&#8804;&nbsp;<i>K</i>&nbsp;&#8804;&nbsp;<i>M</i>). Find the sum and the product of elements of the matrix row with the order number&nbsp;<i>K</i>.`
	m.en[18] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers and an integer&nbsp;<i>K</i> are given (1&nbsp;&#8804;&nbsp;<i>K</i>&nbsp;&#8804;&nbsp;<i>N</i>). Find the sum and the product of elements of the matrix column with the order number&nbsp;<i>K</i>.`
	m.en[19] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Find the sum of elements for each matrix row.`
	m.en[20] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Find the product of elements for each matrix column.`
	m.en[21] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Find the average of elements for each matrix row with odd order number (1, 3,&nbsp;&#8230;). Do not use conditional statements.`
	m.en[22] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Find the sum of elements for each matrix column with even order number (2, 4,&nbsp;&#8230;). Do not use conditional statements.`
	m.en[23] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Find the minimal element for each matrix row.`
	m.en[24] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Find the maximal element for each matrix column.`
	m.en[25] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Find the order number of the matrix row with the maximal sum of elements. Output this order number and the maximal sum value.`
	m.en[26] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Find the order number of the matrix column with the minimal product of elements. Output this order number and the minimal product value.`
	m.en[27] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Find the maximal value among the minimal elements of matrix rows.`
	m.en[28] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Find the minimal value among the maximal elements of matrix columns.`
	m.en[29] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. For each matrix row find the amount of elements that are smaller than the average of all elements of this row.`
	m.en[30] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. For each matrix column find the amount of elements that are greater than the average of all elements of this column.`
	m.en[31] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Find the order numbers of row and column for an element whose value is the closest to the average of all matrix elements.`
	m.en[32] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of integers is given. Find the order number of the first matrix row that contains the equal amount of positive and negative elements (zero elements are not considered). If the matrix does not contain the required rows then output&nbsp;0.`
	m.en[33] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of integers is given. Find the order number of the last matrix column that contains the equal amount of positive and negative elements (zero elements are not considered). If the matrix does not contain the required columns then output&nbsp;0.`
	m.en[34] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of integers is given. Find the order number of the last matrix row that contains even numbers only. If the matrix does not contain the required rows then output&nbsp;0.`
	m.en[35] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of integers is given. Find the order number of the first matrix column that contains odd numbers only. If the matrix does not contain the required columns then output&nbsp;0.`
	m.en[36] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of integers is given, values of its elements are in the range&nbsp;0 to&nbsp;100. A matrix row is called the <i>similar</i> with the other row if these rows contain the same set of numbers. For example, rows (1,&nbsp;3, 3,&nbsp;2) and (2,&nbsp;2, 1,&nbsp;3) contain the same set {1, 2,&nbsp;3} and therefore they are the similar rows. Find the amount of matrix rows that are the similar with the first row.`
	m.en[37] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of integers is given, values of its elements are in the range&nbsp;0 to&nbsp;100. A matrix column is called the <i>similar</i> with the other column if these columns contain the same set of numbers. For example, columns (1,&nbsp;3, 3,&nbsp;2) and (2,&nbsp;2, 1,&nbsp;3) contain the same set {1, 2,&nbsp;3} and therefore they are the similar columns. Find the amount of matrix columns that are the similar with the last column.`
	m.en[38] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of integers is given. Find the amount of its rows that contain no elements with equal values.`
	m.en[39] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of integers is given. Find the amount of its columns that contain no elements with equal values.`
	m.en[40] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of integers is given. Find the order number of the last row that contains the maximal amount of elements with equal values.`
	m.en[41] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of integers is given. Find the order number of the first column that contains the maximal amount of elements with equal values.`
	m.en[42] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Find the amount of its rows whose values of elements are sorted in ascending order.`
	m.en[43] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Find the amount of its columns whose values of elements are sorted in descending order.`
	m.en[44] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Find minimal element among elements of all matrix rows whose values of elements are sorted in ascending or descending order. If the matrix does not contain the required rows then output&nbsp;0 (as a real number).`
	m.en[45] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Find maximal element among elements of all matrix columns whose values of elements are sorted in ascending or descending order. If the matrix does not contain the required columns then output&nbsp;0 (as a real number).`
	m.en[46] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of integers is given. Find the matrix element that is the maximum in its row and the minimum in its column. If the matrix does not contain such elements then output&nbsp;0.`
	m.en[47] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers and two integers&nbsp;<i>K</i><sub>1</sub>, <i>K</i><sub>2</sub> are given (1&nbsp;&#8804;&nbsp;<i>K</i><sub>1</sub>&nbsp;&lt;&nbsp;<i>K</i><sub>2</sub>&nbsp;&#8804;&nbsp;<i>M</i>). Exchange matrix rows with the order numbers&nbsp;<i>K</i><sub>1</sub> and&nbsp;<i>K</i><sub>2</sub>.`
	m.en[48] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers and two integers&nbsp;<i>K</i><sub>1</sub>, <i>K</i><sub>2</sub> are given (1&nbsp;&#8804;&nbsp;<i>K</i><sub>1</sub>&nbsp;&lt;&nbsp;<i>K</i><sub>2</sub>&nbsp;&#8804;&nbsp;<i>N</i>). Exchange matrix columns with the order numbers&nbsp;<i>K</i><sub>1</sub> and&nbsp;<i>K</i><sub>2</sub>.`
	m.en[49] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. For each matrix row exchange values of its minimal and maximal element.`
	m.en[50] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. For each matrix column exchange values of its minimal and maximal element.`
	m.en[51] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Exchange matrix rows containing the minimal and the maximal element of the matrix.`
	m.en[52] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Exchange matrix columns containing the minimal and the maximal element of the matrix.`
	m.en[53] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Exchange the column with the order number&nbsp;1 and the last column that contains positive numbers only. If the matrix does not contain the required columns then do not change it.`
	m.en[54] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Exchange the column with the order number&nbsp;<i>N</i> and the first column that contains negative numbers only. If the matrix does not contain the required columns then do not change it.`
	m.en[55] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given (<i>M</i>&nbsp;is an even number). Exchange the upper and lower half of the matrix.`
	m.en[56] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given (<i>N</i>&nbsp;is an even number). Exchange the left and right half of the matrix.`
	m.en[57] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given (<i>M</i> and&nbsp;<i>N</i> are even numbers). Exchange the upper left and lower right quarter of the matrix.`
	m.en[58] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given (<i>M</i> and&nbsp;<i>N</i> are even numbers). Exchange the upper right and lower left quarter of the matrix.`
	m.en[59] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Reflect its elements about the horizontal axis of symmetry of the matrix (that is, exchange matrix rows with the order numbers&nbsp;<i>1</i> and&nbsp;<i>M</i>, 2 and&nbsp;<i>M</i>&nbsp;&#8722;&nbsp;1, and so on).`
	m.en[60] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Reflect its elements about the vertical axis of symmetry of the matrix (that is, exchange matrix columns with the order numbers&nbsp;<i>1</i> and&nbsp;<i>N</i>, 2 and&nbsp;<i>N</i>&nbsp;&#8722;&nbsp;1, and so on).`
	m.en[61] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers and an integer&nbsp;<i>K</i> are given (1&nbsp;&#8804;&nbsp;<i>K</i>&nbsp;&#8804;&nbsp;<i>M</i>). Remove the matrix row with the order number&nbsp;<i>K</i>.`
	m.en[62] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers and an integer&nbsp;<i>K</i> are given (1&nbsp;&#8804;&nbsp;<i>K</i>&nbsp;&#8804;&nbsp;<i>N</i>). Remove the matrix column with the order number&nbsp;<i>K</i>.`
	m.en[63] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Remove the matrix row that contains the minimal matrix element.`
	m.en[64] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Remove the matrix column that contains the maximal matrix element.`
	m.en[65] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Remove its first column that contains positive numbers only. If the matrix does not contain the required columns then do not change it.`
	m.en[66] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Remove its last column that contains negative numbers only. If the matrix does not contain the required columns then do not change it.`
	m.en[67] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. The matrix contains both positive and negative numbers. Remove all matrix columns that contain positive numbers only. If the matrix does not contain the required columns then do not change it.`
	m.en[68] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers and an integer&nbsp;<i>K</i> are given (1&nbsp;&#8804;&nbsp;<i>K</i>&nbsp;&#8804;&nbsp;<i>M</i>). Insert a new row of elements with zero value before the matrix row with the order number&nbsp;<i>K</i>.`
	m.en[69] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers and an integer&nbsp;<i>K</i> are given (1&nbsp;&#8804;&nbsp;<i>K</i>&nbsp;&#8804;&nbsp;<i>N</i>). Insert a new column of elements with the value&nbsp;1 after the matrix column with the order number&nbsp;<i>K</i>.`
	m.en[70] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Double the occurrence of the matrix row that contains the maximal matrix element.`
	m.en[71] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Double the occurrence of the matrix column that contains the minimal matrix element.`
	m.en[72] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Insert a new column of elements with the value 1 before the first matrix column that contains positive numbers only. If the matrix does not contain the required columns then do not change it.`
	m.en[73] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Insert a new column of elements with zero value after the last matrix column that contains negative numbers only. If the matrix does not contain the required columns then do not change it.`
	m.en[74] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. A matrix element is called the <i>local minimum</i> if it is smaller than all its neighbors. Replace all local minimums of the matrix by zero values. An additional matrix may be used for performing the required replacement.`
	m.en[75] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. A matrix element is called the <i>local maximum</i> if it is greater than all its neighbors. Replace values of all local maximums of the matrix by opposite values. An additional matrix may be used for performing the required replacement.`
	m.en[76] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Rearrange the matrix rows so that values of their first elements were in ascending order.`
	m.en[77] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Rearrange the matrix columns so that values of their last elements were in descending order.`
	m.en[78] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Rearrange the matrix rows so that minimal values of their elements were in descending order.`
	m.en[79] = `An <i>M</i>&nbsp;&#215;&nbsp;<i>N</i> matrix of real numbers is given. Rearrange the matrix columns so that maximal values of their elements were in ascending order.`
	m.en[80] = `A real-valued square matrix&nbsp;<i>A</i> of order&nbsp;<i>M</i> is given. Find the sum of elements of its <i>main diagonal</i>: <i>A</i><sub>1,1</sub>, &nbsp; &nbsp;<i>A</i><sub>2,2</sub>, &nbsp; &nbsp;<i>A</i><sub>3,3</sub>, &nbsp; &nbsp;&#8230;, &nbsp; &nbsp;<i>A</i><sub><i>M</i>,<i>M</i></sub>.`
	m.en[81] = `A real-valued square matrix&nbsp;<i>A</i> of order&nbsp;<i>M</i> is given. Find the average of elements of its <i>secondary diagonal</i>: <i>A</i><sub>1,<i>M</i></sub>, &nbsp; &nbsp;<i>A</i><sub>2,<i>M</i>&#8722;1</sub>, &nbsp; &nbsp;<i>A</i><sub>3,<i>M</i>&#8722;2</sub>, &nbsp; &nbsp;&#8230;, &nbsp; &nbsp;<i>A</i><sub><i>M</i>,1</sub>.`
	m.en[82] = `A real-valued square matrix&nbsp;<i>A</i> of order&nbsp;<i>M</i> is given. Find the sum of elements of each matrix diagonal that is parallel to the main diagonal. Begin with the single-element diagonal&nbsp;<i>A</i><sub>1,<i>M</i></sub>.`
	m.en[83] = `A real-valued square matrix&nbsp;<i>A</i> of order&nbsp;<i>M</i> is given. Find the sum of elements of each matrix diagonal that is parallel to the secondary diagonal. Begin with the single-element diagonal&nbsp;<i>A</i><sub>1,1</sub>.`
	m.en[84] = `A real-valued square matrix&nbsp;<i>A</i> of order&nbsp;<i>M</i> is given. Find the average of elements of each matrix diagonal that is parallel to the main diagonal. Begin with the single-element diagonal&nbsp;<i>A</i><sub>1,<i>M</i></sub>.`
	m.en[85] = `A real-valued square matrix&nbsp;<i>A</i> of order&nbsp;<i>M</i> is given. Find the average of elements of each matrix diagonal that is parallel to the secondary diagonal. Begin with the single-element diagonal&nbsp;<i>A</i><sub>1,1</sub>.`
	m.en[86] = `A real-valued square matrix&nbsp;<i>A</i> of order&nbsp;<i>M</i> is given. Find the minimal value of elements of each matrix diagonal that is parallel to the main diagonal. Begin with the single-element diagonal&nbsp;<i>A</i><sub>1,<i>M</i></sub>.`
	m.en[87] = `A real-valued square matrix&nbsp;<i>A</i> of order&nbsp;<i>M</i> is given. Find the maximal value of elements of each matrix diagonal that is parallel to the secondary diagonal. Begin with the single-element diagonal&nbsp;<i>A</i><sub>1,1</sub>.`
	m.en[88] = `A real-valued square matrix of order&nbsp;<i>M</i> is given. Assign zero value to the matrix elements that lie below the main diagonal. Do not use conditional statements.`
	m.en[89] = `A real-valued square matrix of order&nbsp;<i>M</i> is given. Assign zero value to the matrix elements that lie above the secondary diagonal. Do not use conditional statements.`
	m.en[90] = `A real-valued square matrix of order&nbsp;<i>M</i> is given. Assign zero value to the matrix elements that lie on the secondary diagonal or below it. Do not use conditional statements.`
	m.en[91] = `A real-valued square matrix of order&nbsp;<i>M</i> is given. Assign zero value to the matrix elements that lie on the main diagonal or above it. Do not use conditional statements.`
	m.en[92] = `A real-valued square matrix of order&nbsp;<i>M</i> is given. Assign zero value to the matrix elements that lie above the main diagonal and above the secondary diagonal simultaneously. Do not use conditional statements.`
	m.en[93] = `A real-valued square matrix of order&nbsp;<i>M</i> is given. Assign zero value to the matrix elements that lie above the main diagonal and below the secondary diagonal simultaneously. Do not use conditional statements.`
	m.en[94] = `A real-valued square matrix of order&nbsp;<i>M</i> is given. Assign zero value to the matrix elements that lie below the main diagonal (or on it) and above the secondary diagonal (or on it) simultaneously. Do not use conditional statements.`
	m.en[95] = `A real-valued square matrix of order&nbsp;<i>M</i> is given. Assign zero value to the matrix elements that lie below the main diagonal (or on it) and below the secondary diagonal (or on it) simultaneously. Do not use conditional statements.`
	m.en[96] = `A real-valued square matrix&nbsp;<i>A</i> of order&nbsp;<i>M</i> is given. Reflect its elements about the main diagonal (that is, exchange values of matrix elements&nbsp;<i>A</i><sub>1,2</sub> and&nbsp;<i>A</i><sub>2,1</sub>, <i>A</i><sub>1,3</sub> and&nbsp;<i>A</i><sub>3,1</sub>, and so on). Do not use an additional matrix.`
	m.en[97] = `A real-valued square matrix&nbsp;<i>A</i> of order&nbsp;<i>M</i> is given. Reflect its elements about the secondary diagonal (that is, exchange values of matrix elements&nbsp;<i>A</i><sub>1,1</sub> and&nbsp;<i>A</i><sub><i>M</i>,<i>M</i></sub>, <i>A</i><sub>1,2</sub> and&nbsp;<i>A</i><sub><i>M</i>&#8722;1,<i>M</i></sub>, and so on). Do not use an additional matrix.`
	m.en[98] = `A real-valued square matrix&nbsp;<i>A</i> of order&nbsp;<i>M</i> is given. Rotate its elements by 180&#176; (that is, exchange values of matrix elements&nbsp;<i>A</i><sub>1,1</sub> and&nbsp;<i>A</i><sub><i>M</i>,<i>M</i></sub>, <i>A</i><sub>1,2</sub> and&nbsp;<i>A</i><sub><i>M</i>,<i>M</i>&#8722;1</sub>, and so on). Do not use an additional matrix.`
	m.en[99] = `A real-valued square matrix&nbsp;<i>A</i> of order&nbsp;<i>M</i> is given. Rotate its elements counter-clockwise by 90&#176; (that is, assign an initial value of&nbsp;<i>A</i><sub>1,1</sub> to&nbsp;<i>A</i><sub><i>M</i>,1</sub>, an initial value of&nbsp;<i>A</i><sub><i>M</i>,1</sub> to&nbsp;<i>A</i><sub><i>M</i>,<i>M</i></sub>, and so on). Do not use an additional matrix.`
	m.en[100] = `A real-valued square matrix&nbsp;<i>A</i> of order&nbsp;<i>M</i> is given. Rotate its elements clockwise by 90&#176; (that is, assign an initial value of&nbsp;<i>A</i><sub>1,1</sub> to&nbsp;<i>A</i><sub>1,<i>M</i></sub>, an initial value of&nbsp;<i>A</i><sub>1,<i>M</i></sub> to&nbsp;<i>A</i><sub><i>M</i>,<i>M</i></sub>, and so on). Do not use an additional matrix.`
}

func (m *mmatrix) makeTj() {
	m.tj = make([]string, m.count)
	m.tj[1] = `Ададҳои бутуни мусбии M ва N дода шудаанд. Матритсаи типи бутуни андозаи M x N-ро тартиб диҳед, ки дар он ҳамаи элементҳои сатри I-ӯм дорои қимати 10•I (I = 1, …, M) мебошанд.`
	m.tj[2] = `Ададҳои бутуни мусбии M ва N дода шудаанд. Матритсаи типи бутуни андозаи M x N-ро тартиб диҳед, ки дар он ҳамаи элементҳои сутуни J-ӯм дорои қимати 5•J (J = 1, …, N) мебошанд.`
	m.tj[3] = `Ададҳои бутуни мусбии M, N ва маҷмӯъ аз M ададҳо дода шудаанд. Матритсаи андозаи M x N-ро тартиб диҳед, ки дар он дар ҳар як сутун ҳамаи ададҳои маҷмӯи ибтидоӣ (бо ҳамон тартиб) бошанд.`
	m.tj[4] = `Ададҳои бутуни мусбии M, N ва маҷмӯъ аз N ададҳо дода шудаанд. Матритсаи андозаи M x N-ро тартиб диҳед, ки дар он дар ҳар як сатр ҳамаи ададҳои маҷмӯи ибтидоӣ (бо ҳамон тартиб) бошанд.`
	m.tj[5] = `Ададҳои бутуни мусбии M, N, адади D ва маҷмӯи дорои M ададҳо дода шудаанд. Матритсаи андозаи M x N-ро тартиб диҳед, ки дар он сутуни аввалин бо маҷмӯи ададҳои ибтидоӣ мувофиқат мекунад, элементҳои ҳар як сутуни оянда ба суммаи элементи сутуни пешина ва адади D баробаранд (дар натиҷа ҳар як сатри матритса элементҳои прогрессияи арифметикиро доро мешавад).`
	m.tj[6] = `Ададҳои бутуни мусбии M, N, адади Q ва маҷмӯи дорои N ададҳо дода шудаанд. Матритсаи андозаи M x N-ро тартиб диҳед, ки дар он сатри аввал бо маҷмӯи ададҳои ибтидоӣ мувофиқ аст, элементҳои ҳар як сатри оянда бошанд, ба ҳосилизарби элементи мувофиқи сатри пешина ва Q баробаранд (дар натиҷа ҳар як сутуни матритса элементҳои прогрессияи геометриро доро мешавад).`
	m.tj[7] = `Матритсаи андозаи M x N ва адади бутуни K (1 &lt;= K &lt;= M) дода шудаанд. Элементҳои сатри K-ӯми матритсаи мазкурро хориҷ кунед.`
	m.tj[8] = `Матритсаи андозаи M x N ва адади бутуни K (1 &lt;= K &lt;= N) дода шудаанд. Элементҳои сутуни K-ӯми матритсаи мазкурро хориҷ кунед.`
	m.tj[9] = `Матритсаи андозаи M x N дода шудааст. Элементҳои онро, ки дар сатрҳои дорои рақамҳои тартибии ҷуфт (2, 4, …) ҷойгиранд, хориҷ кунед. Хориҷкунии элементҳоро аз рӯи сатрҳо иҷро кунед, оператори шартиро истифода набаред.`
	m.tj[10] = `Матритсаи андозаи M x N дода шудааст. Элементҳои онро, ки дар сутунҳои дорои рақамҳои тартибии тоқ (1, 3, …) ҷойгиранд, хориҷ кунед. Хориҷкунии элементҳоро аз рӯи сутунҳо иҷро кунед, оператори шартиро истифода набаред.`
	m.tj[11] = `Матритсаи андозаи M x N дода шудааст. Элементҳои онро аз рӯи тартиби зерин хориҷ кунед: сатри аввал аз чап ба рост, сатри дуюм аз рост ба чап, сатри сеюм аз чап ба рост, сатри чорӯм аз рост ба чап ва ғ.`
	m.tj[12] = `Матритсаи андозаи M x N дода шудааст. Элементҳои онро аз рӯи тартиби зерин хориҷ кунед: сутуни аввал аз боло ба поён, сутуни дуюм аз поён ба боло, сутуни сеюм аз боло ба поён, сутуни чорӯм аз поён ба боло ва ғ.`
	m.tj[13] = `Матритсаи квадратии A бо тартиби M дода шудааст. Аз элементи A<sub>1,1</sub> сар карда, элементҳои онро ба тариқи зайл хориҷ кунед («аз рӯи гӯшаҳо»): ҳамаи элементҳои сатри якӯм; элементҳои сутуни охирин, ба ғайр аз элементи якӯм (аллакай хориҷ шудааст); элементҳои боқимондаи сатри дуюм; элементҳои боқимондаи сутуни пешазохирон ва ғ.; охирон элементи A<sub>M,1</sub> хориҷ карда мешавад.`
	m.tj[14] = `Матритсаи квадратии A бо тартиби M дода шудааст. Аз элементи A<sub>1,1</sub> сар карда, элементҳои онро бо тартиби зерин хориҷ кунед («аз рӯи гӯшаҳо»): ҳамаи элементҳои сутуни якӯм; элементҳои сатри охирин, ба ғайр аз элементи якӯм (аллакай хориҷ шудааст); элементҳои боқимондаи сутуни дуюм; элементҳои боқимондаи сатри пешазохирон ва ғ.; охирон элементи A<sub>1,M</sub> хориҷ карда мешавад.`
	m.tj[15] = `Матритсаи квадратии A бо тартиби M (M — адади тоқ) дода шудааст. Аз элементи A<sub>1,1</sub> сар карда ва аз рӯи ақрабаки соат ҷой иваз намуда, ҳамаи элементҳои онро ба таври симпеч хориҷ кунед: сатри якӯм, сутуни охирон, сатри охирон бо тартиби баръакс, сутуни якӯм бо тартиби баръакс, элементҳои боқимондаи сатри дуюм ва ғ.; охирон элементи марказии матритса хориҷ карда мешавад.`
	m.tj[16] = `Матритсаи квадратии A бо тартиби M (M — адади тоқ) дода шудааст. Аз элементи A<sub>1,1</sub> сар карда ва бар муқобили ақрабаки соат ҷой иваз намуда, ҳамаи элементҳои онро ба таври симпеч хориҷ кунед: сутуни якӯм, сатри охирон, сутуни охирон бо тартиби баръакс, сатри якӯм бо тартиби баръакс, элементҳои боқимондаи сутуни дуюм ва ғ.; охирон элементи марказии матритса хориҷ карда мешавад.`
	m.tj[17] = `Матритсаи андозаи M x N ва адади бутуни K (1 &lt;= K &lt;= M) дода шудаанд. Сумма ва ҳосилизарби элементҳои сатри K-ӯми матритсаи мазкурро ёбед.`
	m.tj[18] = `Матритсаи андозаи M x N ва адади бутуни K (1 &lt;= K &lt;= N) дода шудаанд. Сумма ва ҳосилизарби элементҳои сутуни K-ӯми матритсаи мазкурро ёбед.`
	m.tj[19] = `Матритсаи андозаи M x N дода шудааст. Барои ҳар як сатри матритса суммаи элементҳояшро ёбед.`
	m.tj[20] = `Матритсаи андозаи M x N дода шудааст. Барои ҳар як сутуни матритса хосилизарби элементҳояшро ёбед.`
	m.tj[21] = `Матритсаи андозаи M x N дода шудааст. Барои ҳар як сатри матритса, ки дорои рақами тартибии тоқ (1, 3, …) аст, қимати миёнаи арифметикии элементҳояшро ёбед. Оператори шартиро истифода набаред.`
	m.tj[22] = `Матритсаи андозаи M x N дода шудааст. Барои ҳар як сутуни матритса, ки дорои рақами тартибии ҷуфт (2, 4, …) аст, суммаи элементҳояшро ёбед. Оператори шартиро истифода набаред.`
	m.tj[23] = `Матритсаи андозаи M x N дода шудааст. Дар ҳар як сатри матритса элементи хурдтаринро ёбед.`
	m.tj[24] = `Матритсаи андозаи M x N дода шудааст. Дар ҳар як сутуни матритса элементи калонтаринро ёбед.`
	m.tj[25] = `Матритсаи андозаи M x N дода шудааст. Рақами сатри онро, ки дорои суммаи калонтарини элементҳо мебошад, ёбед ва ин рақамро хориҷ кунед, ҳамчунин қимати суммаи калонтаринро низ хориҷ кунед.`
	m.tj[26] = `Матритсаи андозаи M x N дода шудааст. Рақами сутуни онро, ки дорои ҳосилизарби хурдтарини элементҳо мебошад, ёбед ва ин рақамро хориҷ кунед, ҳамчунин қимати ҳосилизарби хурдтаринро низ хориҷ кунед.`
	m.tj[27] = `Матритсаи андозаи M x N дода шудааст. Аз байни элементҳои хурдтарини сатрҳои он калонтаринашро ёбед.`
	m.tj[28] = `Матритсаи андозаи M x N дода шудааст. Аз байни элементҳои калонтарини сутунҳои он хурдтаринашро ёбед.`
	m.tj[29] = `Матритсаи андозаи M x N дода шудааст. Дар ҳар як сатри он миқдори элементҳоеро ёбед, ки аз қимати миёнаи арифметикии ҳамаи элементҳои ин сатр хурданд.`
	m.tj[30] = `Матритсаи андозаи M x N дода шудааст. Дар ҳар як сутуни он миқдори элементҳоеро ёбед, ки аз қимати миёнаи арифметикии ҳамаи элементҳои ин сутун калонанд.`
	m.tj[31] = `Матритсаи андозаи M x N дода шудааст. Рақамҳои сатр ва сутунро барои он элементи матритса ёбед, ки ба қимати миёнаи ҳамаи элементҳои он наздиктарин аст.`
	m.tj[32] = `Матритсаи типи бутуни андозаи M x N дода шудааст. Рақами сатри аввалинро аз сатрҳои он, ки миқдори баробари элементҳои мусбӣ ва манфиро доростанд, ёбед (элементҳои нулии матритса ба назар гирифта намешаванд). Агар чунин сатр набошад, пас 0(нул)-ро хориҷ кунед.`
	m.tj[33] = `Матритсаи типи бутуни андозаи M x N дода шудааст. Рақами сутуни охиринро аз сутунҳои он, ки миқдори баробари элементҳои мусбӣ ва манфиро доростанд, ёбед (элементҳои нулии матритса ба назар гирифта намешаванд). Агар чунин сутун набошад, пас 0(нул)-ро хориҷ кунед.`
	m.tj[34] = `Матритсаи типи бутуни андозаи M x N дода шудааст. Рақами сатри охиринро аз сатрҳои он, ки фақат ададҳои ҷуфт доранд, ёбед. Агар чунин сатр набошад, пас 0(нул)-ро хориҷ кунед.`
	m.tj[35] = `Матритсаи типи бутуни андозаи M x N дода шудааст. Рақами сутуни аввалинро аз сутунҳои он, ки фақат ададҳои тоқ доранд, ёбед. Агар чунин сутун набошад, пас 0(нул)-ро хориҷ кунед.`
	m.tj[36] = `Матритсаи типи бутуни андозаи M x N дода шудааст, ки элементҳои он қиматҳоро аз 0 то 100 қабул карда метавонанд. Сатрҳои гуногуни матритсаро монанд меномем, агар маҷмӯи ададҳое, ки дар ин сатрҳо вомехӯранд, мувофиқ оянд. Миқдори сатрҳое ёбед, ки ба сатри якӯми матритсаи мазкур монанданд.`
	m.tj[37] = `Матритсаи типи бутуни андозаи M x N дода шудааст, ки элементҳои он қиматҳоро аз 0 то 100 қабул карда метавонанд. Сутунҳои гуногуни матритсаро монанд меномем, агар маҷмӯи ададҳое, ки дар ин сутунҳо вомехӯранд, мувофиқ оянд. Миқдори сутунҳоеро ёбед, ки ба сутуни охирини матритсаи мазкур монанданд.`
	m.tj[38] = `Матритсаи типи бутуни андозаи M x N дода шудааст. Миқдори сатрҳои онро, ки ҳамаи элементҳои он гуногунанд, ёбед.`
	m.tj[39] = `Матритсаи типи бутуни андозаи M x N дода шудааст. Миқдори сутунҳои онро, ки ҳамаи элементҳои он гуногунанд, ёбед.`
	m.tj[40] = `Матритсаи типи бутуни андозаи M x N дода шудааст. Рақами сатри охиринро аз сатрҳои он, ки миқдори калонтарини элементҳои якхеларо доростанд, ёбед.`
	m.tj[41] = `Матритсаи типи бутуни андозаи M x N дода шудааст. Рақами сутуни аввалинро аз сутунҳои он, ки миқдори калонтарини элементҳои якхеларо доростанд, ёбед.`
	m.tj[42] = `Матритсаи андозаи M x N дода шудааст. Миқдори сатрҳои онро ёбед, ки элементҳои онҳо аз рӯи афзуншавӣ ба тартиб гузошта шудаанд.`
	m.tj[43] = `Матритсаи андозаи M x N дода шудааст. Миқдори сутунҳои онро ёбед, ки элементҳои онҳо аз рӯи камшавӣ ба тартиб гузошта шудаанд.`
	m.tj[44] = `Матритсаи андозаи M x N дода шудааст. Аз байни элементҳои он сатрҳо, ки ё аз рӯи афзуншавӣ, ё аз рӯи камшавӣ ба тартиб гузошта шудаанд, элементи хурдтаринро ёбед. Агар дар матритса сатри батартибгузошташуда набошад, пас 0(нул)-ро хориҷ кунед.`
	m.tj[45] = `Матритсаи андозаи M x N дода шудааст. Аз байни элементҳои он сутунҳо, ки ё аз рӯи афзуншавӣ, ё аз рӯи камшавӣ ба тартиб гузошта шудаанд, элементи калонтаринро ёбед. Агар дар матритса сутуни батартибгузошташуда набошад, пас 0(нул)-ро хориҷ кунед.`
	m.tj[46] = `Матритсаи типи бутуни андозаи M x N дода шудааст. Элементеро ёбед, ки дар сатри худ калонтарин аст ва дар сутуни худ хурдтарин аст. Агар чунин элемент набошад, пас 0(нул)-ро хориҷ кунед.`
	m.tj[47] = `Матритсаи андозаи M x N ва ададҳои бутуни K<sub>1</sub> ва K<sub>2</sub> (1 &lt;= K<sub>1</sub> < K<sub>2</sub> &lt;= M) дода шудаанд. Ҷойҳои сатрҳои матритсаро, ки дорои рақамҳои K<sub>1</sub> ва K<sub>2</sub> ҳастанд, иваз кунед.`
	m.tj[48] = `Матритсаи андозаи M x N ва ададҳои бутуни K<sub>1</sub> ва K<sub>2</sub> (1 &lt;= K<sub>1</sub> < K<sub>2</sub> &lt;= N) дода шудаанд. Ҷойҳои сутунҳои матритсаро, ки дорои рақамҳои K<sub>1</sub> ва K<sub>2</sub> ҳастанд, иваз кунед.`
	m.tj[49] = `Матритсаи андозаи M x N дода шудааст. Бо ивазкунии ҷойҳои элементҳои калонтарин ва хурдтарин дар ҳар як сатр, матритсаро тағйир диҳед.`
	m.tj[50] = `Матритсаи андозаи M x N дода шудааст. Бо ивазкунии ҷойҳои элементҳои калонтарин ва хурдтарин дар ҳар як сутун, матритсаро тағйир диҳед.`
	m.tj[51] = `Матритсаи андозаи M x N дода шудааст. Ҷойҳои сатрҳоеро, ки элементҳои хурдтарин ва калонтарини матритсаро доростанд, иваз кунед.`
	m.tj[52] = `Матритсаи андозаи M x N дода шудааст. Ҷойҳои сутунҳоеро, ки элементҳои хурдтарин ва калонтарини матритсаро доростанд, иваз кунед.`
	m.tj[53] = `Матритсаи андозаи M x N дода шудааст. Ҷойи сутуни дорои рақами тартибии 1-ро бо сутуни охирин аз сутунҳое, ки фақат элементҳои мусбӣ доранд, иваз кунед. Агар сутуни талабкардашуда набошад, пас матритсаро бе тағйирот хориҷ кунед.`
	m.tj[54] = `Матритсаи андозаи M x N дода шудааст. Ҷойи сутуни дорои рақами тартибии N-ро бо сутуни аввалин аз сутунҳое, ки фақат элементҳои манфӣ доранд, иваз кунед. Агар сутуни талабкардашуда набошад, пас матритсаро бе тағйирот хориҷ кунед.`
	m.tj[55] = `Матритсаи андозаи M x N (M — адади ҷуфт) дода шудааст. Ҷойҳои нимаҳои болоӣ ва поёнии матритсаро иваз кунед.`
	m.tj[56] = `Матритсаи андозаи M x N (N — адади ҷуфт) дода шудааст. Ҷойҳои нимаҳои рост ва чапи матритсаро иваз кунед.`
	m.tj[57] = `Матритсаи андозаи M x N (M ва N — ададҳои ҷуфт) дода шудааст. Ҷойҳои чорякҳои чап-болоӣ ва рост-поёнии матритсаро иваз кунед.`
	m.tj[58] = `Матритсаи андозаи M x N (M ва N — ададҳои ҷуфт) дода шудааст. Ҷойҳои чорякҳои чап-поёнӣ ва рост-болоии матритсаро иваз кунед.`
	m.tj[59] = `Матритсаи андозаи M x N дода шудаст. Элементҳои онро нисбат тири уфуқӣ (ҳоризонталӣ)-и таносуби матритса ба таври оина тасвир кунед (дар ин ҳангом ҷойҳои сатрҳои дорои рақамҳои 1 ва M, 2 ва M – 1 ва ғ. иваз карда мешаванд).`
	m.tj[60] = `Матритсаи андозаи M x N дода шудааст. Элементҳои онро нисбат ба тири амудӣ (вертикалӣ)-и таносуби матритса ба таври оина тасвир кунед (дар ин ҳангом ҷойҳои сутунҳои дорои рақамҳои 1 ва N, 2 ва N – 1 ва ғ. иваз карда мешаванд).`
	m.tj[61] = `Матритсаи андозаи M x N ва адади бутуни K (1 &lt;= K &lt;= M) дода шудаанд. Сатри матритсаро, ки дорои рақами K аст, нест кунед.`
	m.tj[62] = `Матритсаи андозаи M x N ва адади бутуни K (1 &lt;= K &lt;= N) дода шудаанд. Сутуни матритсаро, ки дорои рақами K аст, нест кунед.`
	m.tj[63] = `Матритсаи андозаи M x N дода шудааст. Сатреро нест кунед, ки элементи хурдтарини матритсаро дорост.`
	m.tj[64] = `Матритсаи андозаи M x N дода шудааст. Сутунеро нест кунед, ки элементи калонтарини матритсаро дорост.`
	m.tj[65] = `Матритсаи андозаи M x N дода шудааст. Сутуни аввалини онро, ки фақат элементҳои мусбиро дорост, нест кунед. Агар сутуни талабкардашуда набошад, пас матритсаро бе тағйирот хориҷ кунед.`
	m.tj[66] = `Матритсаи андозаи M x N дода шудааст. Сутуни охирини онро, ки фақат элементҳои манфиро дорост, нест кунед. Агар сутуни талабкардашуда набошад, пас матритсаро бе тағйирот хориҷ кунед.`
	m.tj[67] = `Матритсаи андозаи M x N, ки ҳам элементҳои мусбӣ ва ҳам элементҳои манфиро дорост, дода шудааст. Ҳамаи сутунҳои онро, ки фақат элементҳои мусбиро доростанд, нест кунед. Агар сутуни талабкардашуда набошад, пас матритсаро бе тағйирот хориҷ кунед.`
	m.tj[68] = `Матритсаи андозаи M x N ва адади бутуни K (1 &lt;= K &lt;= M) дода шудаанд. Пеш аз сатри матритса, ки дорои рақами K аст, сатри нулҳоро гузоред.`
	m.tj[69] = `Матритсаи андозаи M x N ва адади бутуни K (1 &lt;= K &lt;= N) дода шудаанд. Пас аз сутуни матритса, ки дорои рақами K аст, сутуни нулҳоро гузоред.`
	m.tj[70] = `Матритсаи андозаи M x N дода шудааст. Сатри матритсаро, ки элементи калонтарини онро дорост, дуто кунед.`
	m.tj[71] = `Матритсаи андозаи M x N дода шудааст. Сутуни матритсаро, ки элементи хурдтарини онро дорост, дуто кунед.`
	m.tj[72] = `Матритсаи андозаи M x N дода шудааст. Пеш аз сутуни аввалине, ки фақат элементҳои мусбиро дорост, сутуни воҳидҳоро гузоред. Агар сутуни талабкардашуда набошад, пас матритсаро бе тағйирот хориҷ кунед.`
	m.tj[73] = `Матритсаи андозаи M x N дода шудааст. Пас аз сутуни охирине, ки фақат элементҳои манфиро дорост, сутуни нулҳоро гузоред. Агар сутуни талабкардашуда набошад, пас матритсаро бе тағйирот хориҷ кунед.`
	m.tj[74] = `Матритсаи андозаи M x N дода шудааст. Элементи матритса - элементи хурдтарини локалии он номида мешавад, агар он элемент аз ҳамаи элементҳои атрофи худ хурд бошад. Ҳамаи элементҳои хурдтарини локалии матритсаи мазкурро ба нулҳо иваз кунед. Ҳангоми ҳал истифодабарии матритсаи ёридиҳанда иҷозат дода мешавад.`
	m.tj[75] = `Матритсаи андозаи M x N дода шудааст. Элементи матритса - элементи калонтарини локалии он номида мешавад, агар он элемент аз ҳамаи элементҳои атрофи худ калон бошад. Аломати ҳамаи элементҳои калонтарини локалии матритсаи мазкурро ба баръаксаш иваз кунед. Ҳангоми ҳал истифодабарии матритсаи ёридиҳанда иҷозат дода мешавад.`
	m.tj[76] = `Матритсаи андозаи M x N дода шудааст. Сатрҳои онро чунон ба тартиб гузоред, ки элементҳои аввалини онҳо пайдарпайии афзуншавандаро ташкил диҳанд.`
	m.tj[77] = `Матритсаи андозаи M x N дода шудааст. Сутунҳои онро чунон ба тартиб гузоред, ки элементҳои охирини онҳо пайдарпайии камшавандаро ташкил диҳанд.`
	m.tj[78] = `Матритсаи андозаи M x N дода шудааст. Сатрҳои онро чунон ба тартиб гузоред, ки элементҳои хурдтарини онҳо пайдарпайии камшавандаро ташкил диҳанд.`
	m.tj[79] = `Матритсаи андозаи M x N дода шудааст. Сутунҳои онро чунон ба тартиб гузоред, ки элементҳои калонтарини онҳо пайдарпайии афзуншавандаро ташкил диҳанд.`
	m.tj[80] = `Матритсаи квадратии A бо тартиби M дода шудааст. Суммаи элементҳои диагонали асосии онро ёбед, яъне диагоналеро, ки элементҳои зеринро дорост: A<sub>1,1</sub>,    A<sub>2,2</sub>,    A<sub>3,3</sub>,    …,    A<sub>M,M</sub>.`
	m.tj[81] = `Матритсаи квадратии A бо тартиби M дода шудааст. Қимати миёнаи арифметикии элементҳои диагонали ғайриасосии онро ёбед, яъне диагоналеро, ки элементҳои зеринро дорост: A<sub>1,M</sub>,    A<sub>2,M-1</sub>,    A<sub>3,M-2</sub>,    …,    A<sub>M,1</sub>.`
	m.tj[82] = `Матритсаи квадратии A бо тартиби M дода шудааст. Суммаи элементҳои ҳар як диагонали онро, ки ба диагонали асосӣ параллел аст (аз диагонали якэлементаи A<sub>1,M</sub> сар карда), ёбед.`
	m.tj[83] = `Матритсаи квадратии A бо тартиби M дода шудааст. Суммаи элементҳои ҳар як диагонали онро, ки ба диагонали ғайриасосӣ параллел аст (аз диагонали якэлементаи A<sub>1,1</sub> сар карда), ёбед.`
	m.tj[84] = `Матритсаи квадратии A бо тартиби M дода шудааст. Қимати миёнаи арифметикии элементҳои ҳар як диагонали онро, ки ба диагонали асосӣ параллел аст (аз диагонали якэлементаи A<sub>1,M</sub> сар карда), ёбед.`
	m.tj[85] = `Матритсаи квадратии A бо тартиби M дода шудааст. Қимати миёнаи арифметикии элементҳои ҳар як диагонали онро, ки ба диагонали ғайриасосӣ параллел аст (аз диагонали якэлементаи A<sub>1,1</sub> сар карда), ёбед.`
	m.tj[86] = `Матритсаи квадратии A бо тартиби M дода шудааст. Элементи хурдтаринро барои ҳар як диагонали он, ки ба диагоали асосӣ параллел аст (аз диагонали якэлементаи A<sub>1,M</sub> сар карда), ёбед.`
	m.tj[87] = `Матритсаи квадратии A бо тартиби M дода шудааст. Элементи калонтаринро барои ҳар як диагонали он, ки ба диагонали ғайриасосӣ праллел аст (аз диагонали якэлементаи A<sub>1,1</sub> сар карда), ёбед.`
	m.tj[88] = `Матритсаи квадратии тартиби M дода шудааст. Элементҳои матритсаро, ки дар поёни диагонали асосӣ ҷойгиранд, нулӣ гардонед. Оператори шартиро истифода набаред.`
	m.tj[89] = `Матритсаи квадратии тартиби M дода шудааст. Элементҳои матритсаро, ки дар болои диагонаи ғайриасосӣ ҷойгиранд, нулӣ гардонед. Оператори шартиро истифода набаред.`
	m.tj[90] = `Матритсаи квадратии тартиби M дода шудааст. Элементҳои матритсаро, ки дар диагонали ғайриасосӣ ва поён аз он ҷойгиранд, нулӣ гардонед. Оператори шартиро истифода набаред.`
	m.tj[91] = `Матритсаи квадратии тартиби M дода шудааст. Элементҳои матритсаро, ки дар диагонали асосӣ ва боло аз он ҷойгиранд, нулӣ гардонед. Оператори шартиро истифода набаред.`
	m.tj[92] = `Матритсаи квадратии тартиби M дода шудааст. Элементҳои матритсаро, ки дар як вақт ҳам боло аз диагонали асосӣ ва ҳам боло аз диагонали ғайриасосӣ ҷойгиранд, нулӣ гардонед. Оператори шартиро истифода набаред.`
	m.tj[93] = `Матритсаи квадратии тартиби M дода шудааст. Элементҳои матритсаро, ки дар як вақт дар болои диагонали асосӣ ва дар поёни диагонали ғайриасосӣ ҷойгиранд, нулӣ гардонед. Оператори шартиро истифода набаред.`
	m.tj[94] = `Матритсаи квадратии тартиби M дода шудааст. Элементҳои матритсаро, ки дар як вақт дар поёни диагонали асосӣ (ин диагоналро дар бар гирифта) ва дар болои диагонали ғайриасосӣ (ҳамчунин ин диагоналро дар бар гирифта) ҷойгиранд, нулӣ гардонед. Оператори шартиро истифода набаред.`
	m.tj[95] = `Матритсаи квадратии тартиби M дода шудааст. Элементҳои матритсаро, ки дар як вақт дар поёни диагонали асосӣ (ин диагоналро дар бар гирифта) ва дар поёни диагонали ғайриасосӣ (ҳамчунин ин диагоналро дар бар гирифта) ҷойгиранд, нулӣ гардонед. Оператори шартиро истифода набаред.`
	m.tj[96] = `Матритсаи квадратии A бо тартиби M дода шудааст. Элементҳои онро нисбат ба диагонали асосӣ ба таври оина тасвир кунед (дар ин ҳангом элементҳои диагонали асосӣ дар ҷойи пешина меистанд, элементи A<sub>1,2</sub> бо элементи A<sub>2,1</sub> ҷой иваз мекунад, элементи A<sub>1,3</sub> — бо A<sub>3,1</sub> ва ғ.). Матритсаи ёридиҳандаро истифода набаред.`
	m.tj[97] = `Матритсаи квадратии A бо тартиби M дода шудаст. Элементҳои онро нисбат ба диагонали ғайриасосӣ ба таври оина тасвир кунед (дар ин ҳангом элементҳои диагонали ғайриасосӣ дар ҷойи пешина меистанд, элементи A<sub>1,1</sub> бо элементи A<sub>M,M</sub> ҷой иваз мекунад, элементи A<sub>1,2</sub> — бо A<sub>M-1,M</sub> ва ғ.). Матритсаи ёридиҳандаро истифода набаред.`
	m.tj[98] = `Матритсаи квадратии A бо тартиби M дода шудааст. Онро ба кунҷи 180° (дар ин ҳангом элементи A<sub>1,1</sub> бо элементи A<sub>M,M</sub> ҷой иваз мекунад, элементи A<sub>1,2</sub> — бо A<sub>M,M-1</sub> ва ғ.) тоб диҳед. Матритсаи ёридиҳандаро истифода набаред.`
	m.tj[99] = `Матритсаи квадратии A бо тартиби M дода шудааст. Онро ба кунҷи 90° ба самти мусбӣ, яъне муқобили ақрабаки соат (дар ин ҳангом элементи A<sub>1,1</sub> ба элементи A<sub>M,1</sub> мекӯчад, элементи A<sub>M,1</sub> — ба A<sub>M,M</sub> ва ғ.) тоб диҳед. Матритсаи ёридиҳандаро истифода набаред.`
	m.tj[100] = `Матритсаи квадратии A бо тартиби M дода шудааст. Онро ба кунҷи 90° ба самти манфӣ, яъне аз рӯи ақрабаки соат (дар ин ҳангом элементи A<sub>1,1</sub> ба элементи A<sub>1,M</sub> мекӯчад, элементи A<sub>1,M</sub> — ба A<sub>M,M</sub> ва ғ.) тоб диҳед. Матритсаи ёридиҳандаро истифода набаред.`
}

func (m *mmatrix) makeRu() {
	m.ru = make([]string, m.count)
	m.ru[1] = `Даны целые положительные числа&nbsp;<i>M</i> и&nbsp;<i>N</i>. Сформировать целочисленную матрицу размера <i>M</i>&nbsp;&#215;&nbsp;<i>N</i>, у которой все элементы <i>I</i>-й&nbsp;строки имеют значение&nbsp;10&#183;<i>I</i> (<i>I</i>&nbsp;=&nbsp;1,&nbsp;&#8230;,&nbsp;<i>M</i>).`
	m.ru[2] = `Даны целые положительные числа&nbsp;<i>M</i> и&nbsp;<i>N</i>. Сформировать целочисленную матрицу размера <i>M</i>&nbsp;&#215;&nbsp;<i>N</i>, у которой все элементы <i>J</i>-го&nbsp;столбца имеют значение&nbsp;5&#183;<i>J</i> (<i>J</i>&nbsp;=&nbsp;1,&nbsp;&#8230;,&nbsp;<i>N</i>).`
	m.ru[3] = `Даны целые положительные числа&nbsp;<i>M</i>, <i>N</i> и набор из <i>M</i>&nbsp;чисел. Сформировать матрицу размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>, у которой в каждом столбце содержатся все числа из исходного набора (в том же порядке).`
	m.ru[4] = `Даны целые положительные числа&nbsp;<i>M</i>, <i>N</i> и набор из <i>N</i>&nbsp;чисел. Сформировать матрицу размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>, у которой в каждой строке содержатся все числа из исходного набора (в том же порядке).`
	m.ru[5] = `Даны целые положительные числа&nbsp;<i>M</i>, <i>N</i>, число&nbsp;<i>D</i> и набор из <i>M</i>&nbsp;чисел. Сформировать матрицу размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>, у которой первый столбец совпадает с исходным набором чисел, а элементы каждого следующего столбца равны сумме соответствующего элемента предыдущего столбца и числа&nbsp;<i>D</i> (в результате каждая строка матрицы будет содержать элементы <i>арифметической прогрессии</i>).`
	m.ru[6] = `Даны целые положительные числа&nbsp;<i>M</i>, <i>N</i>, число&nbsp;<i>D</i> и набор из <i>N</i>&nbsp;чисел. Сформировать матрицу размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>, у которой первая строка совпадает с исходным набором чисел, а элементы каждой следующей строки равны соответствующему элементу предыдущей строки, умноженному на&nbsp;<i>D</i> (в результате каждый столбец матрицы будет содержать элементы <i>геометрической прогрессии</i>).`
	m.ru[7] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i> и целое число&nbsp;<i>K</i> (1&nbsp;&#8804;&nbsp;<i>K</i>&nbsp;&#8804;&nbsp;<i>M</i>). Вывести элементы <i>K</i>-й&nbsp;строки данной матрицы.`
	m.ru[8] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i> и целое число&nbsp;<i>K</i> (1&nbsp;&#8804;&nbsp;<i>K</i>&nbsp;&#8804;&nbsp;<i>N</i>). Вывести элементы <i>K</i>-го&nbsp;столбца данной матрицы.`
	m.ru[9] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Вывести ее элементы, расположенные в строках с четными номерами (2, 4,&nbsp;&#8230;). Вывод элементов производить по строкам, условный оператор не использовать.`
	m.ru[10] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Вывести ее элементы, расположенные в столбцах с нечетными номерами (1, 3,&nbsp;&#8230;). Вывод элементов производить по столбцам, условный оператор не использовать.`
	m.ru[11] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Вывести ее элементы в следующем порядке: первая строка слева направо, вторая строка справа налево, третья строка слева направо, четвертая строка справа налево и&nbsp;т.&nbsp;д.`
	m.ru[12] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Вывести ее элементы в следующем порядке: первый столбец сверху вниз, второй столбец снизу вверх, третий столбец сверху вниз, четвертый столбец снизу вверх и&nbsp;т.&nbsp;д.`
	m.ru[13] = `Дана квадратная матрица&nbsp;<i>A</i> порядка&nbsp;<i>M</i>. Начиная с элемента&nbsp;<i>A</i><sub>1,1</sub>, вывести ее элементы следующим образом (&#171;<i>уголками</i>&#187;): все элементы первой строки; элементы последнего столбца, кроме первого (уже выведенного) элемента; оставшиеся элементы второй строки; оставшиеся элементы предпоследнего столбца и&nbsp;т.&nbsp;д.; последним выводится элемент&nbsp;<i>A</i><sub><i>M</i>,1</sub>.`
	m.ru[14] = `Дана квадратная матрица&nbsp;<i>A</i> порядка&nbsp;<i>M</i>. Начиная с элемента&nbsp;<i>A</i><sub>1,1</sub>, вывести ее элементы следующим образом (&#171;<i>уголками</i>&#187;): все элементы первого столбца; элементы последней строки, кроме первого (уже выведенного) элемента; оставшиеся элементы второго столбца; оставшиеся элементы предпоследней строки и&nbsp;т.&nbsp;д.; последним выводится элемент&nbsp;<i>A</i><sub>1,<i>M</i></sub>.`
	m.ru[15] = `Дана квадратная матрица&nbsp;<i>A</i> порядка&nbsp;<i>M</i> (<i>M</i> &#8212; нечетное число). Начиная с элемента&nbsp;<i>A</i><sub>1,1</sub> и перемещаясь по часовой стрелке, вывести все ее элементы <i>по спирали</i>: первая строка, последний столбец, последняя строка в обратном порядке, первый столбец в обратном порядке, оставшиеся элементы второй строки и&nbsp;т.&nbsp;д.; последним выводится центральный элемент матрицы.`
	m.ru[16] = `Дана квадратная матрица&nbsp;<i>A</i> порядка&nbsp;<i>M</i> (<i>M</i> &#8212; нечетное число). Начиная с элемента&nbsp;<i>A</i><sub>1,1</sub> и перемещаясь против часовой стрелки, вывести все ее элементы <i>по спирали</i>: первый столбец, последняя строка, последний столбец в обратном порядке, первая строка в обратном порядке, оставшиеся элементы второго столбца и&nbsp;т.&nbsp;д.; последним выводится центральный элемент матрицы.`
	m.ru[17] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i> и целое число&nbsp;<i>K</i> (1&nbsp;&#8804;&nbsp;<i>K</i>&nbsp;&#8804;&nbsp;<i>M</i>). Найти сумму и произведение элементов <i>K</i>-й&nbsp;строки данной матрицы.`
	m.ru[18] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i> и целое число&nbsp;<i>K</i> (1&nbsp;&#8804;&nbsp;<i>K</i>&nbsp;&#8804;&nbsp;<i>N</i>). Найти сумму и произведение элементов <i>K</i>-го&nbsp;столбца данной матрицы.`
	m.ru[19] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Для каждой строки матрицы найти сумму ее элементов.`
	m.ru[20] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Для каждого столбца матрицы найти произведение его элементов.`
	m.ru[21] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Для каждой строки матрицы с нечетным номером (1,&nbsp;3,&nbsp;&#8230;) найти среднее арифметическое ее элементов. Условный оператор не использовать.`
	m.ru[22] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Для каждого столбца матрицы с четным номером (2,&nbsp;4,&nbsp;&#8230;) найти сумму его элементов. Условный оператор не использовать.`
	m.ru[23] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. В каждой строке матрицы найти минимальный элемент.`
	m.ru[24] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. В каждом столбце матрицы найти максимальный элемент.`
	m.ru[25] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Найти номер ее строки с наибольшей суммой элементов и вывести данный номер, а также значение наибольшей суммы.`
	m.ru[26] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Найти номер ее столбца с наименьшим произведением элементов и вывести данный номер, а также значение наименьшего произведения.`
	m.ru[27] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Найти максимальный среди минимальных элементов ее строк.`
	m.ru[28] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Найти минимальный среди максимальных элементов ее столбцов.`
	m.ru[29] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. В каждой ее строке найти количество элементов, меньших среднего арифметического всех элементов этой строки.`
	m.ru[30] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. В каждом ее столбце найти количество элементов, больших среднего арифметического всех элементов этого столбца.`
	m.ru[31] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Найти номера строки и столбца для элемента матрицы, наиболее близкого к среднему значению всех ее элементов.`
	m.ru[32] = `Дана целочисленная матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Найти номер первой из ее строк, содержащих равное количество положительных и отрицательных элементов (нулевые элементы матрицы не учитываются). Если таких строк нет, то вывести&nbsp;0.`
	m.ru[33] = `Дана целочисленная матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Найти номер последнего из ее столбцов, содержащих равное количество положительных и отрицательных элементов (нулевые элементы матрицы не учитываются). Если таких столбцов нет, то вывести&nbsp;0.`
	m.ru[34] = `Дана целочисленная матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Найти номер последней из ее строк, содержащих только четные числа. Если таких строк нет, то вывести&nbsp;0.`
	m.ru[35] = `Дана целочисленная матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Найти номер первого из ее столбцов, содержащих только нечетные числа. Если таких столбцов нет, то вывести&nbsp;0.`
	m.ru[36] = `Дана целочисленная матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>, элементы которой могут принимать значения от&nbsp;0 до&nbsp;100. Различные строки матрицы назовем <i>похожими</i>, если совпадают множества чисел, встречающихся в этих строках. Найти количество строк, похожих на первую строку данной матрицы.`
	m.ru[37] = `Дана целочисленная матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>, элементы которой могут принимать значения от&nbsp;0 до&nbsp;100. Различные столбцы матрицы назовем <i>похожими</i>, если совпадают множества чисел, встречающихся в этих столбцах. Найти количество столбцов, похожих на последний столбец данной матрицы.`
	m.ru[38] = `Дана целочисленная матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Найти количество ее строк, все элементы которых различны.`
	m.ru[39] = `Дана целочисленная матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Найти количество ее столбцов, все элементы которых различны.`
	m.ru[40] = `Дана целочисленная матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Найти номер последней из ее строк, содержащих максимальное количество одинаковых элементов.`
	m.ru[41] = `Дана целочисленная матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Найти номер первого из ее столбцов, содержащих максимальное количество одинаковых элементов.`
	m.ru[42] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Найти количество ее строк, элементы которых упорядочены по возрастанию.`
	m.ru[43] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Найти количество ее столбцов, элементы которых упорядочены по убыванию.`
	m.ru[44] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Найти минимальный среди элементов тех строк, которые упорядочены либо по возрастанию, либо по убыванию. Если упорядоченные строки в матрице отсутствуют, то вывести&nbsp;0.`
	m.ru[45] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Найти максимальный среди элементов тех столбцов, которые упорядочены либо по возрастанию, либо по убыванию. Если упорядоченные столбцы в матрице отсутствуют, то вывести&nbsp;0.`
	m.ru[46] = `Дана целочисленная матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Найти элемент, являющийся максимальным в своей строке и минимальным в своем столбце. Если такой элемент отсутствует, то вывести&nbsp;0.`
	m.ru[47] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i> и целые числа&nbsp;<i>K</i><sub>1</sub> и&nbsp;<i>K</i><sub>2</sub> (1&nbsp;&#8804;&nbsp;<i>K</i><sub>1</sub>&nbsp;&lt;&nbsp;<i>K</i><sub>2</sub>&nbsp;&#8804;&nbsp;<i>M</i>). Поменять местами строки матрицы с номерами&nbsp;<i>K</i><sub>1</sub> и&nbsp;<i>K</i><sub>2</sub>.`
	m.ru[48] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i> и целые числа&nbsp;<i>K</i><sub>1</sub> и&nbsp;<i>K</i><sub>2</sub> (1&nbsp;&#8804;&nbsp;<i>K</i><sub>1</sub>&nbsp;&lt;&nbsp;<i>K</i><sub>2</sub>&nbsp;&#8804;&nbsp;<i>N</i>). Поменять местами столбцы матрицы с номерами&nbsp;<i>K</i><sub>1</sub> и&nbsp;<i>K</i><sub>2</sub>.`
	m.ru[49] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Преобразовать матрицу, поменяв местами минимальный и максимальный элемент в каждой строке.`
	m.ru[50] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Преобразовать матрицу, поменяв местами минимальный и максимальный элемент в каждом столбце.`
	m.ru[51] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Поменять местами строки, содержащие минимальный и максимальный элементы матрицы.`
	m.ru[52] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Поменять местами столбцы, содержащие минимальный и максимальный элементы матрицы.`
	m.ru[53] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Поменять местами столбец с номером&nbsp;1 и последний из столбцов, содержащих только положительные элементы. Если требуемых столбцов нет, то вывести матрицу без изменений.`
	m.ru[54] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Поменять местами столбец с номером&nbsp;<i>N</i> и первый из столбцов, содержащих только отрицательные элементы. Если требуемых столбцов нет, то вывести матрицу без изменений.`
	m.ru[55] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i> (<i>M</i> &#8212; четное число). Поменять местами верхнюю и нижнюю половины матрицы.`
	m.ru[56] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i> (<i>N</i> &#8212; четное число). Поменять местами левую и правую половины матрицы.`
	m.ru[57] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i> (<i>M</i> и&nbsp;<i>N</i> &#8212; четные числа). Поменять местами левую верхнюю и правую нижнюю четверти матрицы.`
	m.ru[58] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i> (<i>M</i> и&nbsp;<i>N</i> &#8212; четные числа). Поменять местами левую нижнюю и правую верхнюю четверти матрицы.`
	m.ru[59] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Зеркально отразить ее элементы относительно горизонтальной оси симметрии матрицы (при этом поменяются местами строки с номерами&nbsp;1 и&nbsp;<i>M</i>, 2 и&nbsp;<i>M</i>&nbsp;&#8722;&nbsp;1 и т.&nbsp;д.).`
	m.ru[60] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Зеркально отразить ее элементы относительно вертикальной оси симметрии матрицы (при этом поменяются местами столбцы с номерами&nbsp;1 и&nbsp;<i>N</i>, 2 и&nbsp;<i>N</i>&nbsp;&#8722;&nbsp;1 и т.&nbsp;д.).`
	m.ru[61] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i> и целое число&nbsp;<i>K</i> (1&nbsp;&#8804;&nbsp;<i>K</i>&nbsp;&#8804;&nbsp;<i>M</i>). Удалить строку матрицы с номером&nbsp;<i>K</i>.`
	m.ru[62] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i> и целое число&nbsp;<i>K</i> (1&nbsp;&#8804;&nbsp;<i>K</i>&nbsp;&#8804;&nbsp;<i>N</i>). Удалить столбец матрицы с номером&nbsp;<i>K</i>.`
	m.ru[63] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Удалить строку, содержащую минимальный элемент матрицы.`
	m.ru[64] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Удалить столбец, содержащий максимальный элемент матрицы.`
	m.ru[65] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Удалить ее первый столбец, содержащий только положительные элементы. Если требуемых столбцов нет, то вывести матрицу без изменений.`
	m.ru[66] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Удалить ее последний столбец, содержащий только отрицательные элементы. Если требуемых столбцов нет, то вывести матрицу без изменений.`
	m.ru[67] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>, содержащая как положительные, так и отрицательные элементы. Удалить все ее столбцы, содержащие только положительные элементы. Если требуемых столбцов нет, то вывести матрицу без изменений.`
	m.ru[68] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i> и целое число&nbsp;<i>K</i> (1&nbsp;&#8804;&nbsp;<i>K</i>&nbsp;&#8804;&nbsp;<i>M</i>). Перед строкой матрицы с номером&nbsp;<i>K</i> вставить строку из нулей.`
	m.ru[69] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i> и целое число&nbsp;<i>K</i> (1&nbsp;&#8804;&nbsp;<i>K</i>&nbsp;&#8804;&nbsp;<i>N</i>). После столбца матрицы с номером&nbsp;<i>K</i> вставить столбец из единиц.`
	m.ru[70] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Продублировать строку матрицы, содержащую ее максимальный элемент.`
	m.ru[71] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Продублировать столбец матрицы, содержащий ее минимальный элемент.`
	m.ru[72] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Перед первым столбцом, содержащим только положительные элементы, вставить столбец из единиц. Если требуемых столбцов нет, то вывести матрицу без изменений.`
	m.ru[73] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. После последнего столбца, содержащего только отрицательные элементы, вставить столбец из нулей. Если требуемых столбцов нет, то вывести матрицу без изменений.`
	m.ru[74] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Элемент матрицы называется ее <i>локальным минимумом</i>, если он меньше всех окружающих его элементов. Заменить все локальные минимумы данной матрицы на нули. При решении допускается использовать вспомогательную матрицу.`
	m.ru[75] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Элемент матрицы называется ее <i>локальным максимумом</i>, если он больше всех окружающих его элементов. Поменять знак всех локальных максимумов данной матрицы на противоположный. При решении допускается использовать вспомогательную матрицу.`
	m.ru[76] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Упорядочить ее строки так, чтобы их первые элементы образовывали возрастающую последовательность.`
	m.ru[77] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Упорядочить ее столбцы так, чтобы их последние элементы образовывали убывающую последовательность.`
	m.ru[78] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Упорядочить ее строки так, чтобы их минимальные элементы образовывали убывающую последовательность.`
	m.ru[79] = `Дана матрица размера&nbsp;<i>M</i>&nbsp;&#215;&nbsp;<i>N</i>. Упорядочить ее столбцы так, чтобы их максимальные элементы образовывали возрастающую последовательность.`
	m.ru[80] = `Дана квадратная матрица&nbsp;<i>A</i> порядка&nbsp;<i>M</i>. Найти сумму элементов ее <i>главной диагонали</i>, т.&nbsp;е. диагонали, содержащей следующие элементы: <i>A</i><sub>1,1</sub>, &nbsp; &nbsp;<i>A</i><sub>2,2</sub>, &nbsp; &nbsp;<i>A</i><sub>3,3</sub>, &nbsp; &nbsp;&#8230;, &nbsp; &nbsp;<i>A</i><sub><i>M</i>,<i>M</i></sub>.`
	m.ru[81] = `Дана квадратная матрица&nbsp;<i>A</i> порядка&nbsp;<i>M</i>. Найти среднее арифметическое элементов ее <i>побочной диагонали</i>, т.&nbsp;е. диагонали, содержащей следующие элементы: <i>A</i><sub>1,<i>M</i></sub>, &nbsp; &nbsp;<i>A</i><sub>2,<i>M</i>&#8722;1</sub>, &nbsp; &nbsp;<i>A</i><sub>3,<i>M</i>&#8722;2</sub>, &nbsp; &nbsp;&#8230;, &nbsp; &nbsp;<i>A</i><sub><i>M</i>,1</sub>.`
	m.ru[82] = `Дана квадратная матрица&nbsp;<i>A</i> порядка&nbsp;<i>M</i>. Найти сумму элементов каждой ее диагонали, параллельной главной (начиная с одноэлементной диагонали&nbsp;<i>A</i><sub>1,<i>M</i></sub>).`
	m.ru[83] = `Дана квадратная матрица&nbsp;<i>A</i> порядка&nbsp;<i>M</i>. Найти сумму элементов каждой ее диагонали, параллельной побочной (начиная с одноэлементной диагонали&nbsp;<i>A</i><sub>1,1</sub>).`
	m.ru[84] = `Дана квадратная матрица&nbsp;<i>A</i> порядка&nbsp;<i>M</i>. Найти среднее арифметическое элементов каждой ее диагонали, параллельной главной (начиная с одноэлементной диагонали&nbsp;<i>A</i><sub>1,<i>M</i></sub>).`
	m.ru[85] = `Дана квадратная матрица&nbsp;<i>A</i> порядка&nbsp;<i>M</i>. Найти среднее арифметическое элементов каждой ее диагонали, параллельной побочной (начиная с одноэлементной диагонали&nbsp;<i>A</i><sub>1,1</sub>).`
	m.ru[86] = `Дана квадратная матрица&nbsp;<i>A</i> порядка&nbsp;<i>M</i>. Найти минимальный элемент для каждой ее диагонали, параллельной главной (начиная с одноэлементной диагонали&nbsp;<i>A</i><sub>1,<i>M</i></sub>).`
	m.ru[87] = `Дана квадратная матрица&nbsp;<i>A</i> порядка&nbsp;<i>M</i>. Найти максимальный элемент для каждой ее диагонали, параллельной побочной (начиная с одноэлементной диагонали&nbsp;<i>A</i><sub>1,1</sub>).`
	m.ru[88] = `Дана квадратная матрица порядка&nbsp;<i>M</i>. Обнулить элементы матрицы, лежащие ниже главной диагонали. Условный оператор не использовать.`
	m.ru[89] = `Дана квадратная матрица порядка&nbsp;<i>M</i>. Обнулить элементы матрицы, лежащие выше побочной диагонали. Условный оператор не использовать.`
	m.ru[90] = `Дана квадратная матрица порядка&nbsp;<i>M</i>. Обнулить элементы матрицы, лежащие на побочной диагонали и ниже нее. Условный оператор не использовать.`
	m.ru[91] = `Дана квадратная матрица порядка&nbsp;<i>M</i>. Обнулить элементы матрицы, лежащие на главной диагонали и выше нее. Условный оператор не использовать.`
	m.ru[92] = `Дана квадратная матрица порядка&nbsp;<i>M</i>. Обнулить элементы матрицы, лежащие одновременно выше главной диагонали и выше побочной диагонали. Условный оператор не использовать.`
	m.ru[93] = `Дана квадратная матрица порядка&nbsp;<i>M</i>. Обнулить элементы матрицы, лежащие одновременно выше главной диагонали и ниже побочной диагонали. Условный оператор не использовать.`
	m.ru[94] = `Дана квадратная матрица порядка&nbsp;<i>M</i>. Обнулить элементы матрицы, лежащие одновременно ниже главной диагонали (включая эту диагональ) и выше побочной диагонали (также включая эту диагональ). Условный оператор не использовать.`
	m.ru[95] = `Дана квадратная матрица порядка&nbsp;<i>M</i>. Обнулить элементы матрицы, лежащие одновременно ниже главной диагонали (включая эту диагональ) и ниже побочной диагонали (также включая эту диагональ). Условный оператор не использовать.`
	m.ru[96] = `Дана квадратная матрица&nbsp;<i>A</i> порядка&nbsp;<i>M</i>. Зеркально отразить ее элементы относительно главной диагонали (при этом элементы главной диагонали останутся на прежнем месте, элемент&nbsp;<i>A</i><sub>1,2</sub> поменяется местами с&nbsp;<i>A</i><sub>2,1</sub>, элемент&nbsp;<i>A</i><sub>1,3</sub> &#8212; с&nbsp;<i>A</i><sub>3,1</sub> и т.&nbsp;д.). Вспомогательную матрицу не использовать.`
	m.ru[97] = `Дана квадратная матрица&nbsp;<i>A</i> порядка&nbsp;<i>M</i>. Зеркально отразить ее элементы относительно побочной диагонали (при этом элементы побочной диагонали останутся на прежнем месте, элемент&nbsp;<i>A</i><sub>1,1</sub> поменяется местами с&nbsp;<i>A</i><sub><i>M</i>,<i>M</i></sub>, элемент&nbsp;<i>A</i><sub>1,2</sub> &#8212; с&nbsp;<i>A</i><sub><i>M</i>&#8722;1,<i>M</i></sub> и т.&nbsp;д.). Вспомогательную матрицу не использовать.`
	m.ru[98] = `Дана квадратная матрица&nbsp;<i>A</i> порядка&nbsp;<i>M</i>. Повернуть ее на угол 180&#176; (при этом элемент&nbsp;<i>A</i><sub>1,1</sub> поменяется местами с&nbsp;<i>A</i><sub><i>M</i>,<i>M</i></sub>, элемент&nbsp;<i>A</i><sub>1,2</sub> &#8212; с&nbsp;<i>A</i><sub><i>M</i>,<i>M</i>&#8722;1</sub> и т.&nbsp;д.). Вспомогательную матрицу не использовать.`
	m.ru[99] = `Дана квадратная матрица&nbsp;<i>A</i> порядка&nbsp;<i>M</i>. Повернуть ее на угол 90&#176; в положительном направлении, т.&nbsp;е. против часовой стрелки (при этом элемент&nbsp;<i>A</i><sub>1,1</sub> перейдет в&nbsp;<i>A</i><sub><i>M</i>,1</sub>, элемент&nbsp;<i>A</i><sub><i>M</i>,1</sub> &#8212; в&nbsp;<i>A</i><sub><i>M</i>,<i>M</i></sub> и т.&nbsp;д.). Вспомогательную матрицу не использовать.`
	m.ru[100] = `Дана квадратная матрица&nbsp;<i>A</i> порядка&nbsp;<i>M</i>. Повернуть ее на угол 90&#176; в отрицательном направлении, т.&nbsp;е. по часовой стрелке (при этом элемент&nbsp;<i>A</i><sub>1,1</sub> перейдет в&nbsp;<i>A</i><sub>1,<i>M</i></sub>, элемент&nbsp;<i>A</i><sub>1,<i>M</i></sub> &#8212; в&nbsp;<i>A</i><sub><i>M</i>,<i>M</i></sub> и т.&nbsp;д.). Вспомогательную матрицу не использовать.`
}
