package task

type ffile struct {
	count int
	name  string
	en    []string
	tj    []string
	ru    []string
}

func NewFileTask() Task {
	f := &ffile{
		count: 91,
		name:  "File",
	}
	f.makeEn()
	f.makeTj()
	f.makeRu()
	return f
}

func (f *ffile) Count() int   { return f.count }
func (f *ffile) Name() string { return f.name }
func (f *ffile) En() []string { return f.en }
func (f *ffile) Tj() []string { return f.tj }
func (f *ffile) Ru() []string { return f.ru }

func (f *ffile) makeEn() {
	f.en = make([]string, f.count)
	f.en[1] = `A string&nbsp;<i>S</i> is given. If the string&nbsp;<i>S</i> is an admissible name of file then create an empty file called&nbsp;<i>S</i> and output true. If a file with the name&nbsp;<i>S</i> cannot be created then output false.`
	f.en[2] = `A file name and an integer&nbsp;<i>N</i> (&gt;&nbsp;1) are given. Create a file of integers with the given name and write <i>N</i>&nbsp;first positive even numbers (2, 4,&nbsp;&#8230;) to this file.`
	f.en[3] = `A file name and two real numbers&nbsp;<i>A</i>, <i>D</i> are given. Create a file of real numbers with the given name and write 10&nbsp;first terms of an <i>arithmetic sequence</i> with the first term&nbsp;<i>A</i> and the common difference&nbsp;<i>D</i> (<i>A</i>, <i>A</i>&nbsp;+&nbsp;<i>D</i>, <i>A</i>&nbsp;+&nbsp;2&#183;<i>D</i>,&nbsp;&#8230;, <i>A</i>&nbsp;+&nbsp;9&#183;<i>D</i>) to this file.`
	f.en[4] = `Four file names are given. Find the amount of files with the given names that are located in the working directory.`
	f.en[5] = `A name of file of integers is given. Find the amount of the file components. If a file with the given name does not exist then output&nbsp;&#8722;1.`
	f.en[6] = `An integer&nbsp;<i>K</i> and a file of nonnegative integers are given. Output the file component with the order number&nbsp;<i>K</i> (file components are numbered beginning with&nbsp;1). If the file does not contain a component with the required number then output&nbsp;&#8722;1.`
	f.en[7] = `Given a file of integers that contains at least four components, output its components with the order numbers&nbsp;1, 2, <i>N</i>&#8722;1, <i>N</i>, where&nbsp;<i>N</i> is the amount of the file components.`
	f.en[8] = `Two names of files of real numbers are given. It is known that the first file exists and is nonempty whereas the second file is absent in the working directory. Create the absent file and write the first and the last components of the existing file (in that order) to the file that has been created.`
	f.en[9] = `Two names of files of real numbers are given. It is known that one of these files exists and is nonempty whereas the other file is absent in the working directory. Create the absent file and write the last and the first components of the existing file (in that order) to the file that has been created.`
	f.en[10] = `A file of integers is given. Create a new file that contains all components of the given file in inverse order.`
	f.en[11] = `A file of real numbers is given. Create two new files; the first resulting file must contain the given file components with odd order numbers (1,&nbsp;3,&nbsp;&#8230;), the second resulting file must contain the given file components with even order numbers (2,&nbsp;4,&nbsp;&#8230;).`
	f.en[12] = `A file of integers is given. Create two new files; the first resulting file must contain the given file components whose values are even numbers, the second resulting file must contain the given file components whose values are odd numbers. If the given file does not contain odd or even numbers then the corresponding resulting file must be empty.`
	f.en[13] = `A file of integers is given. Create two new files; the first resulting file must contain the given file components (in inverse order) whose values are positive numbers, the second resulting file must contain the given file components (in inverse order too) whose values are negative numbers. If the given file does not contain positive or negative numbers then the corresponding resulting file must be empty.`
	f.en[14] = `A file of real numbers is given. Find the average of its components.`
	f.en[15] = `A file of real numbers is given. Find the sum of its components with even order numbers.`
	f.en[16] = `A file of integers is given. Find the amount of series of equal numbers that are contained in the file (a <i>series of equal numbers</i> is defined as a set of successive file components with equal values). For instance, if the file contains components with values 1,&nbsp;5, 5, 5, 4, 4,&nbsp;5 then the number&nbsp;4 must be output.`
	f.en[17] = `A file of integers is given. Create a new file of integers that contains lengths of all series of equal numbers from the given file (a <i>series of equal</i> <i>numbers</i> is defined as a set of successive file components with equal values; the amount of these components is called the <i>length of series</i>). For instance, if the given file contains components with values 1,&nbsp;5, 5, 5, 4, 4,&nbsp;5 then the resulting file must contain the following integers: 1,&nbsp;3, 2,&nbsp;1.`
	f.en[18] = `A file of real numbers is given. Find its first local minimum (a file component is called the <i>local minimum</i> if it is smaller than its neighbors).`
	f.en[19] = `A file of real numbers is given. Find its last local maximum (a file component is called the <i>local maximum</i> if it is greater than its neighbors).`
	f.en[20] = `A file of real numbers is given. Find the total amount of its <i>local extremums</i>, that is, its local maximums and local minimums (see the <i>local minimum</i> and <i>local maximum</i> definitions in File18 and File19 respectively).`
	f.en[21] = `A file of real numbers is given. Create a file of integers that contains order numbers of all local maximums of the given file in ascending order (see the <i>local maximum</i> definition in File19).`
	f.en[22] = `A file of real numbers is given. Create a file of integers that contains order numbers of all local extremums of the given file in descending order (see the <i>local extremum</i> definition in File20).`
	f.en[23] = `A file of real numbers is given. Create a file of integers that contains lengths of all sets of successive file components whose values are in descending order. For instance, if the given file contains components with values 1.7, 4.5, 3.4, 2.2, 8.5,&nbsp;1.2 then the resulting file must contain the following integers: 3,&nbsp;2.`
	f.en[24] = `A file of real numbers is given. Create a file of integers that contains lengths of all sets of successive file components whose values are in ascending or descending order. For instance, if the given file contains components with values 1.7, 4.5, 3.4, 2.2, 8.5,&nbsp;1.2 then the resulting file must contain the following integers: 2, 3, 2,&nbsp;2.`
	f.en[25] = `Given a file of real numbers, replace the values of all file components with their squares.`
	f.en[26] = `Given a file of real numbers, exchange values of its minimal and maximal component.`
	f.en[27] = `Given a file of integers with components&nbsp;<i>A</i><sub>1</sub>, <i>A</i><sub>2</sub>,&nbsp;&#8230;, <i>A</i><sub><i>N</i></sub> (<i>N</i> is the amount of the file components), change the order of the file components as follows: <i>A</i><sub>1</sub>, &nbsp; &nbsp;<i>A</i><sub><i>N</i></sub>, &nbsp; &nbsp;<i>A</i><sub>2</sub>, &nbsp; &nbsp;<i>A</i><sub><i>N</i>&#8722;1</sub>, &nbsp; &nbsp;<i>A</i><sub>3</sub>, &nbsp; &nbsp;&#8230;&nbsp;.`
	f.en[28] = `Given a file of real numbers, replace each file component (except for the first and last one) with the average of this component and its neighbors.`
	f.en[29] = `Given a file of integers that contains more than 50&nbsp;components, reduce the size of file to 50&nbsp;components by means of removing last components.`
	f.en[30] = `Given a file of integers that contains an even number of components, remove the second half of the file components.`
	f.en[31] = `Given a file of integers that contains more than 50&nbsp;components, reduce the size of file to 50&nbsp;components by means of removing first components.`
	f.en[32] = `Given a file of integers that contains an even number of components, remove the first half of the file components.`
	f.en[33] = `Given a file of integers, remove file components with even order numbers (2, 4,&nbsp;&#8230;).`
	f.en[34] = `Given a file of integers, remove file components with negative values.`
	f.en[35] = `Given a file of integers that contains less than 50&nbsp;components, increase the size of file up to 50&nbsp;components by means of inserting zero components to the beginning of the file.`
	f.en[36] = `Given a file of integers, write all its components in the same order to the end of this file (as a result, the size of file will be doubled).`
	f.en[37] = `Given a file of integers, write all its components in inverse order to the end of this file (as a result, the size of file will be doubled).`
	f.en[38] = `Given a file of integers, double occurrences of file components with odd order numbers.`
	f.en[39] = `Given a file of integers, double occurrences of file components whose values are in the range&nbsp;5 to&nbsp;10.`
	f.en[40] = `Given a file of integers, replace each file component, whose order number is an even number, with two zero components.`
	f.en[41] = `Given a file of integers, replace each file component, whose value is a positive number, with three zero components.`
	f.en[42] = `Given two untyped files, exchange their contents.`
	f.en[43] = `Given an untyped file and a string&nbsp;<i>S</i>, create the file copy called&nbsp;<i>S</i>.`
	f.en[44] = `Given three untyped files of different size, replace the contents of the longest file with the contents of the shortest one.`
	f.en[45] = `Given three untyped files of different size, replace the contents of the shortest file with the contents of the longest one.`
	f.en[46] = `A string&nbsp;<i>S</i><sub>0</sub>, an integer&nbsp;<i>N</i> (&#8804;&nbsp;4), and <i>N</i>&nbsp;files called <i>S</i><sub>1</sub>,&nbsp;&#8230;, <i>S</i><sub><i>N</i></sub> are given. Components of all given files have the identical type. Combine the contents of the given files (in the same order) in a new file called&nbsp;<i>S</i><sub>0</sub>.`
	f.en[47] = `Given two files whose components have the identical type, add the initial contents of the second file to the end of the first file and the initial contents of the first file to the end of the second file.`
	f.en[48] = `Three files of integers called&nbsp;<i>S</i><sub><i>A</i></sub>, <i>S</i><sub><i>B</i></sub>, <i>S</i><sub><i>C</i></sub> and a string&nbsp;<i>S</i><sub><i>D</i></sub> are given. All given files are of the same size. Create a new file called&nbsp;<i>S</i><sub><i>D</i></sub>; this file must contain triples of components of the given files as follows: <i>A</i><sub>1</sub>, &nbsp; &nbsp;<i>B</i><sub>1</sub>, &nbsp; &nbsp;<i>C</i><sub>1</sub>, &nbsp; &nbsp;<i>A</i><sub>2</sub>, &nbsp; &nbsp;<i>B</i><sub>2</sub>, &nbsp; &nbsp;<i>C</i><sub>2</sub>, &nbsp; &nbsp;&#8230;&nbsp;.`
	f.en[49] = `Four files of integers called&nbsp;<i>S</i><sub><i>A</i></sub>, <i>S</i><sub><i>B</i></sub>, <i>S</i><sub><i>C</i></sub>, <i>S</i><sub><i>D</i></sub> and a string&nbsp;<i>S</i><sub><i>E</i></sub> are given. The given files are of different size. Create a new file called&nbsp;<i>S</i><sub><i>E</i></sub>; this file must contain quadruples of components of the given files as follows: <i>A</i><sub>1</sub>, &nbsp; &nbsp;<i>B</i><sub>1</sub>, &nbsp; &nbsp;<i>C</i><sub>1</sub>, &nbsp; &nbsp;<i>D</i><sub>1</sub>, &nbsp; &nbsp;<i>A</i><sub>2</sub>, &nbsp; &nbsp;<i>B</i><sub>2</sub>, &nbsp; &nbsp;<i>C</i><sub>2</sub>, &nbsp; &nbsp;<i>D</i><sub>2</sub>, &nbsp; &nbsp;&#8230;&nbsp;.Do not write &#34;superfluous&#34; components of longer files to the resulting file.`
	f.en[50] = `Two files of real numbers called&nbsp;<i>S</i><sub>1</sub>, <i>S</i><sub>2</sub> and a string&nbsp;<i>S</i><sub>3</sub> are given. Values of components of each given file are in ascending order. Create a new file called&nbsp;<i>S</i><sub>3</sub>; this file must contain all components of the given files in ascending order of their values.`
	f.en[51] = `Three files of real numbers called&nbsp;<i>S</i><sub>1</sub>, <i>S</i><sub>2</sub>, <i>S</i><sub>3</sub> and a string&nbsp;<i>S</i><sub>4</sub> are given. Values of components of each given file are in descending order. Create a new file called&nbsp;<i>S</i><sub>4</sub>; this file must contain all components of the given files in descending order of their values.`
	f.en[52] = `A string&nbsp;<i>S</i><sub>0</sub>, an integer&nbsp;<i>N</i> (&#8804;&nbsp;4), and <i>N</i>&nbsp;files of integers called <i>S</i><sub>1</sub>,&nbsp;&#8230;, <i>S</i><sub><i>N</i></sub> are given. Create a new file called&nbsp;<i>S</i><sub>0</sub>; this file (an <i>archival file</i>) must contain data of all given files in the following format: the number&nbsp;<i>N</i> (the first component of the archival file), the amounts of components of each given file (the next <i>N</i>&nbsp;components of the archival file), values of all components of the file&nbsp;<i>S</i><sub>1</sub> in the same order, values of all components of the file&nbsp;<i>S</i><sub>2</sub> in the same order, and so on.`
	f.en[53] = `A string&nbsp;<i>S</i>, an integer&nbsp;<i>N</i> (&gt;&nbsp;0) and an <i>archival file</i> are given. The archival file contains data of several files; the format of archival file is described in File52. Restore the data of the <i>N</i>-th file from the archival file and save it in the file called&nbsp;<i>S</i>. If the amount of files, which are contained in the archival file, is less than&nbsp;<i>N</i> then the resulting file&nbsp;<i>S</i> must be empty.`
	f.en[54] = `A string&nbsp;<i>S</i> and an <i>archival file</i> are given. The archival file contains data of several (no more than six) files; the format of archival file is described in File52. Find the average of all component values for each file, which is contained in the archival file. Save all obtained averages (as a real numbers) in a new file called&nbsp;<i>S</i>.`
	f.en[55] = `A string&nbsp;<i>S</i><sub>0</sub>, an integer&nbsp;<i>N</i> (&#8804;&nbsp;4), and <i>N</i>&nbsp;files of integers called <i>S</i><sub>1</sub>,&nbsp;&#8230;, <i>S</i><sub><i>N</i></sub> are given. Create a new file called&nbsp;<i>S</i><sub>0</sub>; this file (an <i>archival file</i>) must contain data of all given files in the following format: the amount of components of the file&nbsp;<i>S</i><sub>1</sub> and values of all its components in the same order; the amount of components of the file&nbsp;<i>S</i><sub>2</sub> and values of all its components in the same order;&nbsp;&#8230;; the amount of components of the file&nbsp;<i>S</i><sub><i>N</i></sub> and values of all its components in the same order.`
	f.en[56] = `A string&nbsp;<i>S</i>, an integer&nbsp;<i>N</i> (&gt;&nbsp;0) and an <i>archival file</i> are given. The archival file contains data of several files; the format of archival file is described in File55. Restore the data of the <i>N</i>-th file from the archival file and save it in the file called&nbsp;<i>S</i>. If the amount of files, which are contained in the archival file, is less than&nbsp;<i>N</i> then the resulting file&nbsp;<i>S</i> must be empty.`
	f.en[57] = `Two strings&nbsp;<i>S</i><sub>1</sub>, <i>S</i><sub>2</sub> and an <i>archival file</i> are given. The archival file contains data of several files; the format of archival file is described in File55. Create two new files called&nbsp;<i>S</i><sub>1</sub>, <i>S</i><sub>2</sub>; the first resulting file must contain first components of all files, which are contained in the archival file, the second resulting file must contain last components of all files, which are contained in the archival file.`
	f.en[58] = `Given a file of characters containing at least one blank character, remove its components that are located after the first blank character (including this blank character).`
	f.en[59] = `Given a file of characters containing at least one blank character, remove its components that are located after the last blank character (including this blank character).`
	f.en[60] = `Given a file of characters containing at least one blank character, remove its components that are located before the first blank character (including this blank character).`
	f.en[61] = `Given a file of characters containing at least one blank character, remove its components that are located before the last blank character (including this blank character).`
	f.en[62] = `Given a file of characters, rearrange file components in ascending order of their numeric values in the character set.`
	f.en[63] = `An integer&nbsp;<i>K</i> (&gt;&nbsp;0) and a file of strings are given. Create two new files; components of the first resulting file are strings that contain first <i>K</i>&nbsp;characters of each string of the given file; components of the second resulting file are <i>K</i>-th characters of each string of the given file. If the length of some string of the given file is less than&nbsp;<i>K</i> then the entire string and a blank character must be written to the first and second resulting file respectively.`
	f.en[64] = `Given a file of strings, write its components of the minimal length to a new file (in the same order).`
	f.en[65] = `Given a file of strings, write its components of the maximal length to a new file (in inverse order).`
	f.en[66] = `Given a file of strings, write all its components to a new file in <i>lexicographic order</i> (that is, in ascending order of the numeric values of their characters).`
	f.en[67] = `A file of strings is given. The file contains dates in the &#34;day/month/year&#34; format, the &#34;day&#34; and &#34;month&#34; fields contain two digits, the &#34;year&#34; field contains four digits (for example, &#34;16/04/2001&#34;). Create two new files and write integer values of days and months for each date from the given file to the first and second resulting file respectively (in the same order).`
	f.en[68] = `A file of strings is given; the file contains dates in the &#34;day/month/year&#34; format (see File67). Create two new files and write integer values of months and years for each date from the given file to the first and second resulting file respectively (in inverse order).`
	f.en[69] = `A file of strings is given; the file contains dates in the &#34;day/month/year&#34; format (see File67). Write its components that corresponds to summer dates to a new file (in the same order). If the given file does not contain required dates then the resulting file must be empty.`
	f.en[70] = `A file of strings is given; the file contains dates in the &#34;day/month/year&#34; format (see File67). Write its components that corresponds to winter dates to a new file (in the same order). If the given file does not contain required dates then the resulting file must be empty.`
	f.en[71] = `A file of strings is given; the file contains dates in the &#34;day/month/year&#34; format (see File67). Find its component that represents the earliest spring date. If the given file does not contain spring dates then output an empty string.`
	f.en[72] = `A file of strings is given; the file contains dates in the &#34;day/month/year&#34; format (see File67). Find its component that represents the latest autumn date. If the given file does not contain autumn dates then output an empty string.`
	f.en[73] = `A file of strings is given; the file contains dates in the &#34;day/month/year&#34; format (see File67). Write all its components to a new file in descending order of their date values.`
	f.en[74] = `Two integers&nbsp;<i>I</i>, <i>J</i> and a file of real numbers are given. This file contains elements of square matrix (by rows). Output the value of the matrix element in the <i>I</i>-th row and <i>J</i>-th column (rows and columns are numbered beginning with&nbsp;1). If the given matrix does not contain the required row or column then output&nbsp;0 (as a real number).`
	f.en[75] = `A file of real numbers is given. This file contains elements of square matrix (by rows). Create a new file that contains the <i>transpose</i> of the given matrix.`
	f.en[76] = `Two files of real numbers called&nbsp;<i>S</i><sub><i>A</i></sub> and&nbsp;<i>S</i><sub><i>B</i></sub> are given. These files contain elements of square matrix&nbsp;<i>A</i> and&nbsp;<i>B</i> (by rows). Create a new file called&nbsp;<i>S</i><sub><i>C</i></sub> that contains elements of the <i>matrix product</i> <i>A</i>&#183;<i>B</i>. If matrices&nbsp;<i>A</i> and&nbsp;<i>B</i> cannot be multiplied then the resulting file&nbsp;<i>S</i><sub><i>C</i></sub> must be empty.`
	f.en[77] = `Two integers&nbsp;<i>I</i>, <i>J</i> and a file of real numbers are given. The first component of the file contains the amount of matrix columns, other file components contain matrix elements (by rows). Output the value of the matrix element in the <i>I</i>-th row and <i>J</i>-th column (rows and columns are numbered beginning with&nbsp;1). If the given matrix does not contain the required row or column then output&nbsp;0 (as a real number).`
	f.en[78] = `A file of real numbers is given. The first component of the file contains the amount of matrix columns, other file components contain matrix elements (by rows). Create a new file that contains the <i>transpose</i> of the given matrix. The resulting file must have the same structure as the given file.`
	f.en[79] = `Two files of real numbers called&nbsp;<i>S</i><sub><i>A</i></sub> and&nbsp;<i>S</i><sub><i>B</i></sub> are given. The first components of the files&nbsp;<i>S</i><sub><i>A</i></sub> and&nbsp;<i>S</i><sub><i>B</i></sub> contain the amount of columns of matrices&nbsp;<i>A</i> and&nbsp;<i>B</i> respectively, other file components contain elements of matrices&nbsp;<i>A</i> and&nbsp;<i>B</i> (by rows). Create a new file called&nbsp;<i>S</i><sub><i>C</i></sub> that contains the <i>matrix product</i> <i>A</i>&#183;<i>B</i> (the resulting file must have the same structure as the given files). If matrices&nbsp;<i>A</i> and&nbsp;<i>B</i> cannot be multiplied then the resulting file must be empty.`
	f.en[80] = `A file of real numbers is given. This file contains elements of an <i>upper triangular matrix</i> (by rows). Create a new file that contains elements of nonzero part of the given matrix (by rows).`
	f.en[81] = `A file of real numbers is given. This file contains elements of a <i>lower triangular matrix</i> (by rows). Create a new file that contains elements of nonzero part of the given matrix (by rows).`
	f.en[82] = `A file of real numbers is given. This file contains elements of a <i>tridiagonal</i> matrix (by rows). Create a new file that contains elements of nonzero part of the given matrix (by rows).`
	f.en[83] = `Two integers&nbsp;<i>I</i>, <i>J</i> and a file of real numbers are given. This file contains elements of nonzero part of an <i>upper triangular matrix</i> (by rows). Output the matrix order and the value of the matrix element in the <i>I</i>-th row and <i>J</i>-th column (rows and columns are numbered beginning with&nbsp;1). If the required element lies in zero part of the matrix then output&nbsp;0 (as a real number). If the given matrix does not contain the required row or column then output&nbsp;&#8722;1 (as a real number).`
	f.en[84] = `Two integers&nbsp;<i>I</i>, <i>J</i> and a file of real numbers are given. This file contains elements of nonzero part of a <i>lower triangular matrix</i> (by rows). Output the matrix order and the value of the matrix element in the <i>I</i>-th row and <i>J</i>-th column (rows and columns are numbered beginning with&nbsp;1). If the required element lies in zero part of the matrix then output&nbsp;0 (as a real number). If the given matrix does not contain the required row or column then output&nbsp;&#8722;1 (as a real number).`
	f.en[85] = `Two integers&nbsp;<i>I</i>, <i>J</i> and a file of real numbers are given. This file contains elements of nonzero part of a <i>tridiagonal matrix</i> (by rows). Output the matrix order and the value of the matrix element in the <i>I</i>-th row and <i>J</i>-th column (rows and columns are numbered beginning with&nbsp;1). If the required element lies in zero part of the matrix then output&nbsp;0 (as a real number). If the given matrix does not contain the required row or column then output&nbsp;&#8722;1 (as a real number).`
	f.en[86] = `A file of real numbers is given. This file contains elements of nonzero part of an <i>upper triangular matrix</i> (by rows). Create a new file that contains all elements of the given matrix (by rows).`
	f.en[87] = `A file of real numbers is given. This file contains elements of nonzero part of a <i>lower triangular matrix</i> (by rows). Create a new file that contains all elements of the given matrix (by rows).`
	f.en[88] = `A file of real numbers is given. This file contains elements of nonzero part of a <i>tridiagonal matrix</i> (by rows). Create a new file that contains all elements of the given matrix (by rows).`
	f.en[89] = `Two files of real numbers called&nbsp;<i>S</i><sub><i>A</i></sub> and&nbsp;<i>S</i><sub><i>B</i></sub> are given. These files contain nonzero parts of <i>upper triangular</i> matrices&nbsp;<i>A</i> and&nbsp;<i>B</i> (by rows). Create a new file called&nbsp;<i>S</i><sub><i>C</i></sub> that contains nonzero part of the <i>matrix product</i>&nbsp;<i>A</i>&#183;<i>B</i> (by rows). If matrices&nbsp;<i>A</i> and&nbsp;<i>B</i> cannot be multiplied then the resulting file must be empty.`
	f.en[90] = `Two files of real numbers called&nbsp;<i>S</i><sub><i>A</i></sub> and&nbsp;<i>S</i><sub><i>B</i></sub> are given. These files contain nonzero parts of <i>lower triangular</i> matrices&nbsp;<i>A</i> and&nbsp;<i>B</i> (by rows). Create a new file called&nbsp;<i>S</i><sub><i>C</i></sub> that contains nonzero part of the <i>matrix product</i>&nbsp;<i>A</i>&#183;<i>B</i> (by rows). If matrices&nbsp;<i>A</i> and&nbsp;<i>B</i> cannot be multiplied then the resulting file must be empty.`
}

func (f *ffile) makeTj() {
	f.tj = make([]string, f.count)
	f.tj[1] = `Сатри S дода шудааст. Агар S номи имконпазири файл бошад, пас файли холиро бо ин ном созед ва True-ро хориҷ кунед. Агар бо номи S сохтани файл номумкин бошад, пас False-ро хориҷ кунед.`
	f.tj[2] = `Номи файл ва адади бутуни N (> 1) дода шудаанд. Файли ададҳои бутунро бо номи мазкур созед ва ба он N-то ададҳои аввалини бутуни ҷуфт (2, 4, …)-ро сабт кунед.`
	f.tj[3] = `Номи файл ва ададҳои ҳақиқии A ва D дода шудаанд. Файли ададҳои ҳақиқиро бо номи мазкур созед ва ба он 10-то аъзоҳои аввалини прогрессияи арифметикиро бо аъзои аввалин A ва фарқи D: A,    A + D,    A + 2•D,    A + 3•D,    …  сабт кунед.`
	f.tj[4] = `Номҳои чорто файлҳо дода шудаанд. Миқдори файлҳоро бо номҳои нишондодашуда ёбед, ки онҳо дар пӯшаи мазкур мавҷуданд.`
	f.tj[5] = `Номи файли ададҳои бутун дода шудааст. Миқдори элементҳои дар файли мазкур мавҷударо ёбед. Агар файл бо чунин ном мавҷуд набошад, пас –1(яки манфӣ)-ро хориҷ кунед.`
	f.tj[6] = `Адади бутуни K ва файли дорои ададҳои бутуни ғайриманфӣ дода шудааст. Элементи K-ӯми файл (элементҳо аз 1 сар карда, рақамгузорӣ карда мешаванд)-ро хориҷ кунед. Агар чунин элемент мавҷуд набошад, пас –1(яки манфӣ)-ро хориҷ кунед.`
	f.tj[7] = `Файли ададҳои бутун, ки на кам аз чор элементҳоро дорост, дода шудааст. Элементҳои якӯм, дуюм, пешазохирин ва охирини файли мазкурро хориҷ кунед.`
	f.tj[8] = `Номҳои ду файлҳои ададҳои ҳақиқӣ дода шудаанд. Маълум аст, ки якӯмини онҳо вуҷуд дорад ва холӣ нест, дуюмаш бошад, дар пӯшаи мазкур вуҷуд надорад. Файли ғоиббударо созед ва ба он элементҳои аввалин ва охирини файли вуҷуддоштаро сабт кунед (бо тартиби нишондодашуда).`
	f.tj[9] = `Номҳои ду файлҳои ададҳои ҳақиқӣ дода шудаанд. Маълум аст, ки яке аз онҳо (якӯм ҳатмӣ нест) вуҷуд дорад ва холӣ нест, дигараш бошад, дар пӯшаи мазкур вуҷуд надорад. Файли ғоиббударо созед ва ба он элементҳои охирин ва аввалини файли вуҷуддоштаро сабт кунед (бо тартиби нишондодашуда).`
	f.tj[10] = `Файли ададҳои бутун дода шудааст. Файли навро созед, ки худи ҳамон элементҳои файли ибтидоиро дорост, аммо бо тартиби баръакс.`
	f.tj[11] = `Файли ададҳои ҳақиқӣ дода шудааст. Ду файлҳои навро созед, ки якӯмини онҳо элементҳои файли ибтидоиро бо рақамҳои тартибии тоқ (1, 3, …) дорост, дуюмаш бошад — элементҳои файли ибтидоиро бо рақамҳои ҷуфт (2, 4, …) дорост.`
	f.tj[12] = `Файли ададҳои бутун дода шудааст. Ду файлҳои навро созед, ки якӯмини онҳо ададҳои ҷуфти файли ибтидоиро дорост, дуюмаш бошад — ададҳои тоқи файли ибтидоиро (бо ҳамон тартиб) дорост. Агар дар файли ибтидоӣ адади тоқ ё ҷуфт мавҷуд набошад, пас файли натиҷавии мувофиқро холӣ гузоред.`
	f.tj[13] = `Файли ададҳои бутун дода шудааст. Ду файлҳои навро созед, ки якӯмини онҳо ададҳои мусбии файли ибтидоиро дорост (бо тартиби баръакс), дуюмаш бошад — ададҳои манфиро (ҳамчунин бо тартиби баръакс) дорост. Агар дар файли ибтидоӣ адади манфӣ ё мусбӣ набошад, пас файли натиҷавии мувофиқро холӣ гузоред.`
	f.tj[14] = `Файли ададҳои ҳақиқӣ дода шудааст. Қимати миёнаи арифметикии элементҳои он ёфта шавад.`
	f.tj[15] = `Файли ададҳои ҳақиқӣ дода шудааст. Суммаи элементҳои онро, ки дорои рақамҳои тартибии ҷуфт ҳастанд, ёбед.`
	f.tj[16] = `Файли ададҳои ҳақиқӣ дода шудааст. Миқдори силсилаҳо (яъне маҷмӯъҳое, ки дорои элементҳои якхелаи пайиҳамоянда ҳастанд)-и дар он мавҷударо ёбед. Масалан, барои файли дорои элементҳои 1, 5, 5, 5, 4, 4, 5 натиҷа ба 4 баробар аст.`
	f.tj[17] = `Файли ададҳои бутун дода шудааст. Файли нави ададҳои бутунро созед, ки дарозиҳои ҳамаи силсилаҳои файли ибтидоиро дорост (силсила гуфта, маҷмӯеро мегӯянд, ки дорои элементҳои якхелаи пайиҳамоянда аст, дарозии силсила бошад — миқдори ин элементҳо аст). Масалан, барои файли ибтидоии дорои элементҳои 1, 5, 5, 5, 4, 4, 5 таркиби файли натиҷавӣ бояд зерин бошад: 1, 3, 2, 1.`
	f.tj[18] = `Файли ададҳои ҳақиқӣ дода шудааст. Элементи хурдтарини локалӣ (элементи хурдтарини локалӣ гуфта, элементеро меноманд, ки он аз ҳамсояҳои худ хурд аст)-и аввалини онро ёбед.`
	f.tj[19] = `Файли ададҳои ҳақиқӣ дода шудааст. Элементи калонтарини локалӣ (элементи калонтарини локалӣ гуфта, элементеро меноманд, ки он аз ҳамсояҳои худ калон аст)-и охирини онро ёбед.`
	f.tj[20] = `Файли ададҳои ҳақиқӣ дода шудааст. Миқдори умумии экстремумҳои локалӣ, яъне элементҳои калонтарин ва хурдтарини локалӣ (муайянкунии элементҳои калонтарин ва хурдтарини локалӣ дар масъалаҳои File18 ва File19 оварда шудаанд)-и онро ёбед.`
	f.tj[21] = `Файли ададҳои ҳақиқӣ дода шудааст. Файли ададҳои бутунро созед, ки рақамҳои ҳамаи ададҳои калонтарини локалии файли ибтидоиро бо тартиби афзуншавӣ доро бошад (муайянкунии адади калонтарини локалӣ дар масъалаи File19 дода шудааст).`
	f.tj[22] = `Файли ададҳои ҳақиқӣ дода шудааст. Файли ададҳои бутунро созед, ки рақамҳои ҳамаи экстремумҳои локалии файли ибтидоиро бо тартиби камшавӣ доро бошад (муайянкунии экстремуми локалӣ дар масъалаи File20 дода шудааст).`
	f.tj[23] = `Файли ададҳои ҳақиқӣ дода шудааст. Файли ададҳои бутунро созед, ки дарозии ҳамаи пайдарпайиҳои камшавандаи элементҳои файли ибтидоиро доро бошад. Масалан, барои файли ибтидоии дорои элементҳои 1.7, 4.5, 3.4, 2.2, 8.5, 1.2 таркиби файли натиҷавӣ бояд зерин бошад: 3, 2.`
	f.tj[24] = `Файли ададҳои ҳақиқӣ дода шудааст. Файли ададҳои бутунро созед, ки дарозии ҳамаи пайдарпайиҳои монотонии элементҳои файли ибтидоиро доро бошад. Масалан, барои файли ибтидоии дорои элементҳои 1.7, 4.5, 3.4, 2.2, 8.5, 1.2 таркиби файли натиҷавӣ бояд зерин бошад: 2, 3, 2, 2.`
	f.tj[25] = `Файли ададҳои ҳақиқӣ дода шудааст. Дар он ҳамаи элементҳоро ба квадратҳояшон иваз кунед.`
	f.tj[26] = `Файли ададҳои ҳақиқӣ дода шудааст. Дар он ҷойҳои элементҳои калонтарин ва хурдтаринро иваз кунед.`
	f.tj[27] = `Файли ададҳои бутун бо элементҳои A<sub>1</sub>, A<sub>2</sub>, …, A<sub>N</sub> (N — миқдори элемент дар файл) дода шудааст. Мавқеи ибтидоии элементҳои онро ба тариқи зайл иваз кунед: A<sub>1</sub>,    A<sub>N</sub>,    A<sub>2</sub>,    A<sub>N-1</sub>,    A<sub>3</sub>,    … .`
	f.tj[28] = `Файли ададҳои ҳақиқӣ дода шудааст. Дар файл ҳар як элементро, ба ғайр аз аввалин ва охирин ба қимати миёнаи арифметикии он бо элементҳои пешина ва пасина иваз кунед.`
	f.tj[29] = `Файли ададҳои бутун дода шудааст, ки дорои зиёда аз 50 элементҳо аст. Андозаи онро бо нест кардани миқдори зарурии элементҳои ниҳоӣ аз файл то 50 элемент кам кунед.`
	f.tj[30] = `Файли ададҳои бутун дода шудааст, ки миқдори ҷуфти элементҳоро дорост. Аз файли мазкур нимаи дуюми элементҳоро нест кунед.`
	f.tj[31] = `Файли ададҳои бутун дода шудааст, ки зиёда аз 50 элементҳоро дорост. Андозаи онро бо нест кардани миқдори зарурии элементҳои аввала аз файл то 50 элементҳо кам кунед.`
	f.tj[32] = `Файли ададҳои бутун дода шудааст, ки миқдори ҷуфти элементҳоро дорост. Аз файли мазкур нимаи якӯми элементҳоро нест кунед.`
	f.tj[33] = `Файли ададҳои бутун дода шудааст. Аз он ҳамаи элементҳои дорои рақами тартибии ҷуфтро нест кунед.`
	f.tj[34] = `Файли ададҳои бутун дода шудааст. Аз он ҳамаи ададҳои манфиро нест кунед.`
	f.tj[35] = `Файли ададҳои бутун дода шудааст, ки камтар 50 элементҳоро дорост. Андозаи онро бо сабти миқдори зарурии нулҳо дар аввали файл то 50 элементҳо зиёд кунед.`
	f.tj[36] = `Файли ададҳои бутун дода шудааст. Андозаи онро бо сабти ҳамаи элементҳои ибтидоии он (бо ҳамон тартиб) дар охири файл дуто кунед.`
	f.tj[37] = `Файли ададҳои бутун дода шудааст. Андозаи онро бо сабти ҳамаи элементҳои ибтидоии он (бо тартиби баръакс) дар охири файл дуто кунед.`
	f.tj[38] = `Файли ададҳои бутун дода шудааст. Дар он ҳамаи элементҳои дорои рақами тартибии тоқро дуто кунед.`
	f.tj[39] = `Файли ададҳои бутун дода шудааст. Дар он ҳамаи ададҳои дар фосилаи 5-10 ҷойгирифтаро дуто кунед.`
	f.tj[40] = `Файли ададҳои бутун дода шудааст. Дар он ҳар як элементи дорои рақами тартибии ҷуфтро ба ду нулҳо иваз кунед.`
	f.tj[41] = `Файли ададҳои бутун дода шудааст. Дар он ҳар як адади мусбиро ба се нулҳо иваз кунед.`
	f.tj[42] = `Ду файлҳои типи ихтиёрӣ дода шудаанд. Ҷойҳои таркибҳои онҳоро иваз кунед.`
	f.tj[43] = `Файли типи ихтиёрӣ дода шудааст. Нусхаи онро бо номи нав созед.`
	f.tj[44] = `Се файлҳои типи якхела, аммо андозаҳои гуногун дода шудаанд. Таркиби файли дарозтаринро ба таркиби файли кӯтоҳтарин иваз кунед.`
	f.tj[45] = `Се файлҳои типи ягона, аммо андозаҳои гуногун дода шудаанд. Таркиби файли кӯтоҳтаринро ба таркиби файли дарозтарин иваз кунед.`
	f.tj[46] = `Сатри S<sub>0</sub>, адади бутуни N (&lt;= 4) ва N файлҳои типи якхела бо номҳои S<sub>1</sub>, …, S<sub>N</sub> дода шудаанд. Таркиби ин файлҳоро (бо таркиби нишондодашуда) дар файли нав бо номи S<sub>0</sub> якҷоя кунед.`
	f.tj[47] = `Ду файлҳои типи якхела дода шудаанд. Ба файли якӯм таркиби файли дуюмро ҳамроҳ кунед, ба файли дуюм бошад, — таркиби файли якӯмро.`
	f.tj[48] = `Се файлҳои ададҳои бутун бо андозаи якхела бо номҳои S<sub>A</sub>, S<sub>B</sub>, S<sub>C</sub> ва сатри S<sub>D</sub> дода шудаанд. Файли навро бо номи S<sub>D</sub> созед, ки дар он элементҳои файлҳои ибтидоӣ бо рақамҳои тартибии якхела пайиҳам оянд: A<sub>1</sub>,    B<sub>1</sub>,    C<sub>1</sub>,    A<sub>2</sub>,    B<sub>2</sub>,    C<sub>2</sub>,    … .`
	f.tj[49] = `Чор файлҳои андозаҳои гуногуни ададҳои бутун бо номҳои S<sub>A</sub>, S<sub>B</sub>, S<sub>C</sub>, S<sub>D</sub> ва сатри S<sub>E</sub> дода шудаанд. Файли навро бо номи S<sub>E</sub> созед, ки дар он элементҳои файлҳои ибтидоӣ бо рақамҳои тартибии якхела (чун дар масъалаи File48) пайиҳам оянд. Элемментҳои «зиёдатӣ»-и файлҳои дарозтарро дар файли натиҷавӣ сабт НАкунед.`
	f.tj[50] = `Ду файлҳои ададҳои ҳақиқӣ бо номҳои S<sub>1</sub> ва S<sub>2</sub> дода шуданд, ки элементҳои онҳо аз рӯи афзуншавӣ ба тартиб гузошта шудаанд. Ин файлҳоро дар файли нав бо номи S<sub>3</sub> чунон якҷоя кунед, ки элементҳои он низ аз рӯи афзуншавӣ ба тартиб гузошта шуда бошанд.`
	f.tj[51] = `Се файлҳои ададҳои ҳақиқӣ бо номҳои S<sub>1</sub>, S<sub>2</sub> ва S<sub>3</sub> дода шудаанд, ки элементҳои онҳо аз рӯи камшавӣ ба тартиб газошта шудаанд. Ин файлҳоро дар файли нав бо номи S<sub>4</sub> чунон ба тартиб гузоред, ки элементҳои он низ аз рӯи камшавӣ ба тартиб гузошта шуда бошанд.`
	f.tj[52] = `Сатри S<sub>0</sub>, адади бутуни N (&lt;= 4) ва N файлҳои ададҳои бутун бо номҳои S<sub>1</sub>, …, S<sub>N</sub> дода шудаанд. Таркибҳои онҳоро дар файл-хазинаи нав бо номи S<sub>0</sub> бо истифодабарии шакли зерин якҷоя кунед: дар элементи якӯми файл-хазина адади N нигоҳ дошта мешавад, дар N элементҳои оянда андоза (адади элементҳо)-и ҳар яке аз файлҳои ибтидоӣ нигоҳ дошта мешавад, сонӣ пайдарпай додаҳои ҳар як файли ибтидоӣ ҷой дода мешаванд.`
	f.tj[53] = `Сатри S, адади бутуни N (> 0) ва файл-хазинаи ададҳои бутун дода шудаанд, ки файл-хазина додаҳои якчанд файлҳоро дар шакли дар масъалаи File52 тасвиршуда дорост. Аз файла-хазина файлро бо рақами тартибии N барқарор кунед ва онро таҳти номи S сабт кунед. Агар файл-хазина додаҳоро аз камтар аз N файлҳо доро бошад, пас файли натиҷавиро холӣ гузоред.`
	f.tj[54] = `Сатри S ва файл-хазинаи ададҳои бутун дода шудаанд, ки файл-хазина додаҳоро аз якчанд (на зиёд аз шаш) файлҳо дар шакли дар масъалаи File52 тасвиршуда дорост. Барои ҳар яке аз файлҳо, дар хазина ҳастанд, қимати миёнаи арифметикии ҳамаи элементҳои онро (адади ҳақиқӣ) ёбед ва ададҳои ёфташударо (бо ҳамон тартиб) ба файли ададҳои ҳақиқӣ бо номи S сабт кунед.`
	f.tj[55] = `Сатри S<sub>0</sub>, адади бутуни N (&lt;= 4) ва N файлҳои ададҳои бутун бо номҳои S<sub>1</sub>, …, S<sub>N</sub> дода шудаанд. Таркибҳои онҳоро дар файл-хазинаи нав бо номи S<sub>0</sub> бо пайдарпай сабткунии додаҳои зерин дар он: андоза (адади элементҳо)-и файли ибтидоии якӯм ва ҳамаи элементҳои ин файл, андозаи файли ибтидоии дуюм ва ҳамаи элементҳои он, …, андозаи файли ибтидои N-ӯм ва ҳамаи элементҳои он якҷоя кунед.`
	f.tj[56] = `Сатри S, адади бутуни N (> 0) ва файл-хазинаи ададии бутун дода шудаанд, ки файл-хазина додаҳоро аз якчанд файлҳо дар формати дар масъалаи File55 тасвиршуда дорост. Аз файл-хазина файлро бо рақами тартибии N барқарор кунед ва онро таҳти номи S сабт кунед. Агар файл-хазина додаҳоро камтар аз N файлҳо доро бошад, пас файли натиҷавиро холӣ гузоред.`
	f.tj[57] = `Сатрҳои S<sub>1</sub>, S<sub>2</sub> ва файл-хазинаи ададҳои бутун, ки додаҳоро аз якчанд файлҳо дар формати дар масъалаи File55 тасвиршуда дорост, дода шудаанд. Файлҳои нави ададҳои бутунро бо номҳои S<sub>1</sub> ва S<sub>2</sub> созед ва ба файли якӯмаш элементҳои аввалаи ҳамаи файлҳоро, ки дар хазина ҳастанд, сабт кунед, ба дуюмаш бошад, — элементҳои охирини ин файлҳоро (бо ҳамон тартиб) сабт кунед.`
	f.tj[58] = `Файли аломатие, ки ба ҳадди ақал як аломати фосила дорад, дода шудааст. Ҳамаи элементҳои онро, ки пас аз аломати фосилаи аввалин ҷойгир шудаанд, якҷоя бо ин фосила нест кунед.`
	f.tj[59] = `Файли аломатие, ки ба ҳадди ақал як аломати фосила дорад, дода шудааст. Ҳамаи элементҳои онро, ки пас аз аломати фосилаи охирин ҷойгир шудаанд, якҷоя бо ин фосила нест кунед.`
	f.tj[60] = `Файли аломатие, ки ба ҳадди ақал як аломати фосила дорад, дода шудааст. Ҳамаи элементҳои онро, ки пеш аз аломати фосилаи аввалин ҷойгир шудаанд, якҷоя бо ин фосила нест кунед.`
	f.tj[61] = `Файли аломатие, ки ба ҳадди ақал як аломати фосила дорад, дода шудааст. Ҳамаи элементҳои онро, ки пеш аз аломати фосилаи охирин ҷойгир шудаанд, якҷоя бо ин фосила нест кунед.`
	f.tj[62] = `Файли аломатӣ дода шудааст. Элементҳои онро аз рӯи афзуншавии кодҳояшон ба тартиб гузоред.`
	f.tj[63] = `Адади бутуни K (> 0) ва файли сатрӣ дода шудаанд. Ду файли нав созед: сатрӣ, ки K-то аломатҳои аввалаи ҳар як сатри файли ибтидоиро дорост, ва рамзӣ, ки аломати K-ӯми ҳар як сатрро дорост (агар дарозии сатр аз K хурд бошад, пас ба файли сатрӣ тамоми сатр навишта мешавад, ба файли рамзӣ бошад, фосила сабт карда мешавад).`
	f.tj[64] = `Файли сатрӣ дода шудааст. Файли сатрии наверо созед, ки ҳамаи сатрҳои файлҳои ибтидоиро бо дарозии хурдтарин (бо ҳамон тартиб) дорост.`
	f.tj[65] = `Файли сатрӣ дода шудааст. Файли сатрии наверо созед, ки ҳамаи сатрҳои файли ибтидоиро бо дарозии калонтарин (бо тартиби баръакс) дорост.`
	f.tj[66] = `Файли сатрӣ дода шудааст. Файли сатрии наверо созед, ки дар он сатрҳои файли ибтидоӣ бо тартиби лексикографӣ, яъне, сар карда аз аломати якӯм, аз рӯи афзуншавии кодҳои аломатҳояшон ҷойгир шуда бошанд.`
	f.tj[67] = `Файли сатрӣ дода шудааст, ки санаро бо шакли «рӯз/моҳ/сол» дорост, ки дар ин ҷо таҳти рӯз ва моҳ ду мавқеъ ҷудо карда мешавад, таҳти сол бошад, — чор мавқеъ (масалан, «04/04/2014»). Ду файли ададҳои бутунро созед, ки якӯмаш қиматҳои рӯзҳоро дорост, дуюмаш бошад, — қиматҳои моҳҳоро барои санаҳо аз файли сатрии ибтидоӣ (бо ҳамон тартиб) дорост.`
	f.tj[68] = `Файли сатрӣ дода шудааст, ки санаҳоро дар шакли дар масъалаи File67 тасвиршуда дорост. Ду файли ададҳои бутунро созед, ки якӯмаш қиматҳои моҳҳоро, дуюмаш бошад, — қиматҳои солҳоро барои санаҳо аз файли сатрии ибтидоӣ (бо тартиби баръакс) дорост.`
	f.tj[69] = `Файли сатрӣ дода шудааст, ки санаҳоро дар шакли дар масъалаи File67 тасвиршуда дорост. Файли сатрии наверо созед, ки ҳамаи санаҳои тобистонаро аз файли ибтидоӣ (бо ҳамон тартиб) доро бошад. Агар санаҳо бо замони талабкардашудаи сол мавҷуд набошанд, пас файли натиҷавиро холӣ гузоред.`
	f.tj[70] = `Файли сатрӣ дода шудааст, ки санаҳоро дар шакли дар масъалаи File67 тасвиршуда дорост. Файли сатрии наверо созед, ки ҳамаи санаҳои зимистонаро аз файли ибтидоӣ (бо тартиби баръакс) доро бошад. Агар санаҳо бо замони талабкардашудаи сол мавҷуд набошанд, пас файли натиҷавиро холӣ гузоред.`
	f.tj[71] = `Файли сатрӣ дода шудааст, ки санаҳоро дар шакли дар масъалаи File67 тасвиршуда дорост. Сатреро ёбед, ки санаи баҳории барақттаринро дорост. Агар сана бо замони талабкардашудаи сол дар файл мавҷуд набошад, пас сатри холиро хориҷ кунед.`
	f.tj[72] = `Файли сатрӣ дода шудааст, ки санаҳоро дар шакли дар масъалаи File67 тасвиршуда дорост. Сатреро ёбед, ки санаи тирамоҳии дертаринро дорост. Агар сана бо замони талабкардашудаи сол дар файл мавҷуд набошад, пас сатри холиро хориҷ кунед.`
	f.tj[73] = `Файли сатрӣ дода шудааст, ки санаҳоро дар шакли дар масъалаи File67 тасвиршуда дорост. Файли сатрии наверо созед, ки дар он санаҳои файли ибтидоӣ бо тартиби камшавӣ ҷойгир шуда бошанд.`
	f.tj[74] = `Ду ададҳои бутуни I, J ва файли ададҳои ҳақиқӣ дода шудаанд, ки файл элементҳои матритсаи квадратӣ (аз рӯи сатрҳо)-ро дорост. Элементи матритсаро хориҷ кунед, ки дар сатри I-ӯм ва сутуни J-ӯм ҷойгир бошад (сатрҳо ва сутунҳо аз 1 сар карда рақамгузорӣ карда мешаванд). Агар элементи талабкардашуда мавҷуд набошад, пас 0(нул)-ро хориҷ кунед.`
	f.tj[75] = `Файли ададҳои ҳақиқӣ дода шудааст, ки элементҳои матритсаи квадратӣ (аз рӯи сатрҳо)-ро дорост. Файли наверо созед, ки элементҳои матритсаи ба матритсаи ибтидоӣ транспониронидашударо доро бошад.`
	f.tj[76] = `Ду файлҳои ададҳои ҳақиқӣ бо номҳои S<sub>A</sub> ва S<sub>B</sub> дода шудаанд, ки элементҳои матритсаҳои квадратии A ва B (аз рӯи сатрҳо)-ро доростанд. Файли навро бо номи S<sub>C</sub> созед, ки элементҳои зарби A•B-ро доро бошад. Агар матритсаҳои A ва B-ро зарб кардан номумкин бошад, пас файли S<sub>C</sub>-ро холӣ гузоред.`
	f.tj[77] = `Ду ададҳои бутуни I, J ва файли ададҳои ҳақиқӣ дода шудаанд, ки файл элементҳои матритсаи росткунҷа (аз рӯи сатрҳо)-ро дорост, ки дар ин ҷо элементи якӯми файл миқдори сутунҳои матритсаро дорост. Элементи матритсаро, ки дар сатри I-ӯм ва сутуни J-ӯм ҷойгир аст, хориҷ кунед (сатрҳо ва сутунҳо аз 1 сар карда рақамгузорӣ карда мешаванд). Агар элементи талабкардашуда мавҷуд набошад, пас 0(нул)-ро хориҷ кунед.`
	f.tj[78] = `Файли ададҳои ҳақиқӣ дода шудааст, ки элементҳои матритсаи росткунҷа (аз рӯи сатрҳо)-ро дорост, ки дар ин ҷо элементи якӯми файл миқдори сутунҳои матритсаро дорост. Файли нави ҳамон сохтро созед, ки матритсаи ба матритсаи ибтидоӣ транспониронидашударо дорост.`
	f.tj[79] = `Ду файлҳои ададҳои ҳақиқӣ бо номҳои S<sub>A</sub> ва S<sub>B</sub> дода шудаанд, ки элементҳои матритсаҳои росткунҷаи A в B (аз рӯи сатрҳо)-ро доростанд, ки дар ин ҷо элементи якӯми ҳар як файл миқдори сутунҳои матритсаи мувофиқро дорост. Файли ҳамон сохтро бо номи S<sub>C</sub> созед, ки элементҳои зарби A•B-ро доро бошад. Агар матритсаҳои A ва B-ро зарб кардан номумкин бошад, пас файли S<sub>C</sub>-ро холӣ гузоред.`
	f.tj[80] = `Файли ададҳои ҳақиқӣ дода шудааст, ки элементҳои матритсаи болосекунҷа (аз рӯи сатрҳо)-ро дорост. Файли навро созед, ки элементҳои қисми ғайринулии матритсаи мазкур (аз рӯи сатрҳо)-ро дорост.`
	f.tj[81] = `Файли ададҳои ҳақиқӣ дода шудааст, ки элементҳои матритсаи поёнсекунҷа (аз рӯи сатрҳо)-ро дорост. Файли наверо созед, ки элементҳои қисми ғайринулии матритсаи мазкур (аз рӯи сатрҳо)-ро дорост.`
	f.tj[82] = `Файли ададҳои ҳақиқӣ дода шудааст, ки элементҳои матритсаи седиагоналӣ (аз рӯи сатрҳо)-ро дорост. Файли наверо созед, ки элементҳои қисми ғайринулии матритсаи мазкур (аз рӯи сатрҳо)-ро дорост.`
	f.tj[83] = `Ду ададҳои бутуни I, J ва файли ададҳои ҳақиқӣ дода шудаанд, ки файл қисми ғайринулии матритсаи болосекунҷа (аз рӯи сатрҳо)-ро дорост. Тартиби матритса ва элементи онро, ки дар сатри I-ӯм ва сутуни J-ӯм ҷойгир шудааст (сатрҳо ва сутунҳо аз 1 сар карда рақамгузорӣ карда мешаванд), хориҷ кунед. Агар элементи талабкардашуда дар қисми нулии матритса ҷойгир бошад, пас 0(нул)-ро хориҷ кунед; агар элемент мавҷуд набошад, пас (–1)-ро хориҷ кунед.`
	f.tj[84] = `Ду ададҳои бутуни I, J ва файли ададҳои ҳақиқӣ дода шудаанд, ки файл қисми ғайринулии матритсаи поёнсекунҷа (аз рӯи сатрҳо)-ро дорост. Тартиби матритса ва элементи онро, ки дар сатри I-ӯм ва сутуни J-ӯм ҷойгир шудааст (сатрҳо ва сутунҳо аз 1 сар карда рақамгузорӣ карда мешаванд), хориҷ кунед. Агар элементи талабкардашуда дар қисми нулии матритса ҷойгир бошад, пас 0(нул)-ро хориҷ кунед; агар элемент мавҷуд набошад, пас (–1)-ро хориҷ кунед.`
	f.tj[85] = `Ду ададҳои бутуни I, J ва файли ададҳои ҳақиқӣ дода шудаанд, ки файл қисми ғайринулии матритсаи седиагоналаро (аз рӯи сатрҳо)-ро дорост. Тартиби матритса ва элементи онро, ки дар сатри I-ӯм ва сутуни J-ӯм ҷойгир шудааст (сатрҳо ва сутунҳо аз 1 сар карда рақамгузорӣ карда мешаванд), хориҷ кунед. Агар элементи талабкардашуда дар қисми нулии матритса ҷойгир бошад, пас 0(нул)-ро хориҷ кунед; агар элемент мавҷуд набошад, пас (–1)-ро хориҷ кунед.`
	f.tj[86] = `Файли ададҳои ҳақиқӣ дода шудааст, ки қисми ғайринулии матритсаи болосекунҷа (аз рӯи сатрҳо)-ро дорост. Файли навро созед, ки ҳамаи элементҳои матритсаи маскур (аз рӯи сатрҳо)-ро доро бошад.`
	f.tj[87] = `Файли ададҳои ҳақиқӣ дода шудааст, ки қисми ғайринулии матритсаи поёнсекунҷа (аз рӯи сатрҳо)-ро дорост. Файли навро созед, ки ҳамаи элементҳои матритсаи мазкур (аз рӯи сатрҳо)-ро доро бошад.`
	f.tj[88] = `Файли ададҳои ҳақиқӣ дода шудааст, ки қисми ғайринулии матритсаи седиагонала (аз рӯи сатрҳо)-ро дорост. Файли навро созед, ки ҳамаи элементҳои матритсаи мазкур (аз рӯи сатрҳо)-ро доро бошад.`
	f.tj[89] = `Ду файлҳои аадҳои ҳақиқӣ бо номҳои S<sub>A</sub> ва S<sub>B</sub> дода шудаанд, ки қисми ғайринулии матритсаҳои болосекунҷаи A ва B (аз рӯи сатрҳо)-ро доростанд. Файли навро бо номи S<sub>C</sub> созед, ки қисми ғайринулии зарби A•B (аз рӯи сатрҳо)-ро доро бошад. Агар матритсаҳои A ва B-ро зарб кардан номумкин бошад, пас файли S<sub>C</sub>-ро холӣ гузоред.`
	f.tj[90] = `Ду файлҳои аадҳои ҳақиқӣ бо номҳои S<sub>A</sub> ва S<sub>B</sub> дода шудаанд, ки қисми ғайринулии матритсаҳои поёнсекунҷаи A ва B (аз рӯи сатрҳо)-ро доростанд. Файли навро бо номи S<sub>C</sub> созед, ки қисми ғайринулии зарби A•B (аз рӯи сатрҳо)-ро доро бошад. Агар матритсаҳои A ва B-ро зарб кардан номумкин бошад, пас файли S<sub>C</sub>-ро холӣ гузоред.`
}

func (f *ffile) makeRu() {
	f.ru = make([]string, f.count)
	f.ru[1] = `Дана строка&nbsp;<i>S</i>. Если <i>S</i>&nbsp;является допустимым именем файла, то создать пустой файл с этим именем и вывести true. Если файл с именем&nbsp;<i>S</i> создать нельзя, то вывести false.`
	f.ru[2] = `Дано имя файла и целое число&nbsp;<i>N</i> (&gt;&nbsp;1). Создать файл целых чисел с данным именем и записать в него <i>N</i>&nbsp;первых положительных четных чисел (2, 4,&nbsp;&#8230;).`
	f.ru[3] = `Дано имя файла и вещественные числа&nbsp;<i>A</i> и&nbsp;<i>D</i>. Создать файл вещественных чисел с данным именем и записать в него 10&nbsp;первых членов <i>арифметической прогрессии</i> с начальным членом&nbsp;<i>A</i> и разностью&nbsp;<i>D</i>: <i>A</i>, &nbsp; &nbsp;<i>A</i>&nbsp;+&nbsp;<i>D</i>, &nbsp; &nbsp;<i>A</i>&nbsp;+&nbsp;2&#183;<i>D</i>, &nbsp; &nbsp;<i>A</i>&nbsp;+&nbsp;3&#183;<i>D</i>, &nbsp; &nbsp;&#8230;&nbsp;.`
	f.ru[4] = `Даны имена четырех файлов. Найти количество файлов с указанными именами, которые имеются в текущем каталоге.`
	f.ru[5] = `Дано имя файла целых чисел. Найти количество элементов, содержащихся в данном файле. Если файла с таким именем не существует, то вывести&nbsp;&#8722;1.`
	f.ru[6] = `Дано целое число&nbsp;<i>K</i> и файл, содержащий неотрицательные целые числа. Вывести <i>K</i>-й элемент файла (элементы нумеруются от&nbsp;1). Если такой элемент отсутствует, то вывести&nbsp;&#8722;1.`
	f.ru[7] = `Дан файл целых чисел, содержащий не менее четырех элементов. Вывести первый, второй, предпоследний и последний элементы данного файла.`
	f.ru[8] = `Даны имена двух файлов вещественных чисел. Известно, что первый из них существует и является непустым, а второй в текущем каталоге отсутствует. Создать отсутствующий файл и записать в него начальный и конечный элементы существующего файла (в указанном порядке).`
	f.ru[9] = `Даны имена двух файлов вещественных чисел. Известно, что один из них (не обязательно первый) существует и является непустым, а другой в текущем каталоге отсутствует. Создать отсутствующий файл и записать в него конечный и начальный элементы существующего файла (в указанном порядке).`
	f.ru[10] = `Дан файл целых чисел. Создать новый файл, содержащий те же элементы, что и исходный файл, но в обратном порядке.`
	f.ru[11] = `Дан файл вещественных чисел. Создать два новых файла, первый из которых содержит элементы исходного файла с нечетными номерами (1,&nbsp;3,&nbsp;&#8230;), а второй &#8212; с четными (2,&nbsp;4,&nbsp;&#8230;).`
	f.ru[12] = `Дан файл целых чисел. Создать два новых файла, первый из которых содержит четные числа из исходного файла, а второй &#8212; нечетные (в том же порядке). Если четные или нечетные числа в исходном файле отсутствуют, то соответствующий результирующий файл оставить пустым.`
	f.ru[13] = `Дан файл целых чисел. Создать два новых файла, первый из которых содержит положительные числа из исходного файла (в обратном порядке), а второй &#8212; отрицательные (также в обратном порядке). Если положительные или отрицательные числа в исходном файле отсутствуют, то соответствующий результирующий файл оставить пустым.`
	f.ru[14] = `Дан файл вещественных чисел. Найти среднее арифметическое его элементов.`
	f.ru[15] = `Дан файл вещественных чисел. Найти сумму его элементов с четными номерами.`
	f.ru[16] = `Дан файл целых чисел. Найти количество содержащихся в нем <i>серий</i> (т.&nbsp;е. наборов последовательно расположенных одинаковых элементов). Например, для файла с элементами 1,&nbsp;5, 5, 5, 4, 4,&nbsp;5 результат равен&nbsp;4.`
	f.ru[17] = `Дан файл целых чисел. Создать новый файл целых чисел, содержащий длины всех серий исходного файла (<i>серией</i> называется набор последовательно расположенных одинаковых элементов, а <i>длиной серии</i> &#8212; количество этих элементов). Например, для исходного файла с элементами 1, 5, 5, 5, 4, 4,&nbsp;5 содержимое результирующего файла должно быть следующим: 1, 3, 2,&nbsp;1.`
	f.ru[18] = `Дан файл вещественных чисел. Найти его первый локальный минимум (<i>локальным минимумом</i> называется элемент, который меньше своих соседей).`
	f.ru[19] = `Дан файл вещественных чисел. Найти его последний локальный максимум (<i>локальным максимумом</i> называется элемент, который больше своих соседей).`
	f.ru[20] = `Дан файл вещественных чисел. Найти общее количество его <i>локальных экстремумов</i>, т.&nbsp;е. локальных минимумов и локальных максимумов (определения локального минимума и локального максимума даны в заданиях File18 и File19).`
	f.ru[21] = `Дан файл вещественных чисел. Создать файл целых чисел, содержащий номера всех <i>локальных максимумов</i> исходного файла в порядке возрастания (определение локального максимума дано в задании File19).`
	f.ru[22] = `Дан файл вещественных чисел. Создать файл целых чисел, содержащий номера всех <i>локальных экстремумов</i> исходного файла в порядке убывания (определение локального экстремума дано в задании File20).`
	f.ru[23] = `Дан файл вещественных чисел. Создать файл целых чисел, содержащий длины всех убывающих последовательностей элементов исходного файла. Например, для исходного файла с элементами 1.7, 4.5, 3.4, 2.2, 8.5,&nbsp;1.2 содержимое результирующего файла должно быть следующим: 3,&nbsp;2.`
	f.ru[24] = `Дан файл вещественных чисел. Создать файл целых чисел, содержащий длины всех монотонных последовательностей элементов исходного файла. Например, для исходного файла с элементами 1.7, 4.5, 3.4, 2.2, 8.5,&nbsp;1.2 содержимое результирующего файла должно быть следующим: 2, 3, 2,&nbsp;2.`
	f.ru[25] = `Дан файл вещественных чисел. Заменить в нем все элементы на их квадраты.`
	f.ru[26] = `Дан файл вещественных чисел. Поменять в нем местами минимальный и максимальный элементы.`
	f.ru[27] = `Дан файл целых чисел с элементами&nbsp;<i>A</i><sub>1</sub>, <i>A</i><sub>2</sub>,&nbsp;&#8230;, <i>A</i><sub><i>N</i></sub> (<i>N</i> &#8212; количество элементов в файле). Заменить исходное расположение его элементов на следующее: <i>A</i><sub>1</sub>, &nbsp; &nbsp;<i>A</i><sub><i>N</i></sub>, &nbsp; &nbsp;<i>A</i><sub>2</sub>, &nbsp; &nbsp;<i>A</i><sub><i>N</i>&#8722;1</sub>, &nbsp; &nbsp;<i>A</i><sub>3</sub>, &nbsp; &nbsp;&#8230;&nbsp;.`
	f.ru[28] = `Дан файл вещественных чисел. Заменить в файле каждый элемент, кроме начального и конечного, на его среднее арифметическое с предыдущим и последующим элементом.`
	f.ru[29] = `Дан файл целых чисел, содержащий более 50&nbsp;элементов. Уменьшить его размер до 50&nbsp;элементов, удалив из файла необходимое количество конечных элементов.`
	f.ru[30] = `Дан файл целых чисел, содержащий четное количество элементов. Удалить из данного файла вторую половину элементов.`
	f.ru[31] = `Дан файл целых чисел, содержащий более 50&nbsp;элементов. Уменьшить его размер до 50&nbsp;элементов, удалив из файла необходимое количество начальных элементов.`
	f.ru[32] = `Дан файл целых чисел, содержащий четное количество элементов. Удалить из данного файла первую половину элементов.`
	f.ru[33] = `Дан файл целых чисел. Удалить из него все элементы с четными номерами.`
	f.ru[34] = `Дан файл целых чисел. Удалить из него все отрицательные числа.`
	f.ru[35] = `Дан файл целых чисел, содержащий менее 50&nbsp;элементов. Увеличить его размер до 50&nbsp;элементов, записав в начало файла необходимое количество нулей.`
	f.ru[36] = `Дан файл целых чисел. Удвоить его размер, записав в конец файла все его исходные элементы (в том же порядке).`
	f.ru[37] = `Дан файл целых чисел. Удвоить его размер, записав в конец файла все его исходные элементы (в обратном порядке).`
	f.ru[38] = `Дан файл целых чисел. Продублировать в нем все элементы с нечетными номерами.`
	f.ru[39] = `Дан файл целых чисел. Продублировать в нем все числа, принадлежащие диапазону&nbsp;5&#8211;10.`
	f.ru[40] = `Дан файл целых чисел. Заменить в нем каждый элемент с четным номером на два нуля.`
	f.ru[41] = `Дан файл целых чисел. Заменить в нем каждое положительное число на три нуля.`
	f.ru[42] = `Даны два файла произвольного типа. Поменять местами их содержимое.`
	f.ru[43] = `Дан файл произвольного типа. Создать его копию с новым именем.`
	f.ru[44] = `Даны три файла одного и того же типа, но разного размера. Заменить содержимое самого длинного файла на содержимое самого короткого.`
	f.ru[45] = `Даны три файла одного и того же типа, но разного размера. Заменить содержимое самого короткого файла на содержимое самого длинного.`
	f.ru[46] = `Дана строка&nbsp;<i>S</i><sub>0</sub>, целое число&nbsp;<i>N</i> (&#8804;&nbsp;4) и <i>N</i>&nbsp;файлов одного и того же типа с именами <i>S</i><sub>1</sub>,&nbsp;&#8230;, <i>S</i><sub><i>N</i></sub>. Объединить содержимое этих файлов (в указанном порядке) в новом файле с именем <i>S</i><sub>0</sub>.`
	f.ru[47] = `Даны два файла одного и того же типа. Добавить к первому файлу содержимое второго файла, а ко второму файлу &#8212; содержимое первого.`
	f.ru[48] = `Даны три файла целых чисел одинакового размера с именами&nbsp;<i>S</i><sub><i>A</i></sub>, <i>S</i><sub><i>B</i></sub>, <i>S</i><sub><i>C</i></sub> и строка&nbsp;<i>S</i><sub><i>D</i></sub>. Создать новый файл с именем&nbsp;<i>S</i><sub><i>D</i></sub>, в котором чередовались бы элементы исходных файлов с одним и тем же номером:<i>A</i><sub>1</sub>, &nbsp; &nbsp;<i>B</i><sub>1</sub>, &nbsp; &nbsp;<i>C</i><sub>1</sub>, &nbsp; &nbsp;<i>A</i><sub>2</sub>, &nbsp; &nbsp;<i>B</i><sub>2</sub>, &nbsp; &nbsp;<i>C</i><sub>2</sub>, &nbsp; &nbsp;&#8230;&nbsp;.`
	f.ru[49] = `Даны четыре файла целых чисел разного размера с именами&nbsp;<i>S</i><sub><i>A</i></sub>, <i>S</i><sub><i>B</i></sub>, <i>S</i><sub><i>C</i></sub>, <i>S</i><sub><i>D</i></sub> и строка <i>S</i><sub><i>E</i></sub>. Создать новый файл с именем&nbsp;<i>S</i><sub><i>E</i></sub>, в котором чередовались бы элементы исходных файлов с одним и тем же номером (как в задании File48). &#171;Лишние&#187; элементы более длинных файлов в результирующий файл не&nbsp;записывать.`
	f.ru[50] = `Даны два файла вещественных чисел с именами&nbsp;<i>S</i><sub>1</sub> и&nbsp;<i>S</i><sub>2</sub>, элементы которых упорядочены по возрастанию. Объединить эти файлы в новый файл с именем&nbsp;<i>S</i><sub>3</sub> так, чтобы его элементы также оказались упорядоченными по возрастанию.`
	f.ru[51] = `Даны три файла вещественных чисел с именами&nbsp;<i>S</i><sub>1</sub>, <i>S</i><sub>2</sub> и&nbsp;<i>S</i><sub>3</sub>, элементы которых упорядочены по убыванию. Объединить эти файлы в новый файл с именем&nbsp;<i>S</i><sub>4</sub> так, чтобы его элементы также оказались упорядоченными по убыванию.`
	f.ru[52] = `Дана строка&nbsp;<i>S</i><sub>0</sub>, целое число&nbsp;<i>N</i> (&#8804;&nbsp;4) и <i>N</i>&nbsp;файлов целых чисел с именами <i>S</i><sub>1</sub>,&nbsp;&#8230;, <i>S</i><sub><i>N</i></sub>. Объединить их содержимое в новом файле-<i>архиве</i> с именем&nbsp;<i>S</i><sub>0</sub>, используя следующий формат: в первом элементе файла-архива хранится число&nbsp;<i>N</i>, в следующих <i>N</i>&nbsp;элементах хранится размер (число элементов) каждого из исходных файлов, а затем последовательно размещаются данные из каждого исходного файла.`
	f.ru[53] = `Дана строка <i>S</i>, целое число <i>N</i> (&gt;&nbsp;0) и файл-<i>архив</i> целых чисел, содержащий данные из нескольких файлов в формате, описанном в задании File52. Восстановить из файла-архива файл с номером&nbsp;<i>N</i> и сохранить его под именем&nbsp;<i>S</i>. Если файл-архив содержит данные из менее чем <i>N</i>&nbsp;файлов, то оставить результирующий файл пустым.`
	f.ru[54] = `Дана строка&nbsp;<i>S</i> и файл-<i>архив</i> целых чисел, содержащий данные из нескольких (не более шести) файлов в формате, описанном в задании File52. Для каждого из файлов, содержащихся в архиве, найти среднее арифметическое всех его элементов (вещественное число) и записать найденные числа (в том же порядке) в файл вещественных чисел с именем&nbsp;<i>S</i>.`
	f.ru[55] = `Дана строка&nbsp;<i>S</i><sub>0</sub>, целое число&nbsp;<i>N</i> (&#8804;&nbsp;4) и <i>N</i>&nbsp;файлов целых чисел  с именами <i>S</i><sub>1</sub>,&nbsp;&#8230;, <i>S</i><sub><i>N</i></sub>. Объединить их содержимое в новом файле-<i>архиве</i> с именем&nbsp;<i>S</i><sub>0</sub>, последовательно записывая в него следующие данные: размер (число элементов) первого исходного файла и все элементы этого файла, размер второго исходного файла и все его элементы, &#8230;, размер <i>N</i>-го исходного файла и все его элементы.`
	f.ru[56] = `Дана строка <i>S</i>, целое число <i>N</i> (&gt;&nbsp;0) и файл-<i>архив</i> целых чисел, содержащий данные из нескольких файлов в формате, описанном в задании File55. Восстановить из файла-архива файл с номером&nbsp;<i>N</i> и сохранить его под именем&nbsp;<i>S</i>. Если файл-архив содержит данные из менее чем <i>N</i>&nbsp;файлов, то оставить результирующий файл пустым.`
	f.ru[57] = `Даны строки&nbsp;<i>S</i><sub>1</sub>, <i>S</i><sub>2</sub> и файл-<i>архив</i> целых чисел, содержащий данные из нескольких файлов в формате, описанном в задании File55. Создать новые файлы целых чисел с именами&nbsp;<i>S</i><sub>1</sub> и&nbsp;<i>S</i><sub>2</sub> и записать в первый из них начальные элементы всех файлов, содержащихся в архиве, а во второй &#8212; конечные элементы этих файлов (в том же порядке).`
	f.ru[58] = `Дан символьный файл, содержащий по крайней мере один символ пробела. Удалить все его элементы, расположенные после первого символа пробела, включая и этот пробел.`
	f.ru[59] = `Дан символьный файл, содержащий по крайней мере один символ пробела. Удалить все его элементы, расположенные после последнего символа пробела, включая и этот пробел.`
	f.ru[60] = `Дан символьный файл, содержащий по крайней мере один символ пробела. Удалить все его элементы, расположенные перед первым символом пробела, включая и этот пробел.`
	f.ru[61] = `Дан символьный файл, содержащий по крайней мере один символ пробела. Удалить все его элементы, расположенные перед последним символом пробела, включая и этот пробел.`
	f.ru[62] = `Дан символьный файл. Упорядочить его элементы по возрастанию их кодов.`
	f.ru[63] = `Дано целое число&nbsp;<i>K</i> (&gt;&nbsp;0) и строковый файл. Создать два новых файла: строковый, содержащий первые <i>K</i>&nbsp;символов каждой строки исходного файла, и символьный, содержащий <i>K</i>-й&nbsp;символ каждой строки (если длина строки меньше&nbsp;<i>K</i>, то в строковый файл записывается вся строка, а в символьный файл записывается пробел).`
	f.ru[64] = `Дан строковый файл. Создать новый строковый файл, содержащий все строки исходного файла наименьшей длины (в том же порядке).`
	f.ru[65] = `Дан строковый файл. Создать новый строковый файл, содержащий все строки исходного файла наибольшей длины (в обратном порядке).`
	f.ru[66] = `Дан строковый файл. Создать новый строковый файл, в котором строки из исходного файла располагались бы в <i>лексикографическом</i> порядке, т.&nbsp;е. по возрастанию кодов их символов, начиная с первого символа.`
	f.ru[67] = `Дан строковый файл, содержащий даты в формате &#171;день/месяц/год&#187;, причем под день и месяц отводится по две позиции, а под год &#8212; четыре (например, &#171;16/04/2001&#187;). Создать два файла целых чисел, первый из которых содержит значения дней, а второй &#8212; значения месяцев для дат из исходного строкового файла (в том же порядке).`
	f.ru[68] = `Дан строковый файл, содержащий даты в формате, описанном в задании File67. Создать два файла целых чисел, первый из которых содержит значения месяцев, а второй &#8212; значения лет для дат из исходного строкового файла (в обратном порядке).`
	f.ru[69] = `Дан строковый файл, содержащий даты в формате, описанном в задании File67. Создать новый строковый файл, содержащий все летние даты из исходного файла (в том же порядке). Если даты с требуемым временем года в файле отсутствуют, то оставить результирующий файл пустым.`
	f.ru[70] = `Дан строковый файл, содержащий даты в формате, описанном в задании File67. Создать новый строковый файл, содержащий все зимние даты из исходного файла (в обратном порядке). Если даты с требуемым временем года в файле отсутствуют, то оставить результирующий файл пустым.`
	f.ru[71] = `Дан строковый файл, содержащий даты в формате, описанном в задании File67. Найти строку, содержащую самую раннюю весеннюю дату. Если даты с требуемым временем года в файле отсутствуют, то вывести пустую строку.`
	f.ru[72] = `Дан строковый файл, содержащий даты в формате, описанном в задании File67. Найти строку, содержащую самую позднюю осеннюю дату. Если даты с требуемым временем года в файле отсутствуют, то вывести пустую строку.`
	f.ru[73] = `Дан строковый файл, содержащий даты в формате, описанном в задании File67. Создать новый строковый файл, в котором даты из исходного файла располагались бы в порядке убывания.`
	f.ru[74] = `Даны два целых числа&nbsp;<i>I</i>, <i>J</i> и файл вещественных чисел, содержащий элементы квадратной матрицы (по строкам). Вывести элемент матрицы, расположенный в&nbsp;<i>I</i>-й строке и&nbsp;<i>J</i>-м столбце (строки и столбцы нумеруются от&nbsp;1). Если требуемый элемент отсутствует, то вывести&nbsp;0.`
	f.ru[75] = `Дан файл вещественных чисел, содержащий элементы квадратной матрицы (по строкам). Создать новый файл, содержащий элементы матрицы, транспонированной к исходной.`
	f.ru[76] = `Даны два файла вещественных чисел с именами&nbsp;<i>S</i><sub><i>A</i></sub> и&nbsp;<i>S</i><sub><i>B</i></sub>, содержащие элементы квадратных матриц&nbsp;<i>A</i> и&nbsp;<i>B</i> (по строкам). Создать новый файл с именем&nbsp;<i>S</i><sub><i>C</i></sub>, содержащий элементы произведения&nbsp;<i>A</i>&#183;<i>B</i>. Если матрицы&nbsp;<i>A</i> и&nbsp;<i>B</i> нельзя перемножать, то оставить файл&nbsp;<i>S</i><sub><i>C</i></sub> пустым.`
	f.ru[77] = `Даны два целых числа&nbsp;<i>I</i>, <i>J</i> и файл вещественных чисел, содержащий элементы прямоугольной матрицы (по строкам), причем первый элемент файла содержит количество столбцов матрицы. Вывести элемент матрицы, расположенный в&nbsp;<i>I</i>-й строке и&nbsp;<i>J</i>-м столбце (строки и столбцы нумеруются от&nbsp;1). Если требуемый элемент отсутствует, то вывести&nbsp;0.`
	f.ru[78] = `Дан файл вещественных чисел, содержащий элементы прямоугольной матрицы (по строкам), причем первый элемент файла содержит количество столбцов матрицы. Создать новый файл той же структуры, содержащий матрицу, транспонированную к исходной.`
	f.ru[79] = `Даны два файла вещественных чисел с именами&nbsp;<i>S</i><sub><i>A</i></sub> и&nbsp;<i>S</i><sub><i>B</i></sub>, содержащие элементы прямоугольных матриц&nbsp;<i>A</i> и&nbsp;<i>B</i> (по строкам), причем первый элемент каждого файла содержит количество столбцов соответствующей матрицы. Создать файл той же структуры с именем&nbsp;<i>S</i><sub><i>C</i></sub>, содержащий элементы произведения&nbsp;<i>A</i>&#183;<i>B</i>. Если матрицы&nbsp;<i>A</i> и&nbsp;<i>B</i> нельзя перемножать, то оставить файл&nbsp;<i>S</i><sub><i>C</i></sub> пустым.`
	f.ru[80] = `Дан файл вещественных чисел, содержащий элементы верхнетреугольной матрицы (по строкам). Создать новый файл, содержащий элементы ненулевой части данной матрицы (по строкам).`
	f.ru[81] = `Дан файл вещественных чисел, содержащий элементы нижнетреугольной матрицы (по строкам). Создать новый файл, содержащий элементы ненулевой части данной матрицы (по строкам).`
	f.ru[82] = `Дан файл вещественных чисел, содержащий элементы трехдиагональной матрицы (по строкам). Создать новый файл, содержащий элементы ненулевой части данной матрицы (по строкам).`
	f.ru[83] = `Даны два целых числа&nbsp;<i>I</i>, <i>J</i> и файл вещественных чисел, содержащий ненулевую часть верхнетреугольной матрицы (по строкам). Вывести порядок матрицы и ее элемент, расположенный в&nbsp;<i>I</i>-й строке и&nbsp;<i>J</i>-м столбце (строки и столбцы нумеруются от&nbsp;1). Если требуемый элемент находится в нулевой части матрицы, то вывести&nbsp;0; если элемент отсутствует, то вывести&nbsp;&#8722;1.`
	f.ru[84] = `Даны два целых числа&nbsp;<i>I</i>, <i>J</i> и файл вещественных чисел, содержащий ненулевую часть нижнетреугольной матрицы (по строкам). Вывести порядок матрицы и ее элемент, расположенный в&nbsp;<i>I</i>-й строке и&nbsp;<i>J</i>-м столбце (строки и столбцы нумеруются от&nbsp;1). Если требуемый элемент находится в нулевой части матрицы, то вывести&nbsp;0; если элемент отсутствует, то вывести&nbsp;&#8722;1.`
	f.ru[85] = `Даны два целых числа&nbsp;<i>I</i>, <i>J</i> и файл вещественных чисел, содержащий ненулевую часть трехдиагональной матрицы (по строкам). Вывести порядок матрицы и ее элемент, расположенный в&nbsp;<i>I</i>-й строке и&nbsp;<i>J</i>-м столбце (строки и столбцы нумеруются от&nbsp;1). Если требуемый элемент находится в нулевой части матрицы, то вывести&nbsp;0; если элемент отсутствует, то вывести&nbsp;&#8722;1.`
	f.ru[86] = `Дан файл вещественных чисел, содержащий ненулевую часть верхнетреугольной матрицы (по строкам). Создать новый файл, содержащий все элементы данной матрицы (по строкам).`
	f.ru[87] = `Дан файл вещественных чисел, содержащий ненулевую часть нижнетреугольной матрицы (по строкам). Создать новый файл, содержащий все элементы данной матрицы (по строкам).`
	f.ru[88] = `Дан файл вещественных чисел, содержащий ненулевую часть трехдиагональной матрицы (по строкам). Создать новый файл, содержащий все элементы данной матрицы (по строкам).`
	f.ru[89] = `Даны два файла вещественных чисел с именами&nbsp;<i>S</i><sub><i>A</i></sub> и&nbsp;<i>S</i><sub><i>B</i></sub>, содержащие ненулевые части верхнетреугольных матриц&nbsp;<i>A</i> и&nbsp;<i>B</i> (по строкам). Создать новый файл с именем&nbsp;<i>S</i><sub><i>C</i></sub>, содержащий ненулевую часть произведения&nbsp;<i>A</i>&#183;<i>B</i> (по строкам). Если матрицы&nbsp;<i>A</i> и&nbsp;<i>B</i> нельзя перемножать, то оставить файл&nbsp;<i>S</i><sub><i>C</i></sub> пустым.`
	f.ru[90] = `Даны два файла вещественных чисел с именами&nbsp;<i>S</i><sub><i>A</i></sub> и&nbsp;<i>S</i><sub><i>B</i></sub>, содержащие ненулевые части нижнетреугольных матриц&nbsp;<i>A</i> и&nbsp;<i>B</i> (по строкам). Создать новый файл с именем&nbsp;<i>S</i><sub><i>C</i></sub>, содержащий ненулевую часть произведения&nbsp;<i>A</i>&#183;<i>B</i> (по строкам). Если матрицы&nbsp;<i>A</i> и&nbsp;<i>B</i> нельзя перемножать, то оставить файл&nbsp;<i>S</i><sub><i>C</i></sub> пустым.`
}
